Failures in [node-test-pull-request/69842](https://ci.nodejs.org/job/node-test-pull-request/69842/) to [node-test-pull-request/69941](https://ci.nodejs.org/job/node-test-pull-request/69941/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2025-10-29.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2025-10-29 00:12 | 0       | 21      | 20       | 2       | 57      | 21.43%     |


### Jenkins Failure

| Reason | <code>Cannot run program "/bin/sh" (in directory "/home/iojs/build/workspace/node"): error=0, Failed to exec spawn helper: pid: 938203, exit value: 1</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/60370/](https://ci.nodejs.org/job/node-test-pull-request/69901/), [https://github.com/nodejs/node/pull/59982/](https://ci.nodejs.org/job/node-test-pull-request/69903/), [https://github.com/nodejs/node/pull/60437/](https://ci.nodejs.org/job/node-test-pull-request/69906/), [https://github.com/nodejs/node/pull/60422/](https://ci.nodejs.org/job/node-test-pull-request/69913/), [https://github.com/nodejs/node/pull/60388/](https://ci.nodejs.org/job/node-test-pull-request/69919/)) |
| Appeared | [test-rackspace-debian11-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian11-x64/67126/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69901/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69919/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian11-x64/67126/console">Example</a></summary>

```
java.io.IOException: Cannot run program "/bin/sh" (in directory "/home/iojs/build/workspace/node"): error=0, Failed to exec spawn helper: pid: 938203, exit value: 1
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at Jenkins v2.528.1//hudson.Proc$LocalProc.<init>(Proc.java:252)
	at Jenkins v2.528.1//hudson.Proc$LocalProc.<init>(Proc.java:221)
	at Jenkins v2.528.1//hudson.Launcher$LocalLauncher.launch(Launcher.java:995)
```
</details>

-------

| Reason | <code>Cannot run program "/bin/sh" (in directory "/home/iojs/build/workspace/node"): error=0, Failed to exec spawn helper: pid: 957237, exit value: 1</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/60422/](https://ci.nodejs.org/job/node-test-pull-request/69932/), [https://github.com/nodejs/node/pull/59982/](https://ci.nodejs.org/job/node-test-pull-request/69933/), [https://github.com/nodejs/node/pull/60443/](https://ci.nodejs.org/job/node-test-pull-request/69935/), [https://github.com/nodejs/node/pull/60464/](https://ci.nodejs.org/job/node-test-pull-request/69939/)) |
| Appeared | [test-rackspace-debian11-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian11-x64/67149/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69932/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69939/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian11-x64/67149/console">Example</a></summary>

```
java.io.IOException: Cannot run program "/bin/sh" (in directory "/home/iojs/build/workspace/node"): error=0, Failed to exec spawn helper: pid: 957237, exit value: 1
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at Jenkins v2.528.1//hudson.Proc$LocalProc.<init>(Proc.java:252)
	at Jenkins v2.528.1//hudson.Proc$LocalProc.<init>(Proc.java:221)
	at Jenkins v2.528.1//hudson.Launcher$LocalLauncher.launch(Launcher.java:995)
```
</details>

-------

| Reason | <code>Backing channel 'JNLP4-connect connection from ... is disconnected.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60330/](https://ci.nodejs.org/job/node-test-pull-request/69842/), [https://github.com/nodejs/node/pull/60331/](https://ci.nodejs.org/job/node-test-pull-request/69843/)) |
| Appeared | [test-digitalocean-ubuntu2404-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=ubuntu2404-x64/67067/console), [test-digitalocean-ubuntu2404-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=ubuntu2404-x64/67066/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69842/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69843/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=ubuntu2404-x64/67067/console">Example</a></summary>

```
java.io.IOException: Backing channel 'JNLP4-connect connection from 167.99.124.188/167.99.124.188:48116' is disconnected.
	at hudson.remoting.RemoteInvocationHandler.channelOrFail(RemoteInvocationHandler.java:227)
	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:306)
	at jdk.proxy2/jdk.proxy2.$Proxy105.isAlive(Unknown Source)
	at hudson.Launcher$RemoteLauncher$ProcImpl.isAlive(Launcher.java:1227)
	at hudson.Launcher$RemoteLauncher$ProcImpl.join(Launcher.java:1219)
```
</details>

-------


### Build Failure

| Reason | <code>ERROR: Step ‘Publish JUnit test result report’ failed: no workspace for ...</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 11 ([https://github.com/nodejs/node/pull/60330/](https://ci.nodejs.org/job/node-test-pull-request/69842/), [https://github.com/nodejs/node/pull/60331/](https://ci.nodejs.org/job/node-test-pull-request/69843/), [https://github.com/nodejs/node/pull/60367/](https://ci.nodejs.org/job/node-test-pull-request/69856/), [https://github.com/nodejs/node/pull/60390/](https://ci.nodejs.org/job/node-test-pull-request/69883/), [https://github.com/nodejs/node/pull/60190/](https://ci.nodejs.org/job/node-test-pull-request/69888/), [https://github.com/nodejs/node/pull/60391/](https://ci.nodejs.org/job/node-test-pull-request/69889/), [https://github.com/nodejs/node/pull/60413/](https://ci.nodejs.org/job/node-test-pull-request/69911/), [https://github.com/nodejs/node/pull/60399/](https://ci.nodejs.org/job/node-test-pull-request/69912/), [https://github.com/nodejs/node/pull/60447/](https://ci.nodejs.org/job/node-test-pull-request/69920/), [https://github.com/nodejs/node/pull/60443/](https://ci.nodejs.org/job/node-test-pull-request/69923/), [https://github.com/nodejs/node/pull/60248/](https://ci.nodejs.org/job/node-test-pull-request/69927/)) |
| Appeared | [vm-k5d2b](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx15-arm64/66902/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69842/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69927/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx15-arm64/66902/console">Example</a></summary>

```
ERROR: Step ‘Publish JUnit test result report’ failed: no workspace for node-test-commit-osx/nodes=osx15-arm64 #66902
Collecting metadata...
Metadata collection done.
[Checks API] No suitable checks publisher found.
Notifying upstream projects of job completion
Finished: FAILURE
```
</details>

-------

| Reason | <code>fatal: No rebase in progress?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60331/](https://ci.nodejs.org/job/node-test-pull-request/69843/), [https://github.com/nodejs/node/pull/60281/](https://ci.nodejs.org/job/node-test-pull-request/69847/)) |
| Appeared | [test-digitalocean-ubuntu2404_sharedlibs_container-x64-6](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_shared_x64/53256/console), [test-digitalocean-ubuntu2404_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_shared_x64/53252/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69843/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69847/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_shared_x64/53256/console">Example</a></summary>

```
fatal: No rebase in progress?
```
</details>

-------


### JSTest Failure

| Reason | <code>sequential/test-worker-prof</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 8 ([https://github.com/nodejs/node/pull/60364/](https://ci.nodejs.org/job/node-test-pull-request/69858/), [https://github.com/nodejs/node/pull/60390/](https://ci.nodejs.org/job/node-test-pull-request/69879/), [https://github.com/nodejs/node/pull/60391/](https://ci.nodejs.org/job/node-test-pull-request/69887/), [https://github.com/nodejs/node/pull/60419/](https://ci.nodejs.org/job/node-test-pull-request/69890/), [https://github.com/nodejs/node/pull/60434/](https://ci.nodejs.org/job/node-test-pull-request/69905/), [https://github.com/nodejs/node/pull/60422/](https://ci.nodejs.org/job/node-test-pull-request/69913/), [https://github.com/nodejs/node/pull/60388/](https://ci.nodejs.org/job/node-test-pull-request/69919/), [https://github.com/nodejs/node/pull/60387/](https://ci.nodejs.org/job/node-test-pull-request/69938/)) |
| Appeared | [test-azure_msft-win10_vs2019-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win10-COMPILED_BY-vs2022_clang/37451/console), [test-azure_msft-win10_vs2019-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2022_clang/37433/console), [vm-qljhz](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67545/console), [test-azure_msft-win11_vs2022-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2022_clang/37402/console), [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/52062/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69858/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69938/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win10-COMPILED_BY-vs2022_clang/37451/console">Example</a></summary>

```
not ok 1167 sequential/test-worker-prof
  ---
  duration_ms: 2387.95000
  severity: fail
  exitcode: 1
  stack: |-
    files found in working directory before worker starts [ 'isolate-000002269D63B000-6416-v8.log' ]
    parent prof file: isolate-000002269D63B000-6416-v8.log
    parent posted 46326 messages
    files found in working directory before worker exits [
      'isolate-000002269D63B000-6416-v8.log',
      'isolate-00000226B7329000-6416-v8.log'
    ]
    worker prof file: isolate-00000226B7329000-6416-v8.log
    
    worker ticks 5
    parent ticks 34
    node:internal/assert/utils:146
      throw error;
      ^
    
    AssertionError [ERR_ASSERTION]: worker ticks <= 10:
    tick,0x7ff79ff1c5aa,101962,0,0x0,3,0x226d7f8297e,0x226d7f82607,0x2b99e3d2f61
    tick,0x7ff79fd05863,118036,0,0x0,2,0x226d7f8297e,0x226d7f82607,0x2b99e3ea938,0x226d7f82a4f,0x226d7f82607,0x2b99e3e9501,0x226d7f82a4f,0x226d7f82607,0x2b99e3e73fb,0x226d7f82a4f,0x226d7f82607,0x2b99e3d30c3
    tick,0x7ff7a0215b82,149885,0,0x0,2,0x226d7...
```
</details>

-------

| Reason | <code>es-module/test-esm-wasm</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/60434/](https://ci.nodejs.org/job/node-test-pull-request/69905/), [https://github.com/nodejs/node/pull/60429/](https://ci.nodejs.org/job/node-test-pull-request/69908/), [https://github.com/nodejs/node/pull/60422/](https://ci.nodejs.org/job/node-test-pull-request/69913/), [https://github.com/nodejs/node/pull/60388/](https://ci.nodejs.org/job/node-test-pull-request/69919/)) |
| Appeared | [test-azure_msft-win10_vs2019-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2019/37423/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69905/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69919/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2019/37423/console">Example</a></summary>

```
not ok 58 es-module/test-esm-wasm
  ---
  duration_ms: 1008.00200
  severity: fail
  exitcode: 1
  stack: |-
    TAP version 13
    # Subtest: ESM: WASM modules
        # Subtest: should load exports
        ok 1 - should load exports
          ---
          duration_ms: 251.6482
          ...

```
</details>

-------

| Reason | <code>parallel/test-watch-mode-kill-signal-override</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/60318/](https://ci.nodejs.org/job/node-test-pull-request/69860/), [https://github.com/nodejs/node/pull/60372/](https://ci.nodejs.org/job/node-test-pull-request/69871/), [https://github.com/nodejs/node/pull/60190/](https://ci.nodejs.org/job/node-test-pull-request/69888/), [https://github.com/nodejs/node/pull/60391/](https://ci.nodejs.org/job/node-test-pull-request/69889/)) |
| Appeared | [vm-jgrbo](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67547/console), [vm-yinh4](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67546/console), [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/52074/console), [test-azure-ubuntu2204_container-arm64-5](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/60808/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69860/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69889/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67547/console">Example</a></summary>

```
not ok 4425 parallel/test-watch-mode-kill-signal-override
  ---
  duration_ms: 120094.59500
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>addons/stringbytes-external-exceed-max/test-stringbytes-external-exceed-max</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/60388/](https://ci.nodejs.org/job/node-test-pull-request/69919/), [https://github.com/nodejs/node/pull/60447/](https://ci.nodejs.org/job/node-test-pull-request/69920/), [https://github.com/nodejs/node/pull/60427/](https://ci.nodejs.org/job/node-test-pull-request/69936/)) |
| Appeared | [test-osuosl-aix72-ppc64_be-4](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59566/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69919/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69936/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59566/console">Example</a></summary>

```
not ok 4617 addons/stringbytes-external-exceed-max/test-stringbytes-external-exceed-max
  ---
  duration_ms: 120108.78300
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    1..0 # Skipped: intensive toString tests due to memory confinements
  ...

```
</details>

-------

| Reason | <code>addons/stringbytes-external-exceed-max/test-stringbytes-external-exceed-max-by-1-binary</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/60434/](https://ci.nodejs.org/job/node-test-pull-request/69907/), [https://github.com/nodejs/node/pull/60351/](https://ci.nodejs.org/job/node-test-pull-request/69922/), [https://github.com/nodejs/node/pull/60387/](https://ci.nodejs.org/job/node-test-pull-request/69938/)) |
| Appeared | [test-osuosl-aix72-ppc64_be-4](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59567/console), [test-ibm-aix72-ppc64_be-2](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59558/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69907/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69938/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59567/console">Example</a></summary>

```
not ok 4620 addons/stringbytes-external-exceed-max/test-stringbytes-external-exceed-max-by-1-binary
  ---
  duration_ms: 120127.66000
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    1..0 # Skipped: intensive toString tests due to memory confinements
  ...

```
</details>

-------

| Reason | <code>addons/stringbytes-external-exceed-max/test-stringbytes-external-exceed-max-by-1-utf8</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/60434/](https://ci.nodejs.org/job/node-test-pull-request/69907/), [https://github.com/nodejs/node/pull/60388/](https://ci.nodejs.org/job/node-test-pull-request/69924/), [https://github.com/nodejs/node/pull/60387/](https://ci.nodejs.org/job/node-test-pull-request/69940/)) |
| Appeared | [test-osuosl-aix72-ppc64_be-4](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59569/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69907/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69940/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59569/console">Example</a></summary>

```
not ok 4622 addons/stringbytes-external-exceed-max/test-stringbytes-external-exceed-max-by-1-utf8
  ---
  duration_ms: 120047.96200
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    1..0 # Skipped: intensive toString tests due to memory confinements
  ...

```
</details>

-------

| Reason | <code>parallel/test-quic-test-client</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/60331/](https://ci.nodejs.org/job/node-test-pull-request/69843/), [https://github.com/nodejs/node/pull/60391/](https://ci.nodejs.org/job/node-test-pull-request/69880/), [https://github.com/nodejs/node/pull/60447/](https://ci.nodejs.org/job/node-test-pull-request/69920/)) |
| Appeared | [vm-mu2vx](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67581/console), [vm-z2sho](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67534/console), [vm-q9xx6](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67494/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69843/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69920/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67581/console">Example</a></summary>

```
not ok 2577 parallel/test-quic-test-client
  ---
  duration_ms: 1856.09700
  severity: fail
  exitcode: 1
  stack: |-
    /Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/out/Release/ngtcp2_test_client
    node:internal/modules/run_main:107
        triggerUncaughtException(
        ^
    
    AssertionError [ERR_ASSERTION]: Missing expected rejection.
        at process.processTicksAndRejections (node:internal/process/task_queues:103:5)
        at async file:///Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/test/parallel/test-quic-test-client.mjs:36:1 {
      generatedMessage: false,
      code: 'ERR_ASSERTION',
      actual: undefined,
      expected: { message: /Process exited with code 1 and signal null/ },
      operator: 'rejects',
      diff: 'simple'
    }
    
    Node.js v26.0.0-pre
  ...

```
</details>

-------

| Reason | <code>addons/stringbytes-external-exceed-max/test-stringbytes-external-exceed-max-by-1-base64</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60388/](https://ci.nodejs.org/job/node-test-pull-request/69919/), [https://github.com/nodejs/node/pull/60387/](https://ci.nodejs.org/job/node-test-pull-request/69938/)) |
| Appeared | [test-osuosl-aix72-ppc64_be-4](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59567/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69919/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69938/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59567/console">Example</a></summary>

```
not ok 4619 addons/stringbytes-external-exceed-max/test-stringbytes-external-exceed-max-by-1-base64
  ---
  duration_ms: 120090.81900
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    1..0 # Skipped: intensive toString tests due to memory confinements
  ...

```
</details>

-------

| Reason | <code>addons/stringbytes-external-exceed-max/test-stringbytes-external-exceed-max-by-1-hex</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60387/](https://ci.nodejs.org/job/node-test-pull-request/69938/), [https://github.com/nodejs/node/pull/60427/](https://ci.nodejs.org/job/node-test-pull-request/69941/)) |
| Appeared | [test-ibm-aix72-ppc64_be-2](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59570/console), [test-osuosl-aix72-ppc64_be-4](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59567/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69938/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69941/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59570/console">Example</a></summary>

```
not ok 4621 addons/stringbytes-external-exceed-max/test-stringbytes-external-exceed-max-by-1-hex
  ---
  duration_ms: 120090.60400
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    1..0 # Skipped: intensive toString tests due to memory confinements
  ...

```
</details>

-------

| Reason | <code>addons/stringbytes-external-exceed-max/test-stringbytes-external-exceed-max-by-2</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60388/](https://ci.nodejs.org/job/node-test-pull-request/69924/), [https://github.com/nodejs/node/pull/60427/](https://ci.nodejs.org/job/node-test-pull-request/69941/)) |
| Appeared | [test-ibm-aix72-ppc64_be-2](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59570/console), [test-osuosl-aix72-ppc64_be-4](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59561/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69924/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69941/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59570/console">Example</a></summary>

```
not ok 4623 addons/stringbytes-external-exceed-max/test-stringbytes-external-exceed-max-by-2
  ---
  duration_ms: 120087.71200
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    1..0 # Skipped: intensive toString tests due to memory confinements
  ...

```
</details>

-------

| Reason | <code>parallel/test-http2-close-while-writing</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60313/](https://ci.nodejs.org/job/node-test-pull-request/69848/), [https://github.com/nodejs/node/pull/60390/](https://ci.nodejs.org/job/node-test-pull-request/69883/)) |
| Appeared | [vm-wfocy](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67540/console), [test-osuosl-rhel8-ppc64_le-2](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel8-ppc64le/61216/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69848/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69883/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67540/console">Example</a></summary>

```
not ok 2310 parallel/test-http2-close-while-writing
  ---
  duration_ms: 120092.64800
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-net-connect-abort-controller</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60374/](https://ci.nodejs.org/job/node-test-pull-request/69862/), [https://github.com/nodejs/node/pull/60190/](https://ci.nodejs.org/job/node-test-pull-request/69888/)) |
| Appeared | [test-mnx-smartos23-x64-6](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos23-x64/62945/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69862/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69888/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos23-x64/62945/console">Example</a></summary>

```
not ok 3536 parallel/test-net-connect-abort-controller
  ---
  duration_ms: 300057.61500
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-perf-hooks-timerify</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60370/](https://ci.nodejs.org/job/node-test-pull-request/69901/), [https://github.com/nodejs/node/pull/60388/](https://ci.nodejs.org/job/node-test-pull-request/69919/)) |
| Appeared | [test-ibm-rhel8-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/67144/console), [test-ibm-rhel8-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/67128/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69901/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69919/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/67144/console">Example</a></summary>

```
not ok 2847 parallel/test-perf-hooks-timerify
  ---
  duration_ms: 200.17400
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/histogram:292
        validateInteger(val, 'val', 1);
        ^
    
    RangeError [ERR_OUT_OF_RANGE]: The value of "val" is out of range. It must be >= 1 && <= 9007199254740991. Received 0
        at RecordableHistogram.record (node:internal/histogram:292:5)
        at processComplete (node:internal/perf/timerify:40:15)
        at timerified m (node:internal/perf/timerify:87:5)
        at /home/iojs/build/workspace/node/test/parallel/test-perf-hooks-timerify.js:107:5
        at runNextTicks (node:internal/process/task_queues:64:5)
        at listOnTimeout (node:internal/timers:567:9)
        at process.processTimers (node:internal/timers:541:7) {
      code: 'ERR_OUT_OF_RANGE'
    }
    
    Node.js v26.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-runner-output</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60190/](https://ci.nodejs.org/job/node-test-pull-request/69888/), [https://github.com/nodejs/node/pull/60391/](https://ci.nodejs.org/job/node-test-pull-request/69889/)) |
| Appeared | [vm-rgwwn](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67543/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69888/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69889/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67543/console">Example</a></summary>

```
not ok 3140 parallel/test-runner-output
  ---
  duration_ms: 120142.32600
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    TAP version 13
    # Subtest: test runner output
        # Subtest: test-runner/output/abort.js
        ok 1 - test-runner/output/abort.js
          ---
          duration_ms: 2592.095926
          ...

```
</details>

-------

| Reason | <code>parallel/test-watch-mode-files_watcher</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60454/](https://ci.nodejs.org/job/node-test-pull-request/69921/), [https://github.com/nodejs/node/pull/60248/](https://ci.nodejs.org/job/node-test-pull-request/69927/)) |
| Appeared | [vm-foi6n](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67589/console), [test-rackspace-win2022_vs2022-x64-6](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2022-COMPILED_BY-vs2022_clang/37440/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69921/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69927/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67589/console">Example</a></summary>

```
not ok 4253 parallel/test-watch-mode-files_watcher
  ---
  duration_ms: 120105.99700
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-watch-mode-kill-signal-default</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60330/](https://ci.nodejs.org/job/node-test-pull-request/69842/), [https://github.com/nodejs/node/pull/60413/](https://ci.nodejs.org/job/node-test-pull-request/69911/)) |
| Appeared | [vm-nbcl4](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67570/console), [vm-2xshg](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67493/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69842/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69911/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67570/console">Example</a></summary>

```
not ok 4426 parallel/test-watch-mode-kill-signal-default
  ---
  duration_ms: 120100.15400
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>sequential/test-perf-hooks</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60330/](https://ci.nodejs.org/job/node-test-pull-request/69842/), [https://github.com/nodejs/node/pull/60331/](https://ci.nodejs.org/job/node-test-pull-request/69843/)) |
| Appeared | [vm-k7hpr](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67492/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69842/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69843/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67492/console">Example</a></summary>

```
not ok 4747 sequential/test-perf-hooks
  ---
  duration_ms: 895.86800
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/assert/utils:77
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: Date.now() - performance.timeOrigin (491.593017578125) - process.uptime() * 1000 (371.23216399999995) = 120.36085357812505 >= +- 50
        at Object.<anonymous> (/Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/sequential/test-perf-hooks.js:36:3)
        at Module._compile (node:internal/modules/cjs/loader:1760:14)
        at Object..js (node:internal/modules/cjs/loader:1893:10)
        at Module.load (node:internal/modules/cjs/loader:1480:32)
        at Module._load (node:internal/modules/cjs/loader:1299:12)
        at TracingChannel.traceSync (node:diagnostics_channel:328:14)
        at wrapModuleLoad (node:internal/modules/cjs/loader:244:24)
        at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
        at node:internal/main/run_main_...
```
</details>

-------

