Failures in [node-test-pull-request/69537](https://ci.nodejs.org/job/node-test-pull-request/69537/) to [node-test-pull-request/69628](https://ci.nodejs.org/job/node-test-pull-request/69628/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2025-10-09.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2025-10-09 00:10 | 4       | 0       | 31       | 3       | 62      | 0.00%      |


### Jenkins Failure

| Reason | <code>Build timed out (after 30 minutes). Marking the build as failed.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/59952/](https://ci.nodejs.org/job/node-test-pull-request/69540/), [https://github.com/nodejs/node/pull/60060/](https://ci.nodejs.org/job/node-test-pull-request/69545/), [https://github.com/nodejs/node/pull/60064/](https://ci.nodejs.org/job/node-test-pull-request/69571/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/37129/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69540/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69571/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/37129/console">Example</a></summary>

```
Build timed out (after 30 minutes). Marking the build as failed.
```
</details>

-------

| Reason | <code>Backing channel 'JNLP4-connect connection from ... is disconnected.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60142/](https://ci.nodejs.org/job/node-test-pull-request/69594/), [https://github.com/nodejs/node/pull/60144/](https://ci.nodejs.org/job/node-test-pull-request/69595/)) |
| Appeared | [test-ibm-alpine321_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/66896/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69594/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69595/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/66896/console">Example</a></summary>

```
java.io.IOException: Backing channel 'JNLP4-connect connection from 9.1a.7534.ip4.static.sl-reverse.com/52.117.26.9:57592' is disconnected.
	at hudson.remoting.RemoteInvocationHandler.channelOrFail(RemoteInvocationHandler.java:227)
	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:306)
	at jdk.proxy2/jdk.proxy2.$Proxy218.isAlive(Unknown Source)
	at hudson.Launcher$RemoteLauncher$ProcImpl.isAlive(Launcher.java:1227)
	at hudson.Launcher$RemoteLauncher$ProcImpl.join(Launcher.java:1219)
```
</details>

-------

| Reason | <code>Build timed out (after 60 minutes). Marking the build as failed.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60059/](https://ci.nodejs.org/job/node-test-pull-request/69556/), [https://github.com/nodejs/node/pull/60136/](https://ci.nodejs.org/job/node-test-pull-request/69597/)) |
| Appeared | [test-ibm-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/53067/console), [test-ibm-ubuntu2404_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_icu_x64/53067/console), [test-ibm-ubuntu2404_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_openssl30_x64/53067/console), [test-ibm-ubuntu2404_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_openssl32_x64/53067/console), [test-ibm-ubuntu2404_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_openssl35_x64/53067/console), [test-ibm-ubuntu2404_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_shared_x64/53067/console), [vm-wpeon](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-arm64/67157/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69556/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69597/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/53067/console">Example</a></summary>

```
Build timed out (after 60 minutes). Marking the build as failed.
```
</details>

-------


### Git Failure


### Build Failure

| Reason | <code>ERROR: Step ‘Record fingerprints of files to track usage’ failed: no workspace for ...</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/60142/](https://ci.nodejs.org/job/node-test-pull-request/69594/), [https://github.com/nodejs/node/pull/60144/](https://ci.nodejs.org/job/node-test-pull-request/69595/), [https://github.com/nodejs/node/pull/60136/](https://ci.nodejs.org/job/node-test-pull-request/69601/)) |
| Appeared | [test-rackspace-debian12-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian12-x64/66903/console), [test-ibm-alpine322_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-latest-x64/66896/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69594/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69601/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian12-x64/66903/console">Example</a></summary>

```
ERROR: Step ‘Record fingerprints of files to track usage’ failed: no workspace for node-test-commit-linux/nodes=debian12-x64 #66903
Collecting metadata...
Metadata collection done.
[Checks API] No suitable checks publisher found.
Notifying upstream projects of job completion
Finished: FAILURE
```
</details>

-------

| Reason | <code>Failed to trigger node-test-commit</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/60060/](https://ci.nodejs.org/job/node-test-pull-request/69543/), [https://github.com/nodejs/node/pull/59952/](https://ci.nodejs.org/job/node-test-pull-request/69544/), [https://github.com/nodejs/node/pull/60132/](https://ci.nodejs.org/job/node-test-pull-request/69587/)) |
| Appeared | [test-mnx-ubuntu2204-x64-1](https://ci.nodejs.org/job/node-test-pull-request/69587/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69543/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69587/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-pull-request/69587/console">Example</a></summary>

```
Failed to trigger node-test-commit
```
</details>

-------

| Reason | <code>fatal: detected dubious ownership in repository at 'C:/workspace/node-test-binary-windows-js-suites/build'</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59952/](https://ci.nodejs.org/job/node-test-pull-request/69540/), [https://github.com/nodejs/node/pull/60060/](https://ci.nodejs.org/job/node-test-pull-request/69545/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-COMPILED_BY-vs2019/37085/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69540/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69545/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-COMPILED_BY-vs2019/37085/console">Example</a></summary>

```
fatal: detected dubious ownership in repository at 'C:/workspace/node-test-binary-windows-js-suites/build'
```
</details>

-------


### JSTest Failure

| Reason | <code>parallel/test-without-async-context-frame</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 17 ([https://github.com/nodejs/node/pull/59805/](https://ci.nodejs.org/job/node-test-pull-request/69537/), [https://github.com/nodejs/node/pull/60060/](https://ci.nodejs.org/job/node-test-pull-request/69545/), [https://github.com/nodejs/node/pull/60036/](https://ci.nodejs.org/job/node-test-pull-request/69550/), [https://github.com/nodejs/node/pull/59952/](https://ci.nodejs.org/job/node-test-pull-request/69553/), [https://github.com/nodejs/node/pull/60123/](https://ci.nodejs.org/job/node-test-pull-request/69569/), [https://github.com/nodejs/node/pull/60059/](https://ci.nodejs.org/job/node-test-pull-request/69570/), [https://github.com/nodejs/node/pull/60008/](https://ci.nodejs.org/job/node-test-pull-request/69577/), [https://github.com/nodejs/node/pull/60061/](https://ci.nodejs.org/job/node-test-pull-request/69593/), [https://github.com/nodejs/node/pull/60142/](https://ci.nodejs.org/job/node-test-pull-request/69594/), [https://github.com/nodejs/node/pull/60098/](https://ci.nodejs.org/job/node-test-pull-request/69596/), [https://github.com/nodejs/node/pull/59889/](https://ci.nodejs.org/job/node-test-pull-request/69603/), [https://github.com/nodejs/node/pull/60153/](https://ci.nodejs.org/job/node-test-pull-request/69606/), [https://github.com/nodejs/node/pull/60160/](https://ci.nodejs.org/job/node-test-pull-request/69617/), [https://github.com/nodejs/node/pull/59853/](https://ci.nodejs.org/job/node-test-pull-request/69618/), [https://github.com/nodejs/node/pull/59931/](https://ci.nodejs.org/job/node-test-pull-request/69619/), [https://github.com/nodejs/node/pull/60148/](https://ci.nodejs.org/job/node-test-pull-request/69623/), [https://github.com/nodejs/node/pull/60144/](https://ci.nodejs.org/job/node-test-pull-request/69624/)) |
| Appeared | [vm-6zndc](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67236/console), [vm-hgw3t](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67235/console), [vm-ebad9](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67231/console), [vm-dm937](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67230/console), [vm-x4kfi](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67229/console), [vm-532du](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67215/console), [vm-f8xgr](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67211/console), [test-digitalocean-ubuntu2404_sharedlibs_container-x64-9](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_shared_x64/53072/console), [test-digitalocean-ubuntu2404_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_shared_x64/53068/console), [test-digitalocean-ubuntu2404_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_shared_x64/53065/console), [vm-1z6qj](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67202/console), [test-ibm-ubuntu2404_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_shared_x64/53064/console), [vm-2on5c](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67201/console), [vm-mqg3w](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67181/console), [vm-tklkv](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67173/console), [vm-1i229](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67172/console), [vm-66gbr](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67154/console), [vm-qbevq](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67144/console), [vm-ujjv9](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67143/console), [vm-2ri4d](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67136/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69537/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69624/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67236/console">Example</a></summary>

```
not ok 4174 parallel/test-without-async-context-frame
  ---
  duration_ms: 120120.73700
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>sequential/test-worker-prof</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 10 ([https://github.com/nodejs/node/pull/59968/](https://ci.nodejs.org/job/node-test-pull-request/69567/), [https://github.com/nodejs/node/pull/60125/](https://ci.nodejs.org/job/node-test-pull-request/69579/), [https://github.com/nodejs/node/pull/60061/](https://ci.nodejs.org/job/node-test-pull-request/69593/), [https://github.com/nodejs/node/pull/60142/](https://ci.nodejs.org/job/node-test-pull-request/69594/), [https://github.com/nodejs/node/pull/60098/](https://ci.nodejs.org/job/node-test-pull-request/69596/), [https://github.com/nodejs/node/pull/59889/](https://ci.nodejs.org/job/node-test-pull-request/69599/), [https://github.com/nodejs/node/pull/60153/](https://ci.nodejs.org/job/node-test-pull-request/69606/), [https://github.com/nodejs/node/pull/59853/](https://ci.nodejs.org/job/node-test-pull-request/69614/), [https://github.com/nodejs/node/pull/60148/](https://ci.nodejs.org/job/node-test-pull-request/69623/), [https://github.com/nodejs/node/pull/60168/](https://ci.nodejs.org/job/node-test-pull-request/69628/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-6](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/37173/console), [test-azure_msft-win10_vs2019-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win10-COMPILED_BY-vs2022_clang/37169/console), [test-azure_msft-win10_vs2019-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win10-COMPILED_BY-vs2022_clang/37164/console), [test-azure_msft-win10_vs2019-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win10-COMPILED_BY-vs2022_clang/37163/console), [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/51877/console), [test-azure_msft-win11_vs2022-arm64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/37130/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69567/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69628/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/37173/console">Example</a></summary>

```
not ok 1143 sequential/test-worker-prof
  ---
  duration_ms: 2703.56100
  severity: fail
  exitcode: 1
  stack: |-
    files found in working directory before worker starts [ 'isolate-000001C5D0014000-11924-v8.log' ]
    parent prof file: isolate-000001C5D0014000-11924-v8.log
    parent posted 38227 messages
    files found in working directory before worker exits [
      'isolate-000001C5D0014000-11924-v8.log',
      'isolate-000001C5D8DA8000-11924-v8.log'
    ]
    worker prof file: isolate-000001C5D8DA8000-11924-v8.log
    
    worker ticks 14
    parent ticks 41
    node:internal/assert/utils:77
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: worker ticks <= 15:
    tick,0x7ff796520a60,37924,0,0x0,0
    tick,0x7ff796384884,245918,0,0x0,3,0x13cc2cd39cd,0x13cc2cd2d6b,0x13cc2cd2c5b,0x13cc2cd2bb3,0x13cc2cca6fb,0x13cc2cc9cec,0x3975274560c
    tick,0x7ff925af0e74,821930,0,0x0,0,0x1c5ea088378,0x1c5ea04e3ec,0x1c5ea088588
    tick,0x7ff925af1780,933908,0,0x0,0,0x1c5ea088378,0x1c5ea04e3ec,0x1c...
```
</details>

-------

| Reason | <code>parallel/test-runner-run-watch</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 7 ([https://github.com/nodejs/node/pull/59805/](https://ci.nodejs.org/job/node-test-pull-request/69537/), [https://github.com/nodejs/node/pull/60060/](https://ci.nodejs.org/job/node-test-pull-request/69554/), [https://github.com/nodejs/node/pull/60059/](https://ci.nodejs.org/job/node-test-pull-request/69556/), [https://github.com/nodejs/node/pull/59952/](https://ci.nodejs.org/job/node-test-pull-request/69558/), [https://github.com/nodejs/node/pull/60061/](https://ci.nodejs.org/job/node-test-pull-request/69563/), [https://github.com/nodejs/node/pull/60123/](https://ci.nodejs.org/job/node-test-pull-request/69569/), [https://github.com/nodejs/node/pull/60064/](https://ci.nodejs.org/job/node-test-pull-request/69571/)) |
| Appeared | [vm-jyntm](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67174/console), [vm-1i229](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67172/console), [vm-3jyui](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67164/console), [vm-qe5tw](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67159/console), [vm-66gbr](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67157/console), [vm-qbevq](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67144/console), [vm-asmhb](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67139/console), [vm-fca2x](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67138/console), [vm-2ri4d](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67136/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69537/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69571/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67174/console">Example</a></summary>

```
not ok 2802 parallel/test-runner-run-watch
  ---
  duration_ms: 27535.14200
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'should run with different cwd while in watch mode and isolation "none"'
    Location: test/parallel/test-runner-run-watch.mjs:358:5
    AssertionError [ERR_ASSERTION]: function should not have been called at file:///Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/test/parallel/test-runner-run-watch.mjs:373
    called with arguments: [Object: null prototype] {
      name: '<anonymous>',
      nesting: 0,
      testNumber: 1,
      details: [Object: null prototype] {
        duration_ms: 210.990362,
        type: 'test',
        error: [Error: test failed] {
          code: 'ERR_TEST_FAILURE',
          failureType: 'testCodeFailure',
          cause: 'test failed',
          exitCode: null,
          signal: 'SIGTERM'
        }
      },
      line: 1,
      column: 1,
      file: '/Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/<anonymo...
```
</details>

-------

| Reason | <code>parallel/test-runner-watch-mode-kill-signal</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 7 ([https://github.com/nodejs/node/pull/59805/](https://ci.nodejs.org/job/node-test-pull-request/69537/), [https://github.com/nodejs/node/pull/60060/](https://ci.nodejs.org/job/node-test-pull-request/69541/), [https://github.com/nodejs/node/pull/60059/](https://ci.nodejs.org/job/node-test-pull-request/69549/), [https://github.com/nodejs/node/pull/60123/](https://ci.nodejs.org/job/node-test-pull-request/69564/), [https://github.com/nodejs/node/pull/60132/](https://ci.nodejs.org/job/node-test-pull-request/69584/), [https://github.com/nodejs/node/pull/59432/](https://ci.nodejs.org/job/node-test-pull-request/69611/), [https://github.com/nodejs/node/pull/60148/](https://ci.nodejs.org/job/node-test-pull-request/69615/)) |
| Appeared | [vm-ebad9](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67227/console), [vm-htd7e](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-arm64/67222/console), [vm-zav92](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67190/console), [test-azure-ubuntu2204_container-arm64-5](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/60617/console), [vm-asmhb](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67139/console), [vm-2ri4d](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67136/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69537/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69615/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67227/console">Example</a></summary>

```
not ok 3201 parallel/test-runner-watch-mode-kill-signal
  ---
  duration_ms: 120274.08400
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>client-proxy/test-https-proxy-request-invalid-char-in-url</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/59805/](https://ci.nodejs.org/job/node-test-pull-request/69537/), [https://github.com/nodejs/node/pull/60060/](https://ci.nodejs.org/job/node-test-pull-request/69554/), [https://github.com/nodejs/node/pull/60123/](https://ci.nodejs.org/job/node-test-pull-request/69569/), [https://github.com/nodejs/node/pull/59889/](https://ci.nodejs.org/job/node-test-pull-request/69599/), [https://github.com/nodejs/node/pull/59432/](https://ci.nodejs.org/job/node-test-pull-request/69612/), [https://github.com/nodejs/node/pull/59853/](https://ci.nodejs.org/job/node-test-pull-request/69618/)) |
| Appeared | [vm-dm937](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67230/console), [vm-qghf4](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67223/console), [vm-532du](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67207/console), [vm-1i229](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67172/console), [vm-qe5tw](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67155/console), [vm-2ri4d](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67136/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69537/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69618/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67230/console">Example</a></summary>

```
not ok 4374 client-proxy/test-https-proxy-request-invalid-char-in-url
  ---
  duration_ms: 750.01000
  severity: fail
  exitcode: 1
  stack: |-
    [Upstream server] responding to request for '/carriage-return-in-host'
    [Upstream server] responding to request for '/newline-in-host'
    [Upstream server] responding to request for '/crlf-in-host'
    [Upstream server] responding to request for '/newline-in-port'
    [Upstream server] responding to request for '/carriage-return-in-port'
    [Proxy client] Received response from server for 'https://local\rhost:62865/carriage-return-in-host': Response for '/carriage-return-in-host'
    [Proxy client] #1 closed request for: 'https://local\rhost:62865/carriage-return-in-host'
    [Proxy client] Received response from server for 'https://local\nhost:62865/newline-in-host': Response for '/newline-in-host'
    [Proxy client] #2 closed request for: 'https://local\nhost:62865/newline-in-host'
    [Proxy client] Received response from server for 'https://local\r\nhost:...
```
</details>

-------

| Reason | <code>sequential/test-perf-hooks</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/60059/](https://ci.nodejs.org/job/node-test-pull-request/69556/), [https://github.com/nodejs/node/pull/60061/](https://ci.nodejs.org/job/node-test-pull-request/69578/), [https://github.com/nodejs/node/pull/60144/](https://ci.nodejs.org/job/node-test-pull-request/69595/), [https://github.com/nodejs/node/pull/60153/](https://ci.nodejs.org/job/node-test-pull-request/69606/)) |
| Appeared | [vm-532du](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67215/console), [test-digitalocean-ubuntu2404_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_openssl30_x64/53065/console), [vm-zqytd](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67183/console), [vm-66gbr](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67157/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69556/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69606/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67215/console">Example</a></summary>

```
not ok 4762 sequential/test-perf-hooks
  ---
  duration_ms: 986.89000
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/assert/utils:77
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: Date.now() - performance.timeOrigin (491.64990234375) - process.uptime() * 1000 (365.44320000000005) = 126.20670234374995 >= +- 50
        at Object.<anonymous> (/Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/test/sequential/test-perf-hooks.js:36:3)
        at Module._compile (node:internal/modules/cjs/loader:1759:14)
        at Object..js (node:internal/modules/cjs/loader:1892:10)
        at Module.load (node:internal/modules/cjs/loader:1479:32)
        at Module._load (node:internal/modules/cjs/loader:1298:12)
        at TracingChannel.traceSync (node:diagnostics_channel:328:14)
        at wrapModuleLoad (node:internal/modules/cjs/loader:244:24)
        at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
        at node:internal/main/run_main...
```
</details>

-------

| Reason | <code>wpt/test-hr-time</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/60009/](https://ci.nodejs.org/job/node-test-pull-request/69573/), [https://github.com/nodejs/node/pull/60061/](https://ci.nodejs.org/job/node-test-pull-request/69593/), [https://github.com/nodejs/node/pull/60160/](https://ci.nodejs.org/job/node-test-pull-request/69617/), [https://github.com/nodejs/node/pull/59853/](https://ci.nodejs.org/job/node-test-pull-request/69618/)) |
| Appeared | [vm-dm937](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67230/console), [vm-x4kfi](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67229/console), [vm-2on5c](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67201/console), [vm-2zf9u](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67176/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69573/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69618/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67230/console">Example</a></summary>

```
not ok 4820 wpt/test-hr-time
  ---
  duration_ms: 2504.46200
  severity: fail
  exitcode: 1
  stack: |-
    [SKIPPED] idlharness-shadowrealm.window.js: ShadowRealm support is not enabled
    [SKIPPED] window-worker-timeOrigin.window.js: depends on URL.createObjectURL(blob)
    [PASS] self.performance.now() is a function that returns a number
    [PASS] self.performance.now() returns a positive number
    [PASS] self.performance.now() difference is not negative
    [PASS] Performance interface extends EventTarget.
    [PASS] self.performance.now() returns a positive number
    [PASS] self.performance.now() difference is not negative
    [PASS] idl_test validation
    [PASS] Partial interface mixin WindowOrWorkerGlobalScope: original interface mixin defined
    [PASS] Partial interface mixin WindowOrWorkerGlobalScope: member names are unique
    [PASS] Partial interface Window: member names are unique
    [PASS] Window includes GlobalEventHandlers: member names are unique
    [PASS] Window includes WindowEventH...
```
</details>

-------

| Reason | <code>parallel/test-runner-run</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/59952/](https://ci.nodejs.org/job/node-test-pull-request/69540/), [https://github.com/nodejs/node/pull/60060/](https://ci.nodejs.org/job/node-test-pull-request/69545/), [https://github.com/nodejs/node/pull/60142/](https://ci.nodejs.org/job/node-test-pull-request/69594/)) |
| Appeared | [vm-1z6qj](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67202/console), [test-azure_msft-win11_vs2022-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-COMPILED_BY-vs2019/37085/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69540/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69594/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67202/console">Example</a></summary>

```
not ok 2758 parallel/test-runner-run
  ---
  duration_ms: 5776.81700
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'should support timeout'
    Location: test/parallel/test-runner-run.mjs:89:3
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    + actual - expected
    
    + 'uncaughtException'
    - 'testTimeoutFailure'
    
        at TestsStream.<anonymous> (file:///Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/test/parallel/test-runner-run.mjs:94:14)
        at TestsStream.<anonymous> (/Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/test/common/index.js:475:15)
        at TestsStream.emit (node:events:508:28)
        at [kEmitMessage] (node:internal/test_runner/tests_stream:153:10)
        at TestsStream.fail (node:internal/test_runner/tests_stream:38:23)
        at FileTest.report (node:internal/test_runner/test:1378:21)
        at FileTest.report (node:internal/test_runner/runner:290:13)
        at FileTest.finalize (node:...
```
</details>

-------

| Reason | <code>parallel/test-fs-watch-recursive-delete</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60142/](https://ci.nodejs.org/job/node-test-pull-request/69594/), [https://github.com/nodejs/node/pull/60144/](https://ci.nodejs.org/job/node-test-pull-request/69595/)) |
| Appeared | [test-digitalocean-fedora41-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora-last-latest-x64/66896/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69594/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69595/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora-last-latest-x64/66896/console">Example</a></summary>

```
not ok 1493 parallel/test-fs-watch-recursive-delete
  ---
  duration_ms: 707.52200
  severity: fail
  exitcode: 1
  stack: |-
    node:events:486
          throw er; // Unhandled 'error' event
          ^
    
    Error: ENOENT: no such file or directory, scandir '/home/iojs/node-tmp/.tmp.1492/parent/child'
        at readdirSync (node:fs:1545:26)
        at #watchFolder (node:internal/fs/recursive_watch:111:21)
        at FSWatcher.<anonymous> (node:internal/fs/recursive_watch:191:26)
        at FSWatcher.emit (node:events:508:28)
        at FSWatcher._handle.onchange (node:internal/fs/watchers:222:12)
    Emitted 'error' event on FSWatcher instance at:
        at #watchFolder (node:internal/fs/recursive_watch:143:12)
        at FSWatcher.<anonymous> (node:internal/fs/recursive_watch:191:26)
        at FSWatcher.emit (node:events:508:28)
        at FSWatcher._handle.onchange (node:internal/fs/watchers:222:12) {
      errno: -2,
      code: 'ENOENT',
      syscall: 'scandir',
      path: '/home/iojs/node-tmp/...
```
</details>

-------

| Reason | <code>parallel/test-quic-test-client</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59952/](https://ci.nodejs.org/job/node-test-pull-request/69560/), [https://github.com/nodejs/node/pull/60168/](https://ci.nodejs.org/job/node-test-pull-request/69628/)) |
| Appeared | [vm-nvuji](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67240/console), [vm-m34hc](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67161/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69560/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69628/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67240/console">Example</a></summary>

```
not ok 2571 parallel/test-quic-test-client
  ---
  duration_ms: 1098.45100
  severity: fail
  exitcode: 1
  stack: |-
    /Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/out/Release/ngtcp2_test_client
    node:internal/modules/run_main:107
        triggerUncaughtException(
        ^
    
    AssertionError [ERR_ASSERTION]: Missing expected rejection.
        at process.processTicksAndRejections (node:internal/process/task_queues:103:5)
        at async file:///Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/test/parallel/test-quic-test-client.mjs:31:1 {
      generatedMessage: false,
      code: 'ERR_ASSERTION',
      actual: undefined,
      expected: { message: /Process exited with code 1 and signal null/ },
      operator: 'rejects',
      diff: 'simple'
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-worker-nearheaplimit-deadlock</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60060/](https://ci.nodejs.org/job/node-test-pull-request/69539/), [https://github.com/nodejs/node/pull/59968/](https://ci.nodejs.org/job/node-test-pull-request/69565/)) |
| Appeared | [test-ibm-rhel8-s390x-4](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/51843/console), [test-osuosl-rhel8-ppc64_le-2](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel8-ppc64le/61023/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69539/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69565/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/51843/console">Example</a></summary>

```
not ok 3810 parallel/test-worker-nearheaplimit-deadlock
  ---
  duration_ms: 523.05900
  severity: crashed
  exitcode: -6
  stack: |-
    
    <--- Last few GCs --->
    
    [780525:0x3ff70001000]       12 ms: Mark-Compact 1.4 (3.5) -> 1.4 (3.5) MB, pooled: 0.0 MB, 1.06 / 0.00 ms (average mu = 0.480, current mu = 0.171) background allocation failure; GC in old space requested
    [780525:0x3ff70001000]       13 ms: Mark-Compact 1.4 (3.5) -> 1.4 (3.5) MB, pooled: 0.0 MB, 0.78 / 0.00 ms (average mu = 0.393, current mu = 0.217) background allocation failure; GC in old space requested
    
    FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
    ----- Native stack trace -----
    
     1: 0x1ed3260 node::OOMErrorHandler(char const*, v8::OOMDetails const&) [out/Release/node]
     2: 0x235d6a4 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [out/Release/node]
     3: 0x273701e v8::internal::HeapAllocator::AllocateRawWithRetryOr...
```
</details>

-------

| Reason | <code>parallel/test-zlib-brotli-16GB</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60153/](https://ci.nodejs.org/job/node-test-pull-request/69606/), [https://github.com/nodejs/node/pull/60148/](https://ci.nodejs.org/job/node-test-pull-request/69615/)) |
| Appeared | [vm-ebad9](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67227/console), [vm-532du](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67215/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69606/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69615/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67227/console">Example</a></summary>

```
not ok 3857 parallel/test-zlib-brotli-16GB
  ---
  duration_ms: 1422.15600
  severity: fail
  exitcode: 1
  stack: |-
    node:assert:149
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    
    0 !== 4
    
        at Timeout.<anonymous> (/Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/test/parallel/test-zlib-brotli-16GB.js:22:3)
        at Timeout._onTimeout (/Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/test/common/index.js:475:15)
        at listOnTimeout (node:internal/timers:605:17)
        at process.processTimers (node:internal/timers:541:7) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: 0,
      expected: 4,
      operator: 'strictEqual',
      diff: 'simple'
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

