Failures in [node-test-pull-request/69815](https://ci.nodejs.org/job/node-test-pull-request/69815/) to [node-test-pull-request/69912](https://ci.nodejs.org/job/node-test-pull-request/69912/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2025-10-28.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2025-10-28 00:10 | 4       | 22      | 21       | 4       | 49      | 23.91%     |


### Jenkins Failure

| Reason | <code>Cannot run program "/bin/sh" (in directory "/home/iojs/build/workspace/node"): error=0, Failed to exec spawn helper: pid: 938203, exit value: 1</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/60370/](https://ci.nodejs.org/job/node-test-pull-request/69901/), [https://github.com/nodejs/node/pull/59982/](https://ci.nodejs.org/job/node-test-pull-request/69903/), [https://github.com/nodejs/node/pull/60437/](https://ci.nodejs.org/job/node-test-pull-request/69906/)) |
| Appeared | [test-rackspace-debian11-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian11-x64/67126/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69901/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69906/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian11-x64/67126/console">Example</a></summary>

```
java.io.IOException: Cannot run program "/bin/sh" (in directory "/home/iojs/build/workspace/node"): error=0, Failed to exec spawn helper: pid: 938203, exit value: 1
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at Jenkins v2.528.1//hudson.Proc$LocalProc.<init>(Proc.java:252)
	at Jenkins v2.528.1//hudson.Proc$LocalProc.<init>(Proc.java:221)
	at Jenkins v2.528.1//hudson.Launcher$LocalLauncher.launch(Launcher.java:995)
```
</details>

-------

| Reason | <code>Backing channel 'JNLP4-connect connection from ... is disconnected.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60330/](https://ci.nodejs.org/job/node-test-pull-request/69842/), [https://github.com/nodejs/node/pull/60331/](https://ci.nodejs.org/job/node-test-pull-request/69843/)) |
| Appeared | [test-digitalocean-ubuntu2404-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=ubuntu2404-x64/67067/console), [test-digitalocean-ubuntu2404-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=ubuntu2404-x64/67066/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69842/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69843/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=ubuntu2404-x64/67067/console">Example</a></summary>

```
java.io.IOException: Backing channel 'JNLP4-connect connection from 167.99.124.188/167.99.124.188:48116' is disconnected.
	at hudson.remoting.RemoteInvocationHandler.channelOrFail(RemoteInvocationHandler.java:227)
	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:306)
	at jdk.proxy2/jdk.proxy2.$Proxy105.isAlive(Unknown Source)
	at hudson.Launcher$RemoteLauncher$ProcImpl.isAlive(Launcher.java:1227)
	at hudson.Launcher$RemoteLauncher$ProcImpl.join(Launcher.java:1219)
```
</details>

-------


### Build Failure

| Reason | <code>ERROR: Step ‘Publish JUnit test result report’ failed: no workspace for ...</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 15 ([https://github.com/nodejs/node/pull/60274/](https://ci.nodejs.org/job/node-test-pull-request/69818/), [https://github.com/nodejs/node/pull/60278/](https://ci.nodejs.org/job/node-test-pull-request/69823/), [https://github.com/nodejs/node/pull/59734/](https://ci.nodejs.org/job/node-test-pull-request/69825/), [https://github.com/nodejs/node/pull/60111/](https://ci.nodejs.org/job/node-test-pull-request/69831/), [https://github.com/nodejs/node/pull/60139/](https://ci.nodejs.org/job/node-test-pull-request/69832/), [https://github.com/nodejs/node/pull/59873/](https://ci.nodejs.org/job/node-test-pull-request/69835/), [https://github.com/nodejs/node/pull/60248/](https://ci.nodejs.org/job/node-test-pull-request/69841/), [https://github.com/nodejs/node/pull/60330/](https://ci.nodejs.org/job/node-test-pull-request/69842/), [https://github.com/nodejs/node/pull/60331/](https://ci.nodejs.org/job/node-test-pull-request/69843/), [https://github.com/nodejs/node/pull/60367/](https://ci.nodejs.org/job/node-test-pull-request/69856/), [https://github.com/nodejs/node/pull/60413/](https://ci.nodejs.org/job/node-test-pull-request/69882/), [https://github.com/nodejs/node/pull/60390/](https://ci.nodejs.org/job/node-test-pull-request/69883/), [https://github.com/nodejs/node/pull/60190/](https://ci.nodejs.org/job/node-test-pull-request/69888/), [https://github.com/nodejs/node/pull/60391/](https://ci.nodejs.org/job/node-test-pull-request/69889/), [https://github.com/nodejs/node/pull/60399/](https://ci.nodejs.org/job/node-test-pull-request/69912/)) |
| Appeared | [vm-k5d2b](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx15-arm64/66902/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69818/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69912/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx15-arm64/66902/console">Example</a></summary>

```
ERROR: Step ‘Publish JUnit test result report’ failed: no workspace for node-test-commit-osx/nodes=osx15-arm64 #66902
Collecting metadata...
Metadata collection done.
[Checks API] No suitable checks publisher found.
Notifying upstream projects of job completion
Finished: FAILURE
```
</details>

-------

| Reason | <code>fatal: No rebase in progress?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60331/](https://ci.nodejs.org/job/node-test-pull-request/69843/), [https://github.com/nodejs/node/pull/60281/](https://ci.nodejs.org/job/node-test-pull-request/69847/)) |
| Appeared | [test-digitalocean-ubuntu2404_sharedlibs_container-x64-6](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_shared_x64/53256/console), [test-digitalocean-ubuntu2404_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_shared_x64/53252/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69843/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69847/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_shared_x64/53256/console">Example</a></summary>

```
fatal: No rebase in progress?
```
</details>

-------


### JSTest Failure

| Reason | <code>sequential/test-worker-prof</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/60274/](https://ci.nodejs.org/job/node-test-pull-request/69818/), [https://github.com/nodejs/node/pull/60364/](https://ci.nodejs.org/job/node-test-pull-request/69858/), [https://github.com/nodejs/node/pull/60390/](https://ci.nodejs.org/job/node-test-pull-request/69879/), [https://github.com/nodejs/node/pull/60391/](https://ci.nodejs.org/job/node-test-pull-request/69887/), [https://github.com/nodejs/node/pull/60419/](https://ci.nodejs.org/job/node-test-pull-request/69890/), [https://github.com/nodejs/node/pull/60434/](https://ci.nodejs.org/job/node-test-pull-request/69905/)) |
| Appeared | [test-azure_msft-win10_vs2019-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win10-COMPILED_BY-vs2022_clang/37428/console), [test-azure_msft-win10_vs2019-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2022_clang/37414/console), [vm-qljhz](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67545/console), [test-azure_msft-win11_vs2022-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2022_clang/37402/console), [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/52062/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69818/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69905/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win10-COMPILED_BY-vs2022_clang/37428/console">Example</a></summary>

```
not ok 1163 sequential/test-worker-prof
  ---
  duration_ms: 2363.61300
  severity: fail
  exitcode: 1
  stack: |-
    files found in working directory before worker starts [ 'isolate-0000021F51A6B000-8656-v8.log' ]
    parent prof file: isolate-0000021F51A6B000-8656-v8.log
    parent posted 46066 messages
    files found in working directory before worker exits [
      'isolate-0000021F51A6B000-8656-v8.log',
      'isolate-0000021F6AF77000-8656-v8.log'
    ]
    worker prof file: isolate-0000021F6AF77000-8656-v8.log
    
    worker ticks 43
    parent ticks 10
    node:internal/assert/utils:146
      throw error;
      ^
    
    AssertionError [ERR_ASSERTION]: parent ticks <= 10:
    tick,0x7ffad57ae394,125255,0,0x0,0,0x7ff6218ad780,0x21f00043772,0x2da61105622,0x2da61107800,0x2da61106b61,0x1ebc5881390,0x2da6110324b,0x2da6110deb7,0xb007047520
    tick,0x7ff6219373f5,141101,0,0x0,2,0x2da61108113,0x2da61108307,0x2da61108cea,0x2da6110781f,0x2da61106b61,0x1ebc5881390,0x2da6110324b,0x2da61107992,0x1ebc58b07d0,0xb...
```
</details>

-------

| Reason | <code>parallel/test-runner-output</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/60274/](https://ci.nodejs.org/job/node-test-pull-request/69818/), [https://github.com/nodejs/node/pull/59873/](https://ci.nodejs.org/job/node-test-pull-request/69835/), [https://github.com/nodejs/node/pull/60334/](https://ci.nodejs.org/job/node-test-pull-request/69838/), [https://github.com/nodejs/node/pull/60190/](https://ci.nodejs.org/job/node-test-pull-request/69888/), [https://github.com/nodejs/node/pull/60391/](https://ci.nodejs.org/job/node-test-pull-request/69889/)) |
| Appeared | [vm-rgwwn](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67543/console), [test-ibm-rhel9-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel9-x64/67060/console), [vm-zn9if](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67483/console), [undefined](https://ci.nodejs.org/job/node-test-commit-custom-suites-freestyle/44458/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69818/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69889/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67543/console">Example</a></summary>

```
not ok 3140 parallel/test-runner-output
  ---
  duration_ms: 120142.32600
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    TAP version 13
    # Subtest: test runner output
        # Subtest: test-runner/output/abort.js
        ok 1 - test-runner/output/abort.js
          ---
          duration_ms: 2592.095926
          ...

```
</details>

-------

| Reason | <code>parallel/test-watch-mode-kill-signal-override</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/60139/](https://ci.nodejs.org/job/node-test-pull-request/69832/), [https://github.com/nodejs/node/pull/60318/](https://ci.nodejs.org/job/node-test-pull-request/69860/), [https://github.com/nodejs/node/pull/60372/](https://ci.nodejs.org/job/node-test-pull-request/69871/), [https://github.com/nodejs/node/pull/60190/](https://ci.nodejs.org/job/node-test-pull-request/69888/), [https://github.com/nodejs/node/pull/60391/](https://ci.nodejs.org/job/node-test-pull-request/69889/)) |
| Appeared | [vm-jgrbo](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67547/console), [vm-yinh4](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67546/console), [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/52074/console), [test-azure-ubuntu2204_container-arm64-5](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/60808/console), [vm-usrrc](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67479/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69832/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69889/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67547/console">Example</a></summary>

```
not ok 4425 parallel/test-watch-mode-kill-signal-override
  ---
  duration_ms: 120094.59500
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-http2-close-while-writing</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/60278/](https://ci.nodejs.org/job/node-test-pull-request/69823/), [https://github.com/nodejs/node/pull/60313/](https://ci.nodejs.org/job/node-test-pull-request/69848/), [https://github.com/nodejs/node/pull/60390/](https://ci.nodejs.org/job/node-test-pull-request/69883/)) |
| Appeared | [vm-wfocy](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67540/console), [test-osuosl-rhel8-ppc64_le-2](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel8-ppc64le/61216/console), [vm-o2tby](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67468/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69823/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69883/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67540/console">Example</a></summary>

```
not ok 2310 parallel/test-http2-close-while-writing
  ---
  duration_ms: 120092.64800
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-quic-test-client</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/60111/](https://ci.nodejs.org/job/node-test-pull-request/69831/), [https://github.com/nodejs/node/pull/60331/](https://ci.nodejs.org/job/node-test-pull-request/69843/), [https://github.com/nodejs/node/pull/60391/](https://ci.nodejs.org/job/node-test-pull-request/69880/)) |
| Appeared | [vm-z2sho](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67534/console), [vm-q9xx6](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67494/console), [vm-5d9v3](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67478/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69831/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69880/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67534/console">Example</a></summary>

```
not ok 2578 parallel/test-quic-test-client
  ---
  duration_ms: 1443.27800
  severity: fail
  exitcode: 1
  stack: |-
    /Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/out/Release/ngtcp2_test_client
    node:internal/modules/run_main:107
        triggerUncaughtException(
        ^
    
    AssertionError [ERR_ASSERTION]: Missing expected rejection.
        at process.processTicksAndRejections (node:internal/process/task_queues:103:5)
        at async file:///Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/test/parallel/test-quic-test-client.mjs:36:1 {
      generatedMessage: false,
      code: 'ERR_ASSERTION',
      actual: undefined,
      expected: { message: /Process exited with code 1 and signal null/ },
      operator: 'rejects',
      diff: 'simple'
    }
    
    Node.js v26.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-runner-watch-mode</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/60111/](https://ci.nodejs.org/job/node-test-pull-request/69831/), [https://github.com/nodejs/node/pull/60139/](https://ci.nodejs.org/job/node-test-pull-request/69832/), [https://github.com/nodejs/node/pull/59873/](https://ci.nodejs.org/job/node-test-pull-request/69835/)) |
| Appeared | [vm-gthqd](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67476/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69831/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69835/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67476/console">Example</a></summary>

```
not ok 2512 parallel/test-runner-watch-mode
  ---
  duration_ms: 12314.16600
  severity: fail
  exitcode: 1
  stack: |-
    TAP version 13
    # Subtest: test runner watch mode
        # Subtest: should run tests repeatedly
        ok 1 - should run tests repeatedly
          ---
          duration_ms: 2034.797083
          ...

```
</details>

-------

| Reason | <code>sequential/test-perf-hooks</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/60248/](https://ci.nodejs.org/job/node-test-pull-request/69841/), [https://github.com/nodejs/node/pull/60330/](https://ci.nodejs.org/job/node-test-pull-request/69842/), [https://github.com/nodejs/node/pull/60331/](https://ci.nodejs.org/job/node-test-pull-request/69843/)) |
| Appeared | [vm-k7hpr](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67492/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69841/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69843/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67492/console">Example</a></summary>

```
not ok 4747 sequential/test-perf-hooks
  ---
  duration_ms: 895.86800
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/assert/utils:77
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: Date.now() - performance.timeOrigin (491.593017578125) - process.uptime() * 1000 (371.23216399999995) = 120.36085357812505 >= +- 50
        at Object.<anonymous> (/Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/sequential/test-perf-hooks.js:36:3)
        at Module._compile (node:internal/modules/cjs/loader:1760:14)
        at Object..js (node:internal/modules/cjs/loader:1893:10)
        at Module.load (node:internal/modules/cjs/loader:1480:32)
        at Module._load (node:internal/modules/cjs/loader:1299:12)
        at TracingChannel.traceSync (node:diagnostics_channel:328:14)
        at wrapModuleLoad (node:internal/modules/cjs/loader:244:24)
        at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
        at node:internal/main/run_main_...
```
</details>

-------

| Reason | <code>parallel/test-net-connect-abort-controller</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60374/](https://ci.nodejs.org/job/node-test-pull-request/69862/), [https://github.com/nodejs/node/pull/60190/](https://ci.nodejs.org/job/node-test-pull-request/69888/)) |
| Appeared | [test-mnx-smartos23-x64-6](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos23-x64/62945/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69862/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69888/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos23-x64/62945/console">Example</a></summary>

```
not ok 3536 parallel/test-net-connect-abort-controller
  ---
  duration_ms: 300057.61500
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-watch-mode-kill-signal-default</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59734/](https://ci.nodejs.org/job/node-test-pull-request/69825/), [https://github.com/nodejs/node/pull/60330/](https://ci.nodejs.org/job/node-test-pull-request/69842/)) |
| Appeared | [vm-2xshg](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67493/console), [vm-v9dgt](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67470/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69825/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69842/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67493/console">Example</a></summary>

```
not ok 4419 parallel/test-watch-mode-kill-signal-default
  ---
  duration_ms: 120032.20800
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>pummel/test-timers</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60274/](https://ci.nodejs.org/job/node-test-pull-request/69818/), [https://github.com/nodejs/node/pull/60387/](https://ci.nodejs.org/job/node-test-pull-request/69896/)) |
| Appeared | [test-osuosl-ubuntu2204_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/60846/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69818/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69896/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/60846/console">Example</a></summary>

```
not ok 4518 pummel/test-timers
  ---
  duration_ms: 3814.54100
  severity: fail
  exitcode: 1
  stack: |-
    diff: 1004
    diff: 1003
    diff: 3609
    node:internal/assert/utils:146
      throw error;
      ^
    
    AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
    
      assert.ok(Math.abs(diff - t) < WINDOW * interval_count)
    
        at Timeout.<anonymous> (/home/iojs/build/workspace/node-test-commit-arm/test/pummel/test-timers.js:64:12)
        at Timeout._onTimeout (/home/iojs/build/workspace/node-test-commit-arm/test/common/index.js:476:15)
        at listOnTimeout (node:internal/timers:605:17)
        at process.processTimers (node:internal/timers:541:7) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: '==',
      diff: 'simple'
    }
    
    Node.js v26.0.0-pre
  ...

```
</details>

-------

