Failures in [node-test-pull-request/69856](https://ci.nodejs.org/job/node-test-pull-request/69856/) to [node-test-pull-request/69954](https://ci.nodejs.org/job/node-test-pull-request/69954/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2025-10-30.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2025-10-30 00:11 | 0       | 19      | 19       | 2       | 60      | 19.39%     |


### Jenkins Failure

| Reason | <code>Cannot run program "/bin/sh" (in directory "/home/iojs/build/workspace/node"): error=0, Failed to exec spawn helper: pid: 938203, exit value: 1</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/60370/](https://ci.nodejs.org/job/node-test-pull-request/69901/), [https://github.com/nodejs/node/pull/59982/](https://ci.nodejs.org/job/node-test-pull-request/69903/), [https://github.com/nodejs/node/pull/60437/](https://ci.nodejs.org/job/node-test-pull-request/69906/), [https://github.com/nodejs/node/pull/60422/](https://ci.nodejs.org/job/node-test-pull-request/69913/), [https://github.com/nodejs/node/pull/60388/](https://ci.nodejs.org/job/node-test-pull-request/69919/)) |
| Appeared | [test-rackspace-debian11-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian11-x64/67126/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69901/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69919/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian11-x64/67126/console">Example</a></summary>

```
java.io.IOException: Cannot run program "/bin/sh" (in directory "/home/iojs/build/workspace/node"): error=0, Failed to exec spawn helper: pid: 938203, exit value: 1
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at Jenkins v2.528.1//hudson.Proc$LocalProc.<init>(Proc.java:252)
	at Jenkins v2.528.1//hudson.Proc$LocalProc.<init>(Proc.java:221)
	at Jenkins v2.528.1//hudson.Launcher$LocalLauncher.launch(Launcher.java:995)
```
</details>

-------

| Reason | <code>Cannot run program "/bin/sh" (in directory "/home/iojs/build/workspace/node"): error=0, Failed to exec spawn helper: pid: 957237, exit value: 1</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/60422/](https://ci.nodejs.org/job/node-test-pull-request/69932/), [https://github.com/nodejs/node/pull/59982/](https://ci.nodejs.org/job/node-test-pull-request/69933/), [https://github.com/nodejs/node/pull/60443/](https://ci.nodejs.org/job/node-test-pull-request/69935/), [https://github.com/nodejs/node/pull/60464/](https://ci.nodejs.org/job/node-test-pull-request/69939/)) |
| Appeared | [test-rackspace-debian11-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian11-x64/67149/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69932/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69939/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian11-x64/67149/console">Example</a></summary>

```
java.io.IOException: Cannot run program "/bin/sh" (in directory "/home/iojs/build/workspace/node"): error=0, Failed to exec spawn helper: pid: 957237, exit value: 1
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at Jenkins v2.528.1//hudson.Proc$LocalProc.<init>(Proc.java:252)
	at Jenkins v2.528.1//hudson.Proc$LocalProc.<init>(Proc.java:221)
	at Jenkins v2.528.1//hudson.Launcher$LocalLauncher.launch(Launcher.java:995)
```
</details>

-------


### Build Failure

| Reason | <code>ERROR: Step ‘Publish JUnit test result report’ failed: no workspace for ...</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 10 ([https://github.com/nodejs/node/pull/60367/](https://ci.nodejs.org/job/node-test-pull-request/69856/), [https://github.com/nodejs/node/pull/60390/](https://ci.nodejs.org/job/node-test-pull-request/69883/), [https://github.com/nodejs/node/pull/60190/](https://ci.nodejs.org/job/node-test-pull-request/69888/), [https://github.com/nodejs/node/pull/60391/](https://ci.nodejs.org/job/node-test-pull-request/69889/), [https://github.com/nodejs/node/pull/60413/](https://ci.nodejs.org/job/node-test-pull-request/69911/), [https://github.com/nodejs/node/pull/60399/](https://ci.nodejs.org/job/node-test-pull-request/69912/), [https://github.com/nodejs/node/pull/60447/](https://ci.nodejs.org/job/node-test-pull-request/69920/), [https://github.com/nodejs/node/pull/60443/](https://ci.nodejs.org/job/node-test-pull-request/69923/), [https://github.com/nodejs/node/pull/60248/](https://ci.nodejs.org/job/node-test-pull-request/69927/), [https://github.com/nodejs/node/pull/60480/](https://ci.nodejs.org/job/node-test-pull-request/69945/)) |
| Appeared | [vm-k5d2b](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx15-arm64/66902/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69856/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69945/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx15-arm64/66902/console">Example</a></summary>

```
ERROR: Step ‘Publish JUnit test result report’ failed: no workspace for node-test-commit-osx/nodes=osx15-arm64 #66902
Collecting metadata...
Metadata collection done.
[Checks API] No suitable checks publisher found.
Notifying upstream projects of job completion
Finished: FAILURE
```
</details>

-------


### JSTest Failure

| Reason | <code>sequential/test-worker-prof</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 9 ([https://github.com/nodejs/node/pull/60364/](https://ci.nodejs.org/job/node-test-pull-request/69858/), [https://github.com/nodejs/node/pull/60390/](https://ci.nodejs.org/job/node-test-pull-request/69879/), [https://github.com/nodejs/node/pull/60391/](https://ci.nodejs.org/job/node-test-pull-request/69887/), [https://github.com/nodejs/node/pull/60419/](https://ci.nodejs.org/job/node-test-pull-request/69890/), [https://github.com/nodejs/node/pull/60434/](https://ci.nodejs.org/job/node-test-pull-request/69905/), [https://github.com/nodejs/node/pull/60422/](https://ci.nodejs.org/job/node-test-pull-request/69913/), [https://github.com/nodejs/node/pull/60388/](https://ci.nodejs.org/job/node-test-pull-request/69919/), [https://github.com/nodejs/node/pull/60387/](https://ci.nodejs.org/job/node-test-pull-request/69938/), [https://github.com/nodejs/node/pull/60479/](https://ci.nodejs.org/job/node-test-pull-request/69951/)) |
| Appeared | [test-azure_msft-win10_vs2019-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win10-COMPILED_BY-vs2022_clang/37460/console), [test-azure_msft-win10_vs2019-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win10-COMPILED_BY-vs2022_clang/37451/console), [test-azure_msft-win10_vs2019-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2022_clang/37433/console), [vm-qljhz](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67545/console), [test-azure_msft-win11_vs2022-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2022_clang/37402/console), [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/52062/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69858/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69951/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win10-COMPILED_BY-vs2022_clang/37460/console">Example</a></summary>

```
not ok 1167 sequential/test-worker-prof
  ---
  duration_ms: 2501.45500
  severity: fail
  exitcode: 1
  stack: |-
    files found in working directory before worker starts [ 'isolate-000002CF0EFDE000-5360-v8.log' ]
    parent prof file: isolate-000002CF0EFDE000-5360-v8.log
    parent posted 35670 messages
    files found in working directory before worker exits [
      'isolate-000002CF0EFDE000-5360-v8.log',
      'isolate-000002CF284F8000-5360-v8.log'
    ]
    worker prof file: isolate-000002CF284F8000-5360-v8.log
    
    worker ticks 10
    parent ticks 20
    node:internal/assert/utils:146
      throw error;
      ^
    
    AssertionError [ERR_ASSERTION]: worker ticks <= 10:
    tick,0x7ff646b470ab,42863,0,0x0,0,0x7ff6469ed440,0x2cf68fc28d8,0x2124a68a219,0x2124a689927,0x2cf68f55567,0x2124a686654
    tick,0x7ff646f91f78,138867,0,0x0,2,0x2cf4914297e,0x2cf49142607,0x2124a6a73fb,0x2cf49142a4f,0x2cf49142607,0x2124a6930c3
    tick,0x7ff646a7dcdd,186875,0,0x0,2,0x2cf4914297e,0x2cf49142607,0x2124a6b4d5c,0x2124...
```
</details>

-------

| Reason | <code>parallel/test-watch-mode-kill-signal-override</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/60318/](https://ci.nodejs.org/job/node-test-pull-request/69860/), [https://github.com/nodejs/node/pull/60372/](https://ci.nodejs.org/job/node-test-pull-request/69871/), [https://github.com/nodejs/node/pull/60190/](https://ci.nodejs.org/job/node-test-pull-request/69888/), [https://github.com/nodejs/node/pull/60391/](https://ci.nodejs.org/job/node-test-pull-request/69889/), [https://github.com/nodejs/node/pull/60480/](https://ci.nodejs.org/job/node-test-pull-request/69945/), [https://github.com/nodejs/node/pull/60345/](https://ci.nodejs.org/job/node-test-pull-request/69953/)) |
| Appeared | [test-azure-ubuntu2204_container-arm64-5](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/60887/console), [vm-jgrbo](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67547/console), [vm-yinh4](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67546/console), [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/52074/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69860/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69953/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/60887/console">Example</a></summary>

```
not ok 3877 parallel/test-watch-mode-kill-signal-override
  ---
  duration_ms: 2310.08200
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/modules/run_main:107
        triggerUncaughtException(
        ^
    
    AssertionError [ERR_ASSERTION]: The input was expected to not match the regular expression /__SIGTERM received__/. Input:
    
    "Restarting '/home/iojs/node-tmp/.tmp.3857/kill-signal-for-watch.js'\n" +
      '__SIGINT received__\n' +
      '__SIGTERM received__\n'
    
        at file:///home/iojs/build/workspace/node-test-commit-arm/test/parallel/test-watch-mode-kill-signal-override.mjs:46:8
        at process.processTicksAndRejections (node:internal/process/task_queues:103:5) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: "Restarting '/home/iojs/node-tmp/.tmp.3857/kill-signal-for-watch.js'\n" +
        '__SIGINT received__\n' +
        '__SIGTERM received__\n',
      expected: /__SIGTERM received__/,
      operator: 'doesNotMatch',
      diff: 'simple'
   ...
```
</details>

-------

| Reason | <code>addons/stringbytes-external-exceed-max/test-stringbytes-external-exceed-max-by-1-utf8</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/60434/](https://ci.nodejs.org/job/node-test-pull-request/69907/), [https://github.com/nodejs/node/pull/60388/](https://ci.nodejs.org/job/node-test-pull-request/69924/), [https://github.com/nodejs/node/pull/60387/](https://ci.nodejs.org/job/node-test-pull-request/69940/), [https://github.com/nodejs/node/pull/60380/](https://ci.nodejs.org/job/node-test-pull-request/69948/), [https://github.com/nodejs/node/pull/60427/](https://ci.nodejs.org/job/node-test-pull-request/69949/)) |
| Appeared | [test-osuosl-aix72-ppc64_be-4](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59581/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69907/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69949/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59581/console">Example</a></summary>

```
not ok 4623 addons/stringbytes-external-exceed-max/test-stringbytes-external-exceed-max-by-1-utf8
  ---
  duration_ms: 120069.84700
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    1..0 # Skipped: intensive toString tests due to memory confinements
  ...

```
</details>

-------

| Reason | <code>addons/stringbytes-external-exceed-max/test-stringbytes-external-exceed-max</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/60388/](https://ci.nodejs.org/job/node-test-pull-request/69919/), [https://github.com/nodejs/node/pull/60447/](https://ci.nodejs.org/job/node-test-pull-request/69920/), [https://github.com/nodejs/node/pull/60427/](https://ci.nodejs.org/job/node-test-pull-request/69936/), [https://github.com/nodejs/node/pull/60380/](https://ci.nodejs.org/job/node-test-pull-request/69954/)) |
| Appeared | [test-ibm-aix72-ppc64_be-2](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59585/console), [test-osuosl-aix72-ppc64_be-4](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59566/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69919/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69954/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59585/console">Example</a></summary>

```
not ok 4619 addons/stringbytes-external-exceed-max/test-stringbytes-external-exceed-max
  ---
  duration_ms: 120185.83700
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    1..0 # Skipped: intensive toString tests due to memory confinements
  ...

```
</details>

-------

| Reason | <code>es-module/test-esm-wasm</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/60434/](https://ci.nodejs.org/job/node-test-pull-request/69905/), [https://github.com/nodejs/node/pull/60429/](https://ci.nodejs.org/job/node-test-pull-request/69908/), [https://github.com/nodejs/node/pull/60422/](https://ci.nodejs.org/job/node-test-pull-request/69913/), [https://github.com/nodejs/node/pull/60388/](https://ci.nodejs.org/job/node-test-pull-request/69919/)) |
| Appeared | [test-azure_msft-win10_vs2019-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2019/37423/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69905/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69919/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2019/37423/console">Example</a></summary>

```
not ok 58 es-module/test-esm-wasm
  ---
  duration_ms: 1008.00200
  severity: fail
  exitcode: 1
  stack: |-
    TAP version 13
    # Subtest: ESM: WASM modules
        # Subtest: should load exports
        ok 1 - should load exports
          ---
          duration_ms: 251.6482
          ...

```
</details>

-------

| Reason | <code>addons/stringbytes-external-exceed-max/test-stringbytes-external-exceed-max-by-1-binary</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/60434/](https://ci.nodejs.org/job/node-test-pull-request/69907/), [https://github.com/nodejs/node/pull/60351/](https://ci.nodejs.org/job/node-test-pull-request/69922/), [https://github.com/nodejs/node/pull/60387/](https://ci.nodejs.org/job/node-test-pull-request/69942/)) |
| Appeared | [test-osuosl-aix72-ppc64_be-4](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59572/console), [test-ibm-aix72-ppc64_be-2](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59558/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69907/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69942/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59572/console">Example</a></summary>

```
not ok 4620 addons/stringbytes-external-exceed-max/test-stringbytes-external-exceed-max-by-1-binary
  ---
  duration_ms: 120134.19400
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    1..0 # Skipped: intensive toString tests due to memory confinements
  ...

```
</details>

-------

| Reason | <code>addons/stringbytes-external-exceed-max/test-stringbytes-external-exceed-max-by-1-hex</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/60427/](https://ci.nodejs.org/job/node-test-pull-request/69941/), [https://github.com/nodejs/node/pull/60387/](https://ci.nodejs.org/job/node-test-pull-request/69943/), [https://github.com/nodejs/node/pull/60380/](https://ci.nodejs.org/job/node-test-pull-request/69948/)) |
| Appeared | [test-osuosl-aix72-ppc64_be-4](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59580/console), [test-ibm-aix72-ppc64_be-2](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59570/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69941/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69948/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59580/console">Example</a></summary>

```
not ok 4623 addons/stringbytes-external-exceed-max/test-stringbytes-external-exceed-max-by-1-hex
  ---
  duration_ms: 120126.05900
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    1..0 # Skipped: intensive toString tests due to memory confinements
  ...

```
</details>

-------

| Reason | <code>addons/stringbytes-external-exceed-max/test-stringbytes-external-exceed-max-by-2</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/60388/](https://ci.nodejs.org/job/node-test-pull-request/69924/), [https://github.com/nodejs/node/pull/60427/](https://ci.nodejs.org/job/node-test-pull-request/69941/), [https://github.com/nodejs/node/pull/60380/](https://ci.nodejs.org/job/node-test-pull-request/69948/)) |
| Appeared | [test-osuosl-aix72-ppc64_be-4](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59580/console), [test-ibm-aix72-ppc64_be-2](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59570/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69924/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69948/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59580/console">Example</a></summary>

```
not ok 4625 addons/stringbytes-external-exceed-max/test-stringbytes-external-exceed-max-by-2
  ---
  duration_ms: 120140.60800
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    1..0 # Skipped: intensive toString tests due to memory confinements
  ...

```
</details>

-------

| Reason | <code>parallel/test-quic-test-client</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/60391/](https://ci.nodejs.org/job/node-test-pull-request/69880/), [https://github.com/nodejs/node/pull/60447/](https://ci.nodejs.org/job/node-test-pull-request/69920/), [https://github.com/nodejs/node/pull/60480/](https://ci.nodejs.org/job/node-test-pull-request/69945/)) |
| Appeared | [vm-80086](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67600/console), [vm-mu2vx](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67581/console), [vm-z2sho](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67534/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69880/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69945/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67600/console">Example</a></summary>

```
not ok 2577 parallel/test-quic-test-client
  ---
  duration_ms: 1850.61100
  severity: fail
  exitcode: 1
  stack: |-
    /Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/out/Release/ngtcp2_test_client
    node:internal/modules/run_main:107
        triggerUncaughtException(
        ^
    
    AssertionError [ERR_ASSERTION]: Missing expected rejection.
        at process.processTicksAndRejections (node:internal/process/task_queues:103:5)
        at async file:///Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/test/parallel/test-quic-test-client.mjs:36:1 {
      generatedMessage: false,
      code: 'ERR_ASSERTION',
      actual: undefined,
      expected: { message: /Process exited with code 1 and signal null/ },
      operator: 'rejects',
      diff: 'simple'
    }
    
    Node.js v26.0.0-pre
  ...

```
</details>

-------

| Reason | <code>addons/stringbytes-external-exceed-max/test-stringbytes-external-exceed-max-by-1-base64</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60388/](https://ci.nodejs.org/job/node-test-pull-request/69919/), [https://github.com/nodejs/node/pull/60387/](https://ci.nodejs.org/job/node-test-pull-request/69938/)) |
| Appeared | [test-osuosl-aix72-ppc64_be-4](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59567/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69919/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69938/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59567/console">Example</a></summary>

```
not ok 4619 addons/stringbytes-external-exceed-max/test-stringbytes-external-exceed-max-by-1-base64
  ---
  duration_ms: 120090.81900
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    1..0 # Skipped: intensive toString tests due to memory confinements
  ...

```
</details>

-------

| Reason | <code>async-hooks/test-emit-before-on-destroyed</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60385/](https://ci.nodejs.org/job/node-test-pull-request/69885/), [https://github.com/nodejs/node/pull/60427/](https://ci.nodejs.org/job/node-test-pull-request/69947/)) |
| Appeared | [test-osuosl-aix72-ppc64_be-4](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59579/console), [test-ibm-aix72-ppc64_be-2](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59523/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69885/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69947/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59579/console">Example</a></summary>

```
not ok 38 async-hooks/test-emit-before-on-destroyed
  ---
  duration_ms: 486.15900
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/assert/utils:146
      throw error;
      ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    
    null !== 1
    
        at ChildProcess.<anonymous> (/home/iojs/build/workspace/node-test-commit-aix/nodes/aix72-ppc64/test/async-hooks/test-emit-before-on-destroyed.js:56:12)
        at ChildProcess.<anonymous> (/home/iojs/build/workspace/node-test-commit-aix/nodes/aix72-ppc64/test/common/index.js:476:15)
        at ChildProcess.emit (node:events:508:28)
        at maybeClose (node:internal/child_process:1085:16)
        at ChildProcess._handle.onexit (node:internal/child_process:304:5) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: null,
      expected: 1,
      operator: 'strictEqual',
      diff: 'simple'
    }
    
    Node.js v26.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-net-connect-abort-controller</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60374/](https://ci.nodejs.org/job/node-test-pull-request/69862/), [https://github.com/nodejs/node/pull/60190/](https://ci.nodejs.org/job/node-test-pull-request/69888/)) |
| Appeared | [test-mnx-smartos23-x64-6](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos23-x64/62945/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69862/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69888/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos23-x64/62945/console">Example</a></summary>

```
not ok 3536 parallel/test-net-connect-abort-controller
  ---
  duration_ms: 300057.61500
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-perf-hooks-timerify</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60370/](https://ci.nodejs.org/job/node-test-pull-request/69901/), [https://github.com/nodejs/node/pull/60388/](https://ci.nodejs.org/job/node-test-pull-request/69919/)) |
| Appeared | [test-ibm-rhel8-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/67144/console), [test-ibm-rhel8-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/67128/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69901/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69919/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/67144/console">Example</a></summary>

```
not ok 2847 parallel/test-perf-hooks-timerify
  ---
  duration_ms: 200.17400
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/histogram:292
        validateInteger(val, 'val', 1);
        ^
    
    RangeError [ERR_OUT_OF_RANGE]: The value of "val" is out of range. It must be >= 1 && <= 9007199254740991. Received 0
        at RecordableHistogram.record (node:internal/histogram:292:5)
        at processComplete (node:internal/perf/timerify:40:15)
        at timerified m (node:internal/perf/timerify:87:5)
        at /home/iojs/build/workspace/node/test/parallel/test-perf-hooks-timerify.js:107:5
        at runNextTicks (node:internal/process/task_queues:64:5)
        at listOnTimeout (node:internal/timers:567:9)
        at process.processTimers (node:internal/timers:541:7) {
      code: 'ERR_OUT_OF_RANGE'
    }
    
    Node.js v26.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-runner-output</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60190/](https://ci.nodejs.org/job/node-test-pull-request/69888/), [https://github.com/nodejs/node/pull/60391/](https://ci.nodejs.org/job/node-test-pull-request/69889/)) |
| Appeared | [vm-rgwwn](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67543/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69888/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69889/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67543/console">Example</a></summary>

```
not ok 3140 parallel/test-runner-output
  ---
  duration_ms: 120142.32600
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    TAP version 13
    # Subtest: test runner output
        # Subtest: test-runner/output/abort.js
        ok 1 - test-runner/output/abort.js
          ---
          duration_ms: 2592.095926
          ...

```
</details>

-------

| Reason | <code>parallel/test-watch-mode-files_watcher</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60454/](https://ci.nodejs.org/job/node-test-pull-request/69921/), [https://github.com/nodejs/node/pull/60248/](https://ci.nodejs.org/job/node-test-pull-request/69927/)) |
| Appeared | [vm-foi6n](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67589/console), [test-rackspace-win2022_vs2022-x64-6](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2022-COMPILED_BY-vs2022_clang/37440/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69921/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69927/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67589/console">Example</a></summary>

```
not ok 4253 parallel/test-watch-mode-files_watcher
  ---
  duration_ms: 120105.99700
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

