Failures in [node-test-pull-request/69465](https://ci.nodejs.org/job/node-test-pull-request/69465/) to [node-test-pull-request/69563](https://ci.nodejs.org/job/node-test-pull-request/69563/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2025-10-05.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2025-10-05 00:12 | 1       | 4       | 27       | 2       | 66      | 4.12%      |


### Jenkins Failure

| Reason | <code>Unexpected termination of the channel</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 8 ([https://github.com/nodejs/node/pull/60066/](https://ci.nodejs.org/job/node-test-pull-request/69494/), [https://github.com/nodejs/node/pull/60014/](https://ci.nodejs.org/job/node-test-pull-request/69496/), [https://github.com/nodejs/node/pull/60024/](https://ci.nodejs.org/job/node-test-pull-request/69498/), [https://github.com/nodejs/node/pull/60069/](https://ci.nodejs.org/job/node-test-pull-request/69499/), [https://github.com/nodejs/node/pull/60000/](https://ci.nodejs.org/job/node-test-pull-request/69523/), [https://github.com/nodejs/node/pull/59952/](https://ci.nodejs.org/job/node-test-pull-request/69526/), [https://github.com/nodejs/node/pull/60060/](https://ci.nodejs.org/job/node-test-pull-request/69527/), [https://github.com/nodejs/node/pull/60115/](https://ci.nodejs.org/job/node-test-pull-request/69528/)) |
| Appeared | [vm-7unys](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-arm64/67123/console), [vm-16b2l](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-arm64/67086/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69494/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69528/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-arm64/67123/console">Example</a></summary>

```
java.io.IOException: Unexpected termination of the channel
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:80)
Caused: java.io.IOException: Backing channel 'vm-7unys' is disconnected.
	at hudson.remoting.RemoteInvocationHandler.channelOrFail(RemoteInvocationHandler.java:227)
	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:306)
	at jdk.proxy2/jdk.proxy2.$Proxy218.isAlive(Unknown Source)
```
</details>

-------

| Reason | <code>Build timed out (after 30 minutes). Marking the build as failed.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/59805/](https://ci.nodejs.org/job/node-test-pull-request/69517/), [https://github.com/nodejs/node/pull/60040/](https://ci.nodejs.org/job/node-test-pull-request/69533/), [https://github.com/nodejs/node/pull/59952/](https://ci.nodejs.org/job/node-test-pull-request/69540/), [https://github.com/nodejs/node/pull/60060/](https://ci.nodejs.org/job/node-test-pull-request/69545/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2019-arm64/37085/console), [test-azure_msft-win11_vs2022-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-native-suites/nodes=win11-vs2022-COMPILED_BY-vs2022_clang/29936/console), [test-azure_msft-win11_vs2022-arm64-3](https://ci.nodejs.org/job/node-test-binary-windows-native-suites/nodes=win11-vs2022-arm64-COMPILED_BY-vs2022_clang-arm64/29936/console), [test-rackspace-win2022_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-native-suites/nodes=win2022-vs2022-COMPILED_BY-vs2022_clang/29936/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69517/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69545/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2019-arm64/37085/console">Example</a></summary>

```
Build timed out (after 30 minutes). Marking the build as failed.
```
</details>

-------


### Build Failure

| Reason | <code>fatal: detected dubious ownership in repository at 'C:/workspace/node-test-binary-windows-js-suites/build'</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/60103/](https://ci.nodejs.org/job/node-test-pull-request/69514/), [https://github.com/nodejs/node/pull/59805/](https://ci.nodejs.org/job/node-test-pull-request/69517/), [https://github.com/nodejs/node/pull/60040/](https://ci.nodejs.org/job/node-test-pull-request/69533/), [https://github.com/nodejs/node/pull/59952/](https://ci.nodejs.org/job/node-test-pull-request/69540/), [https://github.com/nodejs/node/pull/60060/](https://ci.nodejs.org/job/node-test-pull-request/69545/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-COMPILED_BY-vs2019/37085/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69514/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69545/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-COMPILED_BY-vs2019/37085/console">Example</a></summary>

```
fatal: detected dubious ownership in repository at 'C:/workspace/node-test-binary-windows-js-suites/build'
```
</details>

-------

| Reason | <code>Failed to trigger node-test-commit</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/60066/](https://ci.nodejs.org/job/node-test-pull-request/69493/), [https://github.com/nodejs/node/pull/60060/](https://ci.nodejs.org/job/node-test-pull-request/69543/), [https://github.com/nodejs/node/pull/59952/](https://ci.nodejs.org/job/node-test-pull-request/69544/)) |
| Appeared | [test-mnx-ubuntu2204-x64-1](https://ci.nodejs.org/job/node-test-pull-request/69544/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69493/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69544/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-pull-request/69544/console">Example</a></summary>

```
Failed to trigger node-test-commit
```
</details>

-------

| Reason | <code>ERROR: Step �Publish JUnit test result report� failed: No test report files were found. Configuration error?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59952/](https://ci.nodejs.org/job/node-test-pull-request/69512/), [https://github.com/nodejs/node/pull/59805/](https://ci.nodejs.org/job/node-test-pull-request/69517/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-COMPILED_BY-vs2022_clang/37090/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69512/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69517/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-COMPILED_BY-vs2022_clang/37090/console">Example</a></summary>

```
ERROR: Step �Publish JUnit test result report� failed: No test report files were found. Configuration error?
Collecting metadata...
Metadata collection done.
Notifying upstream projects of job completion
Finished: FAILURE
```
</details>

-------


### JSTest Failure

| Reason | <code>parallel/test-runner-run-watch</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 24 ([https://github.com/nodejs/node/pull/60072/](https://ci.nodejs.org/job/node-test-pull-request/69466/), [https://github.com/nodejs/node/pull/59999/](https://ci.nodejs.org/job/node-test-pull-request/69467/), [https://github.com/nodejs/node/pull/60047/](https://ci.nodejs.org/job/node-test-pull-request/69468/), [https://github.com/nodejs/node/pull/60052/](https://ci.nodejs.org/job/node-test-pull-request/69469/), [https://github.com/nodejs/node/pull/60038/](https://ci.nodejs.org/job/node-test-pull-request/69470/), [https://github.com/nodejs/node/pull/60068/](https://ci.nodejs.org/job/node-test-pull-request/69471/), [https://github.com/nodejs/node/pull/59928/](https://ci.nodejs.org/job/node-test-pull-request/69472/), [https://github.com/nodejs/node/pull/59778/](https://ci.nodejs.org/job/node-test-pull-request/69473/), [https://github.com/nodejs/node/pull/60012/](https://ci.nodejs.org/job/node-test-pull-request/69478/), [https://github.com/nodejs/node/pull/60073/](https://ci.nodejs.org/job/node-test-pull-request/69479/), [https://github.com/nodejs/node/pull/59996/](https://ci.nodejs.org/job/node-test-pull-request/69480/), [https://github.com/nodejs/node/pull/60029/](https://ci.nodejs.org/job/node-test-pull-request/69487/), [https://github.com/nodejs/node/pull/60069/](https://ci.nodejs.org/job/node-test-pull-request/69499/), [https://github.com/nodejs/node/pull/60082/](https://ci.nodejs.org/job/node-test-pull-request/69504/), [https://github.com/nodejs/node/pull/60024/](https://ci.nodejs.org/job/node-test-pull-request/69506/), [https://github.com/nodejs/node/pull/60103/](https://ci.nodejs.org/job/node-test-pull-request/69507/), [https://github.com/nodejs/node/pull/59877/](https://ci.nodejs.org/job/node-test-pull-request/69518/), [https://github.com/nodejs/node/pull/60033/](https://ci.nodejs.org/job/node-test-pull-request/69530/), [https://github.com/nodejs/node/pull/60040/](https://ci.nodejs.org/job/node-test-pull-request/69533/), [https://github.com/nodejs/node/pull/59805/](https://ci.nodejs.org/job/node-test-pull-request/69537/), [https://github.com/nodejs/node/pull/60060/](https://ci.nodejs.org/job/node-test-pull-request/69554/), [https://github.com/nodejs/node/pull/60059/](https://ci.nodejs.org/job/node-test-pull-request/69556/), [https://github.com/nodejs/node/pull/59952/](https://ci.nodejs.org/job/node-test-pull-request/69558/), [https://github.com/nodejs/node/pull/60061/](https://ci.nodejs.org/job/node-test-pull-request/69563/)) |
| Appeared | [vm-3jyui](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67164/console), [vm-qe5tw](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67159/console), [vm-66gbr](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67157/console), [vm-qbevq](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67144/console), [vm-asmhb](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67139/console), [vm-fca2x](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67138/console), [vm-2ri4d](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67136/console), [vm-cl25d](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67132/console), [vm-2qmvu](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67127/console), [vm-i26vj](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67118/console), [vm-8cc4z](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67105/console), [vm-fl5w8](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67103/console), [vm-ectrz](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67091/console), [vm-40ucq](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67090/console), [vm-x0big](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67077/console), [vm-o5844](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67069/console), [vm-mfxmz](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67068/console), [vm-d4j6y](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67062/console), [vm-ums8n](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67061/console), [vm-mf6bp](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67053/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69466/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69563/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67164/console">Example</a></summary>

```
not ok 2818 parallel/test-runner-run-watch
  ---
  duration_ms: 27378.44400
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'should run with different cwd while in watch mode and isolation "none"'
    Location: test/parallel/test-runner-run-watch.mjs:358:5
    AssertionError [ERR_ASSERTION]: function should not have been called at file:///Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/test/parallel/test-runner-run-watch.mjs:373
    called with arguments: [Object: null prototype] {
      name: '<anonymous>',
      nesting: 0,
      testNumber: 1,
      details: [Object: null prototype] {
        duration_ms: 222.772831,
        type: 'test',
        error: [Error: test failed] {
          code: 'ERR_TEST_FAILURE',
          failureType: 'testCodeFailure',
          cause: 'test failed',
          exitCode: null,
          signal: 'SIGTERM'
        }
      },
      line: 1,
      column: 1,
      file: '/Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/<anonymo...
```
</details>

-------

| Reason | <code>client-proxy/test-https-proxy-request-invalid-char-in-url</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 10 ([https://github.com/nodejs/node/pull/60072/](https://ci.nodejs.org/job/node-test-pull-request/69466/), [https://github.com/nodejs/node/pull/60038/](https://ci.nodejs.org/job/node-test-pull-request/69470/), [https://github.com/nodejs/node/pull/60068/](https://ci.nodejs.org/job/node-test-pull-request/69471/), [https://github.com/nodejs/node/pull/60043/](https://ci.nodejs.org/job/node-test-pull-request/69476/), [https://github.com/nodejs/node/pull/60012/](https://ci.nodejs.org/job/node-test-pull-request/69478/), [https://github.com/nodejs/node/pull/59996/](https://ci.nodejs.org/job/node-test-pull-request/69480/), [https://github.com/nodejs/node/pull/60029/](https://ci.nodejs.org/job/node-test-pull-request/69481/), [https://github.com/nodejs/node/pull/60103/](https://ci.nodejs.org/job/node-test-pull-request/69507/), [https://github.com/nodejs/node/pull/59805/](https://ci.nodejs.org/job/node-test-pull-request/69537/), [https://github.com/nodejs/node/pull/60060/](https://ci.nodejs.org/job/node-test-pull-request/69554/)) |
| Appeared | [vm-qe5tw](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67155/console), [vm-2ri4d](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67136/console), [vm-fl5w8](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67103/console), [vm-o5844](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67069/console), [vm-mfxmz](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67066/console), [vm-d4j6y](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67060/console), [vm-ums8n](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67059/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69466/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69554/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67155/console">Example</a></summary>

```
not ok 4371 client-proxy/test-https-proxy-request-invalid-char-in-url
  ---
  duration_ms: 494.69100
  severity: fail
  exitcode: 1
  stack: |-
    [Upstream server] responding to request for '/carriage-return-in-host'
    [Proxy client] Received response from server for 'https://local\rhost:62846/carriage-return-in-host': Response for '/carriage-return-in-host'
    [Proxy client] #1 closed request for: 'https://local\rhost:62846/carriage-return-in-host'
    [Upstream server] responding to request for '/newline-in-host'
    [Upstream server] responding to request for '/crlf-in-host'
    [Proxy client] Received response from server for 'https://local\nhost:62846/newline-in-host': Response for '/newline-in-host'
    [Proxy client] #2 closed request for: 'https://local\nhost:62846/newline-in-host'
    [Proxy client] Received response from server for 'https://local\r\nhost:62846/crlf-in-host': Response for '/crlf-in-host'
    [Proxy client] #3 closed request for: 'https://local\r\nhost:62846/crlf-in-host'
    [Up...
```
</details>

-------

| Reason | <code>parallel/test-without-async-context-frame</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 8 ([https://github.com/nodejs/node/pull/60052/](https://ci.nodejs.org/job/node-test-pull-request/69469/), [https://github.com/nodejs/node/pull/60024/](https://ci.nodejs.org/job/node-test-pull-request/69498/), [https://github.com/nodejs/node/pull/60115/](https://ci.nodejs.org/job/node-test-pull-request/69528/), [https://github.com/nodejs/node/pull/60033/](https://ci.nodejs.org/job/node-test-pull-request/69530/), [https://github.com/nodejs/node/pull/59805/](https://ci.nodejs.org/job/node-test-pull-request/69537/), [https://github.com/nodejs/node/pull/60060/](https://ci.nodejs.org/job/node-test-pull-request/69545/), [https://github.com/nodejs/node/pull/60036/](https://ci.nodejs.org/job/node-test-pull-request/69550/), [https://github.com/nodejs/node/pull/59952/](https://ci.nodejs.org/job/node-test-pull-request/69553/)) |
| Appeared | [vm-66gbr](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67154/console), [vm-qbevq](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67144/console), [vm-ujjv9](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67143/console), [vm-2ri4d](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67136/console), [vm-y9ecw](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67128/console), [vm-2qmvu](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67127/console), [vm-8yw85](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67121/console), [vm-40ucq](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67090/console), [vm-d4j6y](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67058/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69469/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69553/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67154/console">Example</a></summary>

```
not ok 4216 parallel/test-without-async-context-frame
  ---
  duration_ms: 120044.06300
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>sequential/test-single-executable-application</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 8 ([https://github.com/nodejs/node/pull/60072/](https://ci.nodejs.org/job/node-test-pull-request/69466/), [https://github.com/nodejs/node/pull/59999/](https://ci.nodejs.org/job/node-test-pull-request/69467/), [https://github.com/nodejs/node/pull/60047/](https://ci.nodejs.org/job/node-test-pull-request/69468/), [https://github.com/nodejs/node/pull/60052/](https://ci.nodejs.org/job/node-test-pull-request/69469/), [https://github.com/nodejs/node/pull/60038/](https://ci.nodejs.org/job/node-test-pull-request/69470/), [https://github.com/nodejs/node/pull/59928/](https://ci.nodejs.org/job/node-test-pull-request/69472/), [https://github.com/nodejs/node/pull/59778/](https://ci.nodejs.org/job/node-test-pull-request/69473/), [https://github.com/nodejs/node/pull/60073/](https://ci.nodejs.org/job/node-test-pull-request/69475/)) |
| Appeared | [vm-d4j6y](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67064/console), [vm-ums8n](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67061/console), [vm-mf6bp](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67061/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69466/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69475/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67064/console">Example</a></summary>

```
not ok 4763 sequential/test-single-executable-application
  ---
  duration_ms: 14112.72600
  severity: fail
  exitcode: 1
  stack: |-
    Copied /Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/out/Release/node to /Users/admin/node-tmp/.tmp.4762/sea
    Injected /Users/admin/node-tmp/.tmp.4762/sea-prep.blob into /Users/admin/node-tmp/.tmp.4762/sea
    Signed /Users/admin/node-tmp/.tmp.4762/sea
    [process 79192]: --- stderr ---
    dyld[79192]: failed to set up thread local variables for '/Users/admin/node-tmp/.tmp.4762/sea': unsupported thread-local, larger than 4GB
    
    [process 79192]: --- stdout ---
    
    [process 79192]: status = null, signal = SIGABRT
    /Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/test/common/child_process.js:98
        throw error;
        ^
    
    Error: - process terminated with status null, expected 0
    - process terminated with signal SIGABRT, expected null
        at Object.<anonymous> (/Users/admin/build/workspace/node-test-...
```
</details>

-------

| Reason | <code>sequential/test-single-executable-application-asset-keys</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 8 ([https://github.com/nodejs/node/pull/60072/](https://ci.nodejs.org/job/node-test-pull-request/69466/), [https://github.com/nodejs/node/pull/59999/](https://ci.nodejs.org/job/node-test-pull-request/69467/), [https://github.com/nodejs/node/pull/60047/](https://ci.nodejs.org/job/node-test-pull-request/69468/), [https://github.com/nodejs/node/pull/60052/](https://ci.nodejs.org/job/node-test-pull-request/69469/), [https://github.com/nodejs/node/pull/60038/](https://ci.nodejs.org/job/node-test-pull-request/69470/), [https://github.com/nodejs/node/pull/59928/](https://ci.nodejs.org/job/node-test-pull-request/69472/), [https://github.com/nodejs/node/pull/59778/](https://ci.nodejs.org/job/node-test-pull-request/69473/), [https://github.com/nodejs/node/pull/60073/](https://ci.nodejs.org/job/node-test-pull-request/69475/)) |
| Appeared | [vm-d4j6y](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67064/console), [vm-ums8n](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67061/console), [vm-mf6bp](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67061/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69466/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69475/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67064/console">Example</a></summary>

```
not ok 4764 sequential/test-single-executable-application-asset-keys
  ---
  duration_ms: 14197.59900
  severity: fail
  exitcode: 1
  stack: |-
    Copied /Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/out/Release/node to /Users/admin/node-tmp/.tmp.4763/sea
    Injected /Users/admin/node-tmp/.tmp.4763/sea-prep.blob into /Users/admin/node-tmp/.tmp.4763/sea
    Signed /Users/admin/node-tmp/.tmp.4763/sea
    [process 79212]: --- stderr ---
    dyld[79212]: failed to set up thread local variables for '/Users/admin/node-tmp/.tmp.4763/sea': unsupported thread-local, larger than 4GB
    
    [process 79212]: --- stdout ---
    
    [process 79212]: status = null, signal = SIGABRT
    /Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/test/common/child_process.js:98
        throw error;
        ^
    
    Error: - process terminated with status null, expected 0
    - process terminated with signal SIGABRT, expected null
        at Object.<anonymous> (/Users/admin/build/workspace...
```
</details>

-------

| Reason | <code>sequential/test-single-executable-application-asset-keys-empty</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 8 ([https://github.com/nodejs/node/pull/60072/](https://ci.nodejs.org/job/node-test-pull-request/69466/), [https://github.com/nodejs/node/pull/59999/](https://ci.nodejs.org/job/node-test-pull-request/69467/), [https://github.com/nodejs/node/pull/60047/](https://ci.nodejs.org/job/node-test-pull-request/69468/), [https://github.com/nodejs/node/pull/60052/](https://ci.nodejs.org/job/node-test-pull-request/69469/), [https://github.com/nodejs/node/pull/60038/](https://ci.nodejs.org/job/node-test-pull-request/69470/), [https://github.com/nodejs/node/pull/59928/](https://ci.nodejs.org/job/node-test-pull-request/69472/), [https://github.com/nodejs/node/pull/59778/](https://ci.nodejs.org/job/node-test-pull-request/69473/), [https://github.com/nodejs/node/pull/60073/](https://ci.nodejs.org/job/node-test-pull-request/69475/)) |
| Appeared | [vm-d4j6y](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67064/console), [vm-ums8n](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67061/console), [vm-mf6bp](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67061/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69466/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69475/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67064/console">Example</a></summary>

```
not ok 4765 sequential/test-single-executable-application-asset-keys-empty
  ---
  duration_ms: 14238.46900
  severity: fail
  exitcode: 1
  stack: |-
    Copied /Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/out/Release/node to /Users/admin/node-tmp/.tmp.4764/sea
    Injected /Users/admin/node-tmp/.tmp.4764/sea-prep.blob into /Users/admin/node-tmp/.tmp.4764/sea
    Signed /Users/admin/node-tmp/.tmp.4764/sea
    [process 79231]: --- stderr ---
    dyld[79231]: failed to set up thread local variables for '/Users/admin/node-tmp/.tmp.4764/sea': unsupported thread-local, larger than 4GB
    
    [process 79231]: --- stdout ---
    
    [process 79231]: status = null, signal = SIGABRT
    /Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/test/common/child_process.js:98
        throw error;
        ^
    
    Error: - process terminated with status null, expected 0
    - process terminated with signal SIGABRT, expected null
        at Object.<anonymous> (/Users/admin/build/wor...
```
</details>

-------

| Reason | <code>sequential/test-single-executable-application-assets</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 8 ([https://github.com/nodejs/node/pull/60072/](https://ci.nodejs.org/job/node-test-pull-request/69466/), [https://github.com/nodejs/node/pull/59999/](https://ci.nodejs.org/job/node-test-pull-request/69467/), [https://github.com/nodejs/node/pull/60047/](https://ci.nodejs.org/job/node-test-pull-request/69468/), [https://github.com/nodejs/node/pull/60052/](https://ci.nodejs.org/job/node-test-pull-request/69469/), [https://github.com/nodejs/node/pull/60038/](https://ci.nodejs.org/job/node-test-pull-request/69470/), [https://github.com/nodejs/node/pull/59928/](https://ci.nodejs.org/job/node-test-pull-request/69472/), [https://github.com/nodejs/node/pull/59778/](https://ci.nodejs.org/job/node-test-pull-request/69473/), [https://github.com/nodejs/node/pull/60073/](https://ci.nodejs.org/job/node-test-pull-request/69475/)) |
| Appeared | [vm-d4j6y](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67064/console), [vm-ums8n](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67061/console), [vm-mf6bp](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67061/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69466/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69475/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67064/console">Example</a></summary>

```
not ok 4766 sequential/test-single-executable-application-assets
  ---
  duration_ms: 14481.54300
  severity: fail
  exitcode: 1
  stack: |-
    Copied /Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/out/Release/node to /Users/admin/node-tmp/.tmp.4765/sea
    Injected /Users/admin/node-tmp/.tmp.4765/sea-prep.blob into /Users/admin/node-tmp/.tmp.4765/sea
    Signed /Users/admin/node-tmp/.tmp.4765/sea
    [process 79253]: --- stderr ---
    dyld[79253]: failed to set up thread local variables for '/Users/admin/node-tmp/.tmp.4765/sea': unsupported thread-local, larger than 4GB
    
    [process 79253]: --- stdout ---
    
    [process 79253]: status = null, signal = SIGABRT
    /Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/test/common/child_process.js:98
        throw error;
        ^
    
    Error: - process terminated with status null, expected 0
    - process terminated with signal SIGABRT, expected null
        at Object.<anonymous> (/Users/admin/build/workspace/nod...
```
</details>

-------

| Reason | <code>sequential/test-single-executable-application-assets-raw</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 8 ([https://github.com/nodejs/node/pull/60072/](https://ci.nodejs.org/job/node-test-pull-request/69466/), [https://github.com/nodejs/node/pull/59999/](https://ci.nodejs.org/job/node-test-pull-request/69467/), [https://github.com/nodejs/node/pull/60047/](https://ci.nodejs.org/job/node-test-pull-request/69468/), [https://github.com/nodejs/node/pull/60052/](https://ci.nodejs.org/job/node-test-pull-request/69469/), [https://github.com/nodejs/node/pull/60038/](https://ci.nodejs.org/job/node-test-pull-request/69470/), [https://github.com/nodejs/node/pull/59928/](https://ci.nodejs.org/job/node-test-pull-request/69472/), [https://github.com/nodejs/node/pull/59778/](https://ci.nodejs.org/job/node-test-pull-request/69473/), [https://github.com/nodejs/node/pull/60073/](https://ci.nodejs.org/job/node-test-pull-request/69475/)) |
| Appeared | [vm-d4j6y](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67064/console), [vm-ums8n](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67061/console), [vm-mf6bp](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67061/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69466/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69475/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67064/console">Example</a></summary>

```
not ok 4767 sequential/test-single-executable-application-assets-raw
  ---
  duration_ms: 14413.53000
  severity: fail
  exitcode: 1
  stack: |-
    Copied /Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/out/Release/node to /Users/admin/node-tmp/.tmp.4766/sea
    Injected /Users/admin/node-tmp/.tmp.4766/sea-prep.blob into /Users/admin/node-tmp/.tmp.4766/sea
    Signed /Users/admin/node-tmp/.tmp.4766/sea
    [process 79273]: --- stderr ---
    dyld[79273]: failed to set up thread local variables for '/Users/admin/node-tmp/.tmp.4766/sea': unsupported thread-local, larger than 4GB
    
    [process 79273]: --- stdout ---
    
    [process 79273]: status = null, signal = SIGABRT
    /Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/test/common/child_process.js:98
        throw error;
        ^
    
    Error: - process terminated with status null, expected 0
    - process terminated with signal SIGABRT, expected null
        at Object.<anonymous> (/Users/admin/build/workspace...
```
</details>

-------

| Reason | <code>sequential/test-single-executable-application-disable-experimental-sea-warning</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 8 ([https://github.com/nodejs/node/pull/60072/](https://ci.nodejs.org/job/node-test-pull-request/69466/), [https://github.com/nodejs/node/pull/59999/](https://ci.nodejs.org/job/node-test-pull-request/69467/), [https://github.com/nodejs/node/pull/60047/](https://ci.nodejs.org/job/node-test-pull-request/69468/), [https://github.com/nodejs/node/pull/60052/](https://ci.nodejs.org/job/node-test-pull-request/69469/), [https://github.com/nodejs/node/pull/60038/](https://ci.nodejs.org/job/node-test-pull-request/69470/), [https://github.com/nodejs/node/pull/59928/](https://ci.nodejs.org/job/node-test-pull-request/69472/), [https://github.com/nodejs/node/pull/59778/](https://ci.nodejs.org/job/node-test-pull-request/69473/), [https://github.com/nodejs/node/pull/60073/](https://ci.nodejs.org/job/node-test-pull-request/69475/)) |
| Appeared | [vm-d4j6y](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67064/console), [vm-ums8n](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67061/console), [vm-mf6bp](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67061/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69466/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69475/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67064/console">Example</a></summary>

```
not ok 4768 sequential/test-single-executable-application-disable-experimental-sea-warning
  ---
  duration_ms: 14139.33700
  severity: fail
  exitcode: 1
  stack: |-
    Copied /Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/out/Release/node to /Users/admin/node-tmp/.tmp.4767/sea
    Injected /Users/admin/node-tmp/.tmp.4767/sea-prep.blob into /Users/admin/node-tmp/.tmp.4767/sea
    Signed /Users/admin/node-tmp/.tmp.4767/sea
    [process 79292]: --- stderr ---
    dyld[79292]: failed to set up thread local variables for '/Users/admin/node-tmp/.tmp.4767/sea': unsupported thread-local, larger than 4GB
    
    [process 79292]: --- stdout ---
    
    [process 79292]: status = null, signal = SIGABRT
    /Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/test/common/child_process.js:98
        throw error;
        ^
    
    Error: - process terminated with status null, expected 0
    - process terminated with signal SIGABRT, expected null
        at Object.<anonymous> (/Users...
```
</details>

-------

| Reason | <code>sequential/test-single-executable-application-exec-argv</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 8 ([https://github.com/nodejs/node/pull/60072/](https://ci.nodejs.org/job/node-test-pull-request/69466/), [https://github.com/nodejs/node/pull/59999/](https://ci.nodejs.org/job/node-test-pull-request/69467/), [https://github.com/nodejs/node/pull/60047/](https://ci.nodejs.org/job/node-test-pull-request/69468/), [https://github.com/nodejs/node/pull/60052/](https://ci.nodejs.org/job/node-test-pull-request/69469/), [https://github.com/nodejs/node/pull/60038/](https://ci.nodejs.org/job/node-test-pull-request/69470/), [https://github.com/nodejs/node/pull/59928/](https://ci.nodejs.org/job/node-test-pull-request/69472/), [https://github.com/nodejs/node/pull/59778/](https://ci.nodejs.org/job/node-test-pull-request/69473/), [https://github.com/nodejs/node/pull/60073/](https://ci.nodejs.org/job/node-test-pull-request/69475/)) |
| Appeared | [vm-d4j6y](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67064/console), [vm-ums8n](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67061/console), [vm-mf6bp](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67061/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69466/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69475/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67064/console">Example</a></summary>

```
not ok 4770 sequential/test-single-executable-application-exec-argv
  ---
  duration_ms: 14779.88400
  severity: fail
  exitcode: 1
  stack: |-
    Copied /Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/out/Release/node to /Users/admin/node-tmp/.tmp.4769/sea
    Injected /Users/admin/node-tmp/.tmp.4769/sea-prep.blob into /Users/admin/node-tmp/.tmp.4769/sea
    Signed /Users/admin/node-tmp/.tmp.4769/sea
    [process 79331]: --- stderr ---
    dyld[79331]: failed to set up thread local variables for '/Users/admin/node-tmp/.tmp.4769/sea': unsupported thread-local, larger than 4GB
    
    [process 79331]: --- stdout ---
    
    [process 79331]: status = null, signal = SIGABRT
    /Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/test/common/child_process.js:98
        throw error;
        ^
    
    Error: - process terminated with status null, expected 0
    - process terminated with signal SIGABRT, expected null
        at Object.<anonymous> (/Users/admin/build/workspace/...
```
</details>

-------

| Reason | <code>sequential/test-single-executable-application-exec-argv-empty</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 8 ([https://github.com/nodejs/node/pull/60072/](https://ci.nodejs.org/job/node-test-pull-request/69466/), [https://github.com/nodejs/node/pull/59999/](https://ci.nodejs.org/job/node-test-pull-request/69467/), [https://github.com/nodejs/node/pull/60047/](https://ci.nodejs.org/job/node-test-pull-request/69468/), [https://github.com/nodejs/node/pull/60052/](https://ci.nodejs.org/job/node-test-pull-request/69469/), [https://github.com/nodejs/node/pull/60038/](https://ci.nodejs.org/job/node-test-pull-request/69470/), [https://github.com/nodejs/node/pull/59928/](https://ci.nodejs.org/job/node-test-pull-request/69472/), [https://github.com/nodejs/node/pull/59778/](https://ci.nodejs.org/job/node-test-pull-request/69473/), [https://github.com/nodejs/node/pull/60073/](https://ci.nodejs.org/job/node-test-pull-request/69475/)) |
| Appeared | [vm-d4j6y](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67064/console), [vm-ums8n](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67061/console), [vm-mf6bp](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67061/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69466/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69475/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67064/console">Example</a></summary>

```
not ok 4771 sequential/test-single-executable-application-exec-argv-empty
  ---
  duration_ms: 15620.60300
  severity: fail
  exitcode: 1
  stack: |-
    Copied /Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/out/Release/node to /Users/admin/node-tmp/.tmp.4770/sea
    Injected /Users/admin/node-tmp/.tmp.4770/sea-prep.blob into /Users/admin/node-tmp/.tmp.4770/sea
    Signed /Users/admin/node-tmp/.tmp.4770/sea
    [process 79351]: --- stderr ---
    dyld[79351]: failed to set up thread local variables for '/Users/admin/node-tmp/.tmp.4770/sea': unsupported thread-local, larger than 4GB
    
    [process 79351]: --- stdout ---
    
    [process 79351]: status = null, signal = SIGABRT
    /Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/test/common/child_process.js:98
        throw error;
        ^
    
    Error: - process terminated with status null, expected 0
    - process terminated with signal SIGABRT, expected null
        at Object.<anonymous> (/Users/admin/build/work...
```
</details>

-------

| Reason | <code>sequential/test-single-executable-application-exec-argv-extension-cli</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 8 ([https://github.com/nodejs/node/pull/60072/](https://ci.nodejs.org/job/node-test-pull-request/69466/), [https://github.com/nodejs/node/pull/59999/](https://ci.nodejs.org/job/node-test-pull-request/69467/), [https://github.com/nodejs/node/pull/60047/](https://ci.nodejs.org/job/node-test-pull-request/69468/), [https://github.com/nodejs/node/pull/60052/](https://ci.nodejs.org/job/node-test-pull-request/69469/), [https://github.com/nodejs/node/pull/60038/](https://ci.nodejs.org/job/node-test-pull-request/69470/), [https://github.com/nodejs/node/pull/59928/](https://ci.nodejs.org/job/node-test-pull-request/69472/), [https://github.com/nodejs/node/pull/59778/](https://ci.nodejs.org/job/node-test-pull-request/69473/), [https://github.com/nodejs/node/pull/60073/](https://ci.nodejs.org/job/node-test-pull-request/69475/)) |
| Appeared | [vm-d4j6y](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67064/console), [vm-ums8n](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67061/console), [vm-mf6bp](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67061/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69466/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69475/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67064/console">Example</a></summary>

```
not ok 4772 sequential/test-single-executable-application-exec-argv-extension-cli
  ---
  duration_ms: 15079.09300
  severity: fail
  exitcode: 1
  stack: |-
    Copied /Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/out/Release/node to /Users/admin/node-tmp/.tmp.4771/sea
    Injected /Users/admin/node-tmp/.tmp.4771/sea-prep.blob into /Users/admin/node-tmp/.tmp.4771/sea
    Signed /Users/admin/node-tmp/.tmp.4771/sea
    [process 79370]: --- stderr ---
    dyld[79370]: failed to set up thread local variables for '/Users/admin/node-tmp/.tmp.4771/sea': unsupported thread-local, larger than 4GB
    
    [process 79370]: --- stdout ---
    
    [process 79370]: status = null, signal = SIGABRT
    /Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/test/common/child_process.js:98
        throw error;
        ^
    
    Error: - process terminated with status null, expected 0
    - process terminated with signal SIGABRT, expected null
        at Object.<anonymous> (/Users/admin/bu...
```
</details>

-------

| Reason | <code>sequential/test-single-executable-application-exec-argv-extension-env</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 8 ([https://github.com/nodejs/node/pull/60072/](https://ci.nodejs.org/job/node-test-pull-request/69466/), [https://github.com/nodejs/node/pull/59999/](https://ci.nodejs.org/job/node-test-pull-request/69467/), [https://github.com/nodejs/node/pull/60047/](https://ci.nodejs.org/job/node-test-pull-request/69468/), [https://github.com/nodejs/node/pull/60052/](https://ci.nodejs.org/job/node-test-pull-request/69469/), [https://github.com/nodejs/node/pull/60038/](https://ci.nodejs.org/job/node-test-pull-request/69470/), [https://github.com/nodejs/node/pull/59928/](https://ci.nodejs.org/job/node-test-pull-request/69472/), [https://github.com/nodejs/node/pull/59778/](https://ci.nodejs.org/job/node-test-pull-request/69473/), [https://github.com/nodejs/node/pull/60073/](https://ci.nodejs.org/job/node-test-pull-request/69475/)) |
| Appeared | [vm-d4j6y](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67064/console), [vm-ums8n](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67061/console), [vm-mf6bp](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67061/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69466/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69475/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67064/console">Example</a></summary>

```
not ok 4773 sequential/test-single-executable-application-exec-argv-extension-env
  ---
  duration_ms: 14675.49900
  severity: fail
  exitcode: 1
  stack: |-
    Copied /Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/out/Release/node to /Users/admin/node-tmp/.tmp.4772/sea
    Injected /Users/admin/node-tmp/.tmp.4772/sea-prep.blob into /Users/admin/node-tmp/.tmp.4772/sea
    Signed /Users/admin/node-tmp/.tmp.4772/sea
    [process 79390]: --- stderr ---
    dyld[79390]: failed to set up thread local variables for '/Users/admin/node-tmp/.tmp.4772/sea': unsupported thread-local, larger than 4GB
    
    [process 79390]: --- stdout ---
    
    [process 79390]: status = null, signal = SIGABRT
    /Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/test/common/child_process.js:98
        throw error;
        ^
    
    Error: - process terminated with status null, expected 0
    - process terminated with signal SIGABRT, expected null
        at Object.<anonymous> (/Users/admin/bu...
```
</details>

-------

| Reason | <code>sequential/test-single-executable-application-exec-argv-extension-none</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 8 ([https://github.com/nodejs/node/pull/60072/](https://ci.nodejs.org/job/node-test-pull-request/69466/), [https://github.com/nodejs/node/pull/59999/](https://ci.nodejs.org/job/node-test-pull-request/69467/), [https://github.com/nodejs/node/pull/60047/](https://ci.nodejs.org/job/node-test-pull-request/69468/), [https://github.com/nodejs/node/pull/60052/](https://ci.nodejs.org/job/node-test-pull-request/69469/), [https://github.com/nodejs/node/pull/60038/](https://ci.nodejs.org/job/node-test-pull-request/69470/), [https://github.com/nodejs/node/pull/59928/](https://ci.nodejs.org/job/node-test-pull-request/69472/), [https://github.com/nodejs/node/pull/59778/](https://ci.nodejs.org/job/node-test-pull-request/69473/), [https://github.com/nodejs/node/pull/60073/](https://ci.nodejs.org/job/node-test-pull-request/69475/)) |
| Appeared | [vm-d4j6y](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67064/console), [vm-ums8n](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67061/console), [vm-mf6bp](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67061/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69466/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69475/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67064/console">Example</a></summary>

```
not ok 4774 sequential/test-single-executable-application-exec-argv-extension-none
  ---
  duration_ms: 14285.88700
  severity: fail
  exitcode: 1
  stack: |-
    Copied /Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/out/Release/node to /Users/admin/node-tmp/.tmp.4773/sea
    Injected /Users/admin/node-tmp/.tmp.4773/sea-prep.blob into /Users/admin/node-tmp/.tmp.4773/sea
    Signed /Users/admin/node-tmp/.tmp.4773/sea
    [process 79409]: --- stderr ---
    dyld[79409]: failed to set up thread local variables for '/Users/admin/node-tmp/.tmp.4773/sea': unsupported thread-local, larger than 4GB
    
    [process 79409]: --- stdout ---
    
    [process 79409]: status = null, signal = SIGABRT
    /Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/test/common/child_process.js:98
        throw error;
        ^
    
    Error: - process terminated with status null, expected 0
    - process terminated with signal SIGABRT, expected null
        at Object.<anonymous> (/Users/admin/b...
```
</details>

-------

| Reason | <code>sequential/test-single-executable-application-inspect</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 8 ([https://github.com/nodejs/node/pull/60072/](https://ci.nodejs.org/job/node-test-pull-request/69466/), [https://github.com/nodejs/node/pull/59999/](https://ci.nodejs.org/job/node-test-pull-request/69467/), [https://github.com/nodejs/node/pull/60047/](https://ci.nodejs.org/job/node-test-pull-request/69468/), [https://github.com/nodejs/node/pull/60052/](https://ci.nodejs.org/job/node-test-pull-request/69469/), [https://github.com/nodejs/node/pull/60038/](https://ci.nodejs.org/job/node-test-pull-request/69470/), [https://github.com/nodejs/node/pull/59928/](https://ci.nodejs.org/job/node-test-pull-request/69472/), [https://github.com/nodejs/node/pull/59778/](https://ci.nodejs.org/job/node-test-pull-request/69473/), [https://github.com/nodejs/node/pull/60073/](https://ci.nodejs.org/job/node-test-pull-request/69475/)) |
| Appeared | [vm-d4j6y](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67064/console), [vm-ums8n](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67061/console), [vm-mf6bp](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67061/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69466/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69475/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67064/console">Example</a></summary>

```
not ok 4775 sequential/test-single-executable-application-inspect
  ---
  duration_ms: 14495.05700
  severity: fail
  exitcode: 1
  stack: |-
    Copied /Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/out/Release/node to /Users/admin/node-tmp/.tmp.4774/sea
    Injected /Users/admin/node-tmp/.tmp.4774/sea-prep.blob into /Users/admin/node-tmp/.tmp.4774/sea
    Signed /Users/admin/node-tmp/.tmp.4774/sea
    [SEA][STDERR] dyld[79429]: failed to set up thread local variables for '/Users/admin/node-tmp/.tmp.4774/sea': unsupported thread-local, larger than 4GB
    
    node:assert:149
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: SEA process exited with code null.
    
    null !== 0
    
        at ChildProcess.<anonymous> (/Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/test/sequential/test-single-executable-application-inspect.js:117:10)
        at ChildProcess.emit (node:events:508:28)
        at maybeClose (node:internal/child_proce...
```
</details>

-------

| Reason | <code>sequential/test-single-executable-application-inspect-in-sea-flags</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 8 ([https://github.com/nodejs/node/pull/60072/](https://ci.nodejs.org/job/node-test-pull-request/69466/), [https://github.com/nodejs/node/pull/59999/](https://ci.nodejs.org/job/node-test-pull-request/69467/), [https://github.com/nodejs/node/pull/60047/](https://ci.nodejs.org/job/node-test-pull-request/69468/), [https://github.com/nodejs/node/pull/60052/](https://ci.nodejs.org/job/node-test-pull-request/69469/), [https://github.com/nodejs/node/pull/60038/](https://ci.nodejs.org/job/node-test-pull-request/69470/), [https://github.com/nodejs/node/pull/59928/](https://ci.nodejs.org/job/node-test-pull-request/69472/), [https://github.com/nodejs/node/pull/59778/](https://ci.nodejs.org/job/node-test-pull-request/69473/), [https://github.com/nodejs/node/pull/60073/](https://ci.nodejs.org/job/node-test-pull-request/69475/)) |
| Appeared | [vm-d4j6y](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67064/console), [vm-ums8n](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67061/console), [vm-mf6bp](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67061/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69466/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69475/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67064/console">Example</a></summary>

```
not ok 4776 sequential/test-single-executable-application-inspect-in-sea-flags
  ---
  duration_ms: 14974.92400
  severity: fail
  exitcode: 1
  stack: |-
    Copied /Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/out/Release/node to /Users/admin/node-tmp/.tmp.4775/sea
    Injected /Users/admin/node-tmp/.tmp.4775/sea-prep.blob into /Users/admin/node-tmp/.tmp.4775/sea
    Signed /Users/admin/node-tmp/.tmp.4775/sea
    [process 79448]: --- stderr ---
    dyld[79448]: failed to set up thread local variables for '/Users/admin/node-tmp/.tmp.4775/sea': unsupported thread-local, larger than 4GB
    
    [process 79448]: --- stdout ---
    
    [process 79448]: status = null, signal = SIGABRT
    /Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/test/common/child_process.js:98
        throw error;
        ^
    
    Error: - process terminated with status null, expected 0
    - process terminated with signal SIGABRT, expected null
        at Object.<anonymous> (/Users/admin/build...
```
</details>

-------

| Reason | <code>sequential/test-single-executable-application-snapshot</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 8 ([https://github.com/nodejs/node/pull/60072/](https://ci.nodejs.org/job/node-test-pull-request/69466/), [https://github.com/nodejs/node/pull/59999/](https://ci.nodejs.org/job/node-test-pull-request/69467/), [https://github.com/nodejs/node/pull/60047/](https://ci.nodejs.org/job/node-test-pull-request/69468/), [https://github.com/nodejs/node/pull/60052/](https://ci.nodejs.org/job/node-test-pull-request/69469/), [https://github.com/nodejs/node/pull/60038/](https://ci.nodejs.org/job/node-test-pull-request/69470/), [https://github.com/nodejs/node/pull/59928/](https://ci.nodejs.org/job/node-test-pull-request/69472/), [https://github.com/nodejs/node/pull/59778/](https://ci.nodejs.org/job/node-test-pull-request/69473/), [https://github.com/nodejs/node/pull/60073/](https://ci.nodejs.org/job/node-test-pull-request/69475/)) |
| Appeared | [vm-d4j6y](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67064/console), [vm-ums8n](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67061/console), [vm-mf6bp](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67061/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69466/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69475/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67064/console">Example</a></summary>

```
not ok 4777 sequential/test-single-executable-application-snapshot
  ---
  duration_ms: 16011.61300
  severity: fail
  exitcode: 1
  stack: |-
    Copied /Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/out/Release/node to /Users/admin/node-tmp/.tmp.4776/sea
    Injected /Users/admin/node-tmp/.tmp.4776/sea-prep.blob into /Users/admin/node-tmp/.tmp.4776/sea
    Signed /Users/admin/node-tmp/.tmp.4776/sea
    [process 79469]: --- stderr ---
    dyld[79469]: failed to set up thread local variables for '/Users/admin/node-tmp/.tmp.4776/sea': unsupported thread-local, larger than 4GB
    
    [process 79469]: --- stdout ---
    
    [process 79469]: status = null, signal = SIGABRT
    /Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/test/common/child_process.js:98
        throw error;
        ^
    
    Error: - process terminated with status null, expected 0
    - process terminated with signal SIGABRT, expected null
        at Object.<anonymous> (/Users/admin/build/workspace/n...
```
</details>

-------

| Reason | <code>sequential/test-single-executable-application-snapshot-and-code-cache</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 8 ([https://github.com/nodejs/node/pull/60072/](https://ci.nodejs.org/job/node-test-pull-request/69466/), [https://github.com/nodejs/node/pull/59999/](https://ci.nodejs.org/job/node-test-pull-request/69467/), [https://github.com/nodejs/node/pull/60047/](https://ci.nodejs.org/job/node-test-pull-request/69468/), [https://github.com/nodejs/node/pull/60052/](https://ci.nodejs.org/job/node-test-pull-request/69469/), [https://github.com/nodejs/node/pull/60038/](https://ci.nodejs.org/job/node-test-pull-request/69470/), [https://github.com/nodejs/node/pull/59928/](https://ci.nodejs.org/job/node-test-pull-request/69472/), [https://github.com/nodejs/node/pull/59778/](https://ci.nodejs.org/job/node-test-pull-request/69473/), [https://github.com/nodejs/node/pull/60073/](https://ci.nodejs.org/job/node-test-pull-request/69475/)) |
| Appeared | [vm-d4j6y](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67064/console), [vm-ums8n](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67061/console), [vm-mf6bp](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67061/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69466/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69475/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67064/console">Example</a></summary>

```
not ok 4778 sequential/test-single-executable-application-snapshot-and-code-cache
  ---
  duration_ms: 16430.14900
  severity: fail
  exitcode: 1
  stack: |-
    Copied /Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/out/Release/node to /Users/admin/node-tmp/.tmp.4777/sea
    Injected /Users/admin/node-tmp/.tmp.4777/sea-prep.blob into /Users/admin/node-tmp/.tmp.4777/sea
    Signed /Users/admin/node-tmp/.tmp.4777/sea
    [process 79488]: --- stderr ---
    dyld[79488]: failed to set up thread local variables for '/Users/admin/node-tmp/.tmp.4777/sea': unsupported thread-local, larger than 4GB
    
    [process 79488]: --- stdout ---
    
    [process 79488]: status = null, signal = SIGABRT
    /Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/test/common/child_process.js:98
        throw error;
        ^
    
    Error: - process terminated with status null, expected 0
    - process terminated with signal SIGABRT, expected null
        at Object.<anonymous> (/Users/admin/bu...
```
</details>

-------

| Reason | <code>sequential/test-single-executable-application-snapshot-worker</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 8 ([https://github.com/nodejs/node/pull/60072/](https://ci.nodejs.org/job/node-test-pull-request/69466/), [https://github.com/nodejs/node/pull/59999/](https://ci.nodejs.org/job/node-test-pull-request/69467/), [https://github.com/nodejs/node/pull/60047/](https://ci.nodejs.org/job/node-test-pull-request/69468/), [https://github.com/nodejs/node/pull/60052/](https://ci.nodejs.org/job/node-test-pull-request/69469/), [https://github.com/nodejs/node/pull/60038/](https://ci.nodejs.org/job/node-test-pull-request/69470/), [https://github.com/nodejs/node/pull/59928/](https://ci.nodejs.org/job/node-test-pull-request/69472/), [https://github.com/nodejs/node/pull/59778/](https://ci.nodejs.org/job/node-test-pull-request/69473/), [https://github.com/nodejs/node/pull/60073/](https://ci.nodejs.org/job/node-test-pull-request/69475/)) |
| Appeared | [vm-d4j6y](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67064/console), [vm-ums8n](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67061/console), [vm-mf6bp](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67061/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69466/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69475/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67064/console">Example</a></summary>

```
not ok 4779 sequential/test-single-executable-application-snapshot-worker
  ---
  duration_ms: 16631.52100
  severity: fail
  exitcode: 1
  stack: |-
    Copied /Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/out/Release/node to /Users/admin/node-tmp/.tmp.4778/sea
    Injected /Users/admin/node-tmp/.tmp.4778/sea-prep.blob into /Users/admin/node-tmp/.tmp.4778/sea
    Signed /Users/admin/node-tmp/.tmp.4778/sea
    [process 79508]: --- stderr ---
    dyld[79508]: failed to set up thread local variables for '/Users/admin/node-tmp/.tmp.4778/sea': unsupported thread-local, larger than 4GB
    
    [process 79508]: --- stdout ---
    
    [process 79508]: status = null, signal = SIGABRT
    /Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/test/common/child_process.js:98
        throw error;
        ^
    
    Error: - process terminated with status null, expected 0
    - process terminated with signal SIGABRT, expected null
        at Object.<anonymous> (/Users/admin/build/work...
```
</details>

-------

| Reason | <code>sequential/test-single-executable-application-use-code-cache</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 8 ([https://github.com/nodejs/node/pull/60072/](https://ci.nodejs.org/job/node-test-pull-request/69466/), [https://github.com/nodejs/node/pull/59999/](https://ci.nodejs.org/job/node-test-pull-request/69467/), [https://github.com/nodejs/node/pull/60047/](https://ci.nodejs.org/job/node-test-pull-request/69468/), [https://github.com/nodejs/node/pull/60052/](https://ci.nodejs.org/job/node-test-pull-request/69469/), [https://github.com/nodejs/node/pull/60038/](https://ci.nodejs.org/job/node-test-pull-request/69470/), [https://github.com/nodejs/node/pull/59928/](https://ci.nodejs.org/job/node-test-pull-request/69472/), [https://github.com/nodejs/node/pull/59778/](https://ci.nodejs.org/job/node-test-pull-request/69473/), [https://github.com/nodejs/node/pull/60073/](https://ci.nodejs.org/job/node-test-pull-request/69475/)) |
| Appeared | [vm-d4j6y](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67064/console), [vm-ums8n](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67061/console), [vm-mf6bp](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67061/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69466/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69475/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67064/console">Example</a></summary>

```
not ok 4780 sequential/test-single-executable-application-use-code-cache
  ---
  duration_ms: 15058.41300
  severity: fail
  exitcode: 1
  stack: |-
    Copied /Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/out/Release/node to /Users/admin/node-tmp/.tmp.4779/sea
    Injected /Users/admin/node-tmp/.tmp.4779/sea-prep.blob into /Users/admin/node-tmp/.tmp.4779/sea
    Signed /Users/admin/node-tmp/.tmp.4779/sea
    [process 79528]: --- stderr ---
    dyld[79528]: failed to set up thread local variables for '/Users/admin/node-tmp/.tmp.4779/sea': unsupported thread-local, larger than 4GB
    
    [process 79528]: --- stdout ---
    
    [process 79528]: status = null, signal = SIGABRT
    /Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/test/common/child_process.js:98
        throw error;
        ^
    
    Error: - process terminated with status null, expected 0
    - process terminated with signal SIGABRT, expected null
        at Object.<anonymous> (/Users/admin/build/works...
```
</details>

-------

| Reason | <code>parallel/test-quic-test-client</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 7 ([https://github.com/nodejs/node/pull/60047/](https://ci.nodejs.org/job/node-test-pull-request/69468/), [https://github.com/nodejs/node/pull/60068/](https://ci.nodejs.org/job/node-test-pull-request/69471/), [https://github.com/nodejs/node/pull/60043/](https://ci.nodejs.org/job/node-test-pull-request/69476/), [https://github.com/nodejs/node/pull/60029/](https://ci.nodejs.org/job/node-test-pull-request/69477/), [https://github.com/nodejs/node/pull/59996/](https://ci.nodejs.org/job/node-test-pull-request/69484/), [https://github.com/nodejs/node/pull/59877/](https://ci.nodejs.org/job/node-test-pull-request/69520/), [https://github.com/nodejs/node/pull/59952/](https://ci.nodejs.org/job/node-test-pull-request/69560/)) |
| Appeared | [vm-m34hc](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67161/console), [vm-of2j2](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67126/console), [vm-hn1w7](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67120/console), [vm-9ks3c](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67073/console), [vm-o5844](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67066/console), [vm-s1fp9](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67065/console), [vm-d4j6y](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67060/console), [vm-ums8n](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67057/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69468/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69560/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67161/console">Example</a></summary>

```
not ok 2567 parallel/test-quic-test-client
  ---
  duration_ms: 1531.02300
  severity: fail
  exitcode: 1
  stack: |-
    /Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/out/Release/ngtcp2_test_client
    node:internal/modules/run_main:107
        triggerUncaughtException(
        ^
    
    AssertionError [ERR_ASSERTION]: Missing expected rejection.
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
        at async file:///Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/test/parallel/test-quic-test-client.mjs:31:1 {
      generatedMessage: false,
      code: 'ERR_ASSERTION',
      actual: undefined,
      expected: { message: /Process exited with code 1 and signal null/ },
      operator: 'rejects',
      diff: 'simple'
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-runner-watch-mode-kill-signal</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 7 ([https://github.com/nodejs/node/pull/59999/](https://ci.nodejs.org/job/node-test-pull-request/69467/), [https://github.com/nodejs/node/pull/60069/](https://ci.nodejs.org/job/node-test-pull-request/69499/), [https://github.com/nodejs/node/pull/59952/](https://ci.nodejs.org/job/node-test-pull-request/69510/), [https://github.com/nodejs/node/pull/60115/](https://ci.nodejs.org/job/node-test-pull-request/69521/), [https://github.com/nodejs/node/pull/59805/](https://ci.nodejs.org/job/node-test-pull-request/69537/), [https://github.com/nodejs/node/pull/60060/](https://ci.nodejs.org/job/node-test-pull-request/69541/), [https://github.com/nodejs/node/pull/60059/](https://ci.nodejs.org/job/node-test-pull-request/69549/)) |
| Appeared | [test-azure-ubuntu2204_container-arm64-5](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/60611/console), [vm-asmhb](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67139/console), [vm-2ri4d](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67136/console), [test-azure-ubuntu2204_container-arm64-6](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/20578/console), [vm-5sqy5](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67107/console), [vm-xw0o3](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67106/console), [vm-035qn](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-arm64/67082/console), [vm-xrzl3](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-arm64/67056/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69467/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69549/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/60611/console">Example</a></summary>

```
not ok 2943 parallel/test-runner-watch-mode-kill-signal
  ---
  duration_ms: 2414.30900
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'can be overridden (to SIGINT)'
    Location: test/parallel/test-runner-watch-mode-kill-signal.mjs:72:3
    AssertionError [ERR_ASSERTION]: The input was expected to not match the regular expression /__SIGTERM received__/. Input:
    
    "Restarting '/home/iojs/node-tmp/.tmp.2949/index.js'\n" +
      '__SIGINT received__\n' +
      '__SIGTERM received__\n'
    
        at TestContext.<anonymous> (file:///home/iojs/build/workspace/node-test-commit-arm/test/parallel/test-runner-watch-mode-kill-signal.mjs:103:12)
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
        at async Test.run (node:internal/test_runner/test:1113:7)
        at async Suite.processPendingSubtests (node:internal/test_runner/test:788:7) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: "Restarting '/home/iojs/node-tmp/.tmp.2949/in...
```
</details>

-------

| Reason | <code>parallel/test-http2-close-while-writing</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/60047/](https://ci.nodejs.org/job/node-test-pull-request/69468/), [https://github.com/nodejs/node/pull/60038/](https://ci.nodejs.org/job/node-test-pull-request/69470/), [https://github.com/nodejs/node/pull/60068/](https://ci.nodejs.org/job/node-test-pull-request/69471/), [https://github.com/nodejs/node/pull/60024/](https://ci.nodejs.org/job/node-test-pull-request/69506/), [https://github.com/nodejs/node/pull/59952/](https://ci.nodejs.org/job/node-test-pull-request/69540/)) |
| Appeared | [vm-fca2x](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67138/console), [vm-fl5w8](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67102/console), [vm-d4j6y](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67060/console), [vm-ums8n](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67059/console), [vm-mf6bp](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67053/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69468/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69540/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67138/console">Example</a></summary>

```
not ok 2363 parallel/test-http2-close-while-writing
  ---
  duration_ms: 120086.78500
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>sequential/test-perf-hooks</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/60068/](https://ci.nodejs.org/job/node-test-pull-request/69471/), [https://github.com/nodejs/node/pull/60073/](https://ci.nodejs.org/job/node-test-pull-request/69479/), [https://github.com/nodejs/node/pull/60082/](https://ci.nodejs.org/job/node-test-pull-request/69504/), [https://github.com/nodejs/node/pull/60115/](https://ci.nodejs.org/job/node-test-pull-request/69528/), [https://github.com/nodejs/node/pull/60059/](https://ci.nodejs.org/job/node-test-pull-request/69556/)) |
| Appeared | [vm-66gbr](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67157/console), [vm-y9ecw](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67128/console), [vm-fl5w8](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67100/console), [vm-mfxmz](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67068/console), [vm-d4j6y](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67060/console), [vm-ums8n](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67053/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69471/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69556/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67157/console">Example</a></summary>

```
not ok 4757 sequential/test-perf-hooks
  ---
  duration_ms: 1055.89100
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/assert/utils:77
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: Date.now() - performance.timeOrigin (607.282958984375) - process.uptime() * 1000 (438.37600599999996) = 168.90695298437504 >= +- 50
        at Object.<anonymous> (/Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/test/sequential/test-perf-hooks.js:36:3)
        at Module._compile (node:internal/modules/cjs/loader:1759:14)
        at Object..js (node:internal/modules/cjs/loader:1892:10)
        at Module.load (node:internal/modules/cjs/loader:1479:32)
        at Module._load (node:internal/modules/cjs/loader:1298:12)
        at TracingChannel.traceSync (node:diagnostics_channel:328:14)
        at wrapModuleLoad (node:internal/modules/cjs/loader:244:24)
        at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
        at node:internal/main/run_ma...
```
</details>

-------

| Reason | <code>parallel/test-runner-run</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/59805/](https://ci.nodejs.org/job/node-test-pull-request/69517/), [https://github.com/nodejs/node/pull/60040/](https://ci.nodejs.org/job/node-test-pull-request/69533/), [https://github.com/nodejs/node/pull/59952/](https://ci.nodejs.org/job/node-test-pull-request/69540/), [https://github.com/nodejs/node/pull/60060/](https://ci.nodejs.org/job/node-test-pull-request/69545/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-COMPILED_BY-vs2019/37085/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69517/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69545/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-COMPILED_BY-vs2019/37085/console">Example</a></summary>

```
not ok 691 parallel/test-runner-run
  ---
  duration_ms: 4080.99800
  severity: fail
  exitcode: 1
  stack: |-
    TAP version 13
    # Subtest: require('node:test').run
        # Subtest: should run with no tests
        ok 1 - should run with no tests
          ---
          duration_ms: 291.918
          ...

```
</details>

-------

| Reason | <code>sequential/test-gc-http-client</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59996/](https://ci.nodejs.org/job/node-test-pull-request/69480/), [https://github.com/nodejs/node/pull/60029/](https://ci.nodejs.org/job/node-test-pull-request/69481/)) |
| Appeared | [vm-o5844](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67069/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69480/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69481/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67069/console">Example</a></summary>

```
not ok 4714 sequential/test-gc-http-client
  ---
  duration_ms: 897.91300
  severity: fail
  exitcode: 1
  stack: |-
    done/collected/total: 1/0/168
    done/collected/total: 1/1/168
    done/collected/total: 1/1/168
    done/collected/total: 2/1/168
    done/collected/total: 3/2/168
    done/collected/total: 4/3/168
    done/collected/total: 5/4/168
    done/collected/total: 6/5/168
    done/collected/total: 7/6/168
    done/collected/total: 8/7/168
    done/collected/total: 9/8/168
    done/collected/total: 10/9/168
    done/collected/total: 11/10/168
    done/collected/total: 12/11/168
    done/collected/total: 13/12/168
    done/collected/total: 14/13/168
    done/collected/total: 15/14/168
    done/collected/total: 16/15/168
    done/collected/total: 17/16/168
    done/collected/total: 18/17/168
    done/collected/total: 19/18/168
    done/collected/total: 20/19/168
    node:events:486
          throw er; // Unhandled 'error' event
          ^
    
    AggregateError [ECONNRESET]: 
        at internalC...
```
</details>

-------

| Reason | <code>wpt/test-hr-time</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60029/](https://ci.nodejs.org/job/node-test-pull-request/69481/), [https://github.com/nodejs/node/pull/60014/](https://ci.nodejs.org/job/node-test-pull-request/69496/)) |
| Appeared | [vm-ectrz](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67088/console), [vm-mfxmz](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67070/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69481/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69496/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67088/console">Example</a></summary>

```
not ok 4814 wpt/test-hr-time
  ---
  duration_ms: 2389.19100
  severity: fail
  exitcode: 1
  stack: |-
    [SKIPPED] idlharness-shadowrealm.window.js: ShadowRealm support is not enabled
    [SKIPPED] window-worker-timeOrigin.window.js: depends on URL.createObjectURL(blob)
    [PASS] self.performance.now() is a function that returns a number
    [PASS] self.performance.now() returns a positive number
    [PASS] self.performance.now() difference is not negative
    [PASS] Performance interface extends EventTarget.
    [PASS] self.performance.now() returns a positive number
    [PASS] self.performance.now() difference is not negative
    [PASS] idl_test validation
    [PASS] Partial interface mixin WindowOrWorkerGlobalScope: original interface mixin defined
    [PASS] Partial interface mixin WindowOrWorkerGlobalScope: member names are unique
    [PASS] Partial interface Window: member names are unique
    [PASS] Window includes GlobalEventHandlers: member names are unique
    [PASS] Window includes WindowEventH...
```
</details>

-------

| Reason | <code>wpt/test-streams</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60045/](https://ci.nodejs.org/job/node-test-pull-request/69492/), [https://github.com/nodejs/node/pull/60105/](https://ci.nodejs.org/job/node-test-pull-request/69505/)) |
| Appeared | [test-ibm-aix72-ppc64_be-2](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59270/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69492/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69505/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59270/console">Example</a></summary>

```
not ok 4839 wpt/test-streams
  ---
  duration_ms: 1566.23700
  severity: crashed
  exitcode: -5
  stack: |-
    [SKIPPED] queuing-strategies-size-function-per-global.window.js: Browser-specific test
    [SKIPPED] readable-streams/cross-realm-crash.window.js: Browser-specific test
    [SKIPPED] readable-streams/owning-type-video-frame.any.js: Browser-specific test
    [SKIPPED] readable-streams/read-task-handling.window.js: Browser-specific test
    [SKIPPED] transferable/deserialize-error.window.js: Browser-specific test
    [SKIPPED] transferable/transfer-with-messageport.window.js: Browser-specific test
    [SKIPPED] transform-streams/invalid-realm.tentative.window.js: Browser-specific test
    [EXPECTED_FAILURE][FAIL] enqueue() must not synchronously call write algorithm
    assert_false: write algorithm must not run synchronously expected false got true
        at Test.<anonymous> (/home/iojs/build/workspace/node-test-commit-aix/nodes/aix72-ppc64/test/fixtures/wpt/streams/piping/general-addition.any.js:14...
```
</details>

-------

