Failures in [node-test-pull-request/69776](https://ci.nodejs.org/job/node-test-pull-request/69776/) to [node-test-pull-request/69874](https://ci.nodejs.org/job/node-test-pull-request/69874/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2025-10-25.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2025-10-25 00:10 | 0       | 24      | 17       | 4       | 55      | 25.00%     |


### Jenkins Failure

| Reason | <code>Backing channel 'JNLP4-connect connection from ... is disconnected.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60330/](https://ci.nodejs.org/job/node-test-pull-request/69842/), [https://github.com/nodejs/node/pull/60331/](https://ci.nodejs.org/job/node-test-pull-request/69843/)) |
| Appeared | [test-digitalocean-ubuntu2404-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=ubuntu2404-x64/67067/console), [test-digitalocean-ubuntu2404-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=ubuntu2404-x64/67066/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69842/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69843/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=ubuntu2404-x64/67067/console">Example</a></summary>

```
java.io.IOException: Backing channel 'JNLP4-connect connection from 167.99.124.188/167.99.124.188:48116' is disconnected.
	at hudson.remoting.RemoteInvocationHandler.channelOrFail(RemoteInvocationHandler.java:227)
	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:306)
	at jdk.proxy2/jdk.proxy2.$Proxy105.isAlive(Unknown Source)
	at hudson.Launcher$RemoteLauncher$ProcImpl.isAlive(Launcher.java:1227)
	at hudson.Launcher$RemoteLauncher$ProcImpl.join(Launcher.java:1219)
```
</details>

-------

| Reason | <code>Build timed out (after 30 minutes). Marking the build as failed.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60255/](https://ci.nodejs.org/job/node-test-pull-request/69805/), [https://github.com/nodejs/node/pull/60111/](https://ci.nodejs.org/job/node-test-pull-request/69831/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/37352/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69805/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69831/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/37352/console">Example</a></summary>

```
Build timed out (after 30 minutes). Marking the build as failed.
```
</details>

-------


### Build Failure

| Reason | <code>fatal: No rebase in progress?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/60230/](https://ci.nodejs.org/job/node-test-pull-request/69791/), [https://github.com/nodejs/node/pull/60255/](https://ci.nodejs.org/job/node-test-pull-request/69805/), [https://github.com/nodejs/node/pull/60289/](https://ci.nodejs.org/job/node-test-pull-request/69809/), [https://github.com/nodejs/node/pull/60298/](https://ci.nodejs.org/job/node-test-pull-request/69810/), [https://github.com/nodejs/node/pull/60331/](https://ci.nodejs.org/job/node-test-pull-request/69843/), [https://github.com/nodejs/node/pull/60281/](https://ci.nodejs.org/job/node-test-pull-request/69847/)) |
| Appeared | [test-digitalocean-ubuntu2404_sharedlibs_container-x64-6](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_shared_x64/53256/console), [test-digitalocean-ubuntu2404_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_shared_x64/53252/console), [test-mnx-ubuntu2204-x64-1](https://ci.nodejs.org/job/node-test-linter/62233/console), [test-ibm-ubuntu2404_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_shared_x64/53211/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69791/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69847/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_shared_x64/53256/console">Example</a></summary>

```
fatal: No rebase in progress?
```
</details>

-------


### JSTest Failure

| Reason | <code>parallel/test-without-async-context-frame</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 7 ([https://github.com/nodejs/node/pull/60205/](https://ci.nodejs.org/job/node-test-pull-request/69778/), [https://github.com/nodejs/node/pull/60266/](https://ci.nodejs.org/job/node-test-pull-request/69780/), [https://github.com/nodejs/node/pull/60271/](https://ci.nodejs.org/job/node-test-pull-request/69781/), [https://github.com/nodejs/node/pull/60277/](https://ci.nodejs.org/job/node-test-pull-request/69785/), [https://github.com/nodejs/node/pull/60272/](https://ci.nodejs.org/job/node-test-pull-request/69786/), [https://github.com/nodejs/node/pull/60269/](https://ci.nodejs.org/job/node-test-pull-request/69793/), [https://github.com/nodejs/node/pull/60289/](https://ci.nodejs.org/job/node-test-pull-request/69799/)) |
| Appeared | [vm-xrtit](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67444/console), [vm-qeafq](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67435/console), [vm-4tv35](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67433/console), [vm-oa16m](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67427/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69778/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69799/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67444/console">Example</a></summary>

```
not ok 4167 parallel/test-without-async-context-frame
  ---
  duration_ms: 120040.46100
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-http2-close-while-writing</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/60269/](https://ci.nodejs.org/job/node-test-pull-request/69779/), [https://github.com/nodejs/node/pull/60271/](https://ci.nodejs.org/job/node-test-pull-request/69794/), [https://github.com/nodejs/node/pull/60289/](https://ci.nodejs.org/job/node-test-pull-request/69799/), [https://github.com/nodejs/node/pull/60278/](https://ci.nodejs.org/job/node-test-pull-request/69823/), [https://github.com/nodejs/node/pull/60313/](https://ci.nodejs.org/job/node-test-pull-request/69848/)) |
| Appeared | [test-osuosl-rhel8-ppc64_le-2](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel8-ppc64le/61216/console), [vm-o2tby](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67468/console), [vm-xrtit](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67444/console), [vm-ehfzr](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67441/console), [vm-qeafq](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67426/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69779/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69848/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel8-ppc64le/61216/console">Example</a></summary>

```
not ok 3080 parallel/test-http2-close-while-writing
  ---
  duration_ms: 120095.83000
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-runner-output</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/60131/](https://ci.nodejs.org/job/node-test-pull-request/69792/), [https://github.com/nodejs/node/pull/60266/](https://ci.nodejs.org/job/node-test-pull-request/69796/), [https://github.com/nodejs/node/pull/60274/](https://ci.nodejs.org/job/node-test-pull-request/69818/), [https://github.com/nodejs/node/pull/59873/](https://ci.nodejs.org/job/node-test-pull-request/69835/), [https://github.com/nodejs/node/pull/60334/](https://ci.nodejs.org/job/node-test-pull-request/69838/)) |
| Appeared | [test-ibm-rhel9-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel9-x64/67060/console), [vm-zn9if](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67483/console), [undefined](https://ci.nodejs.org/job/node-test-commit-custom-suites-freestyle/44458/console), [test-azure_msft-win11_vs2022-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-COMPILED_BY-vs2022_clang/37319/console), [test-osuosl-aix72-ppc64_be-4](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59443/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69792/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69838/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel9-x64/67060/console">Example</a></summary>

```
not ok 3236 parallel/test-runner-output
  ---
  duration_ms: 7428.58700
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'test-runner/output/test-timeout-flag.js'
    Location: test/parallel/test-runner-output.mjs:356:5
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    + actual - expected
    ... Skipped lines
    
      'TAP version 13\n' +
        '# Subtest: --test-timeout is set to 100ms\n' +
        '    # Subtest: should timeout after 100ms\n' +
        '    not ok 1 - should timeout after 100ms\n' +
        '      ---\n' +
    ...

```
</details>

-------

| Reason | <code>sequential/test-perf-hooks</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/60269/](https://ci.nodejs.org/job/node-test-pull-request/69788/), [https://github.com/nodejs/node/pull/60289/](https://ci.nodejs.org/job/node-test-pull-request/69799/), [https://github.com/nodejs/node/pull/60248/](https://ci.nodejs.org/job/node-test-pull-request/69841/), [https://github.com/nodejs/node/pull/60330/](https://ci.nodejs.org/job/node-test-pull-request/69842/), [https://github.com/nodejs/node/pull/60331/](https://ci.nodejs.org/job/node-test-pull-request/69843/)) |
| Appeared | [vm-k7hpr](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67492/console), [vm-xrtit](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67444/console), [vm-qeafq](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67435/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69788/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69843/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67492/console">Example</a></summary>

```
not ok 4747 sequential/test-perf-hooks
  ---
  duration_ms: 895.86800
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/assert/utils:77
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: Date.now() - performance.timeOrigin (491.593017578125) - process.uptime() * 1000 (371.23216399999995) = 120.36085357812505 >= +- 50
        at Object.<anonymous> (/Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/sequential/test-perf-hooks.js:36:3)
        at Module._compile (node:internal/modules/cjs/loader:1760:14)
        at Object..js (node:internal/modules/cjs/loader:1893:10)
        at Module.load (node:internal/modules/cjs/loader:1480:32)
        at Module._load (node:internal/modules/cjs/loader:1299:12)
        at TracingChannel.traceSync (node:diagnostics_channel:328:14)
        at wrapModuleLoad (node:internal/modules/cjs/loader:244:24)
        at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
        at node:internal/main/run_main_...
```
</details>

-------

| Reason | <code>sequential/test-worker-prof</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/60269/](https://ci.nodejs.org/job/node-test-pull-request/69779/), [https://github.com/nodejs/node/pull/60266/](https://ci.nodejs.org/job/node-test-pull-request/69796/), [https://github.com/nodejs/node/pull/60289/](https://ci.nodejs.org/job/node-test-pull-request/69814/), [https://github.com/nodejs/node/pull/60274/](https://ci.nodejs.org/job/node-test-pull-request/69818/), [https://github.com/nodejs/node/pull/60364/](https://ci.nodejs.org/job/node-test-pull-request/69858/)) |
| Appeared | [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/52062/console), [test-azure_msft-win10_vs2019-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2022_clang/37337/console), [test-azure_msft-win10_vs2019-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2022_clang/37332/console), [test-azure_msft-win10_vs2019-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2022_clang/37326/console), [test-azure_msft-win11_vs2022-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2022_clang/37322/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69779/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69858/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/52062/console">Example</a></summary>

```
not ok 4811 sequential/test-worker-prof
  ---
  duration_ms: 1948.30700
  severity: fail
  exitcode: 1
  stack: |-
    files found in working directory before worker starts [ 'isolate-0x2a6ca000-7527-v8.log' ]
    parent prof file: isolate-0x2a6ca000-7527-v8.log
    parent posted 11225 messages
    files found in working directory before worker exits [
      'isolate-0x2a6ca000-7527-v8.log',
      'isolate-0x3ff68001000-7527-v8.log'
    ]
    worker prof file: isolate-0x3ff68001000-7527-v8.log
    
    worker ticks 9
    parent ticks 38
    node:internal/assert/utils:146
      throw error;
      ^
    
    AssertionError [ERR_ASSERTION]: worker ticks <= 10:
    tick,0x2c3e38a,19690,0,0x0,0,0x292ed9707d,0x2cb9a74,0x292ed96e93,0x292ed9482d
    tick,0x3ffa407e320,54350,0,0x0,1
    tick,0x2526f54,55733,0,0x0,2,0x3ff5c006bb6,0x3ff5c0064ee,0x292edb2df4,0x3ff5c006d14,0x3ff5c0064ee,0x292eda0ea6
    tick,0x26ef780,70325,0,0x0,2,0x3ff5c006bb6,0x3ff5c0064ee,0x292edbcea5,0x3ff5c006d14,0x3ff5c0064ee,0x292edbafb1,0x3ff5c00...
```
</details>

-------

| Reason | <code>parallel/test-quic-test-client</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/60277/](https://ci.nodejs.org/job/node-test-pull-request/69785/), [https://github.com/nodejs/node/pull/60178/](https://ci.nodejs.org/job/node-test-pull-request/69808/), [https://github.com/nodejs/node/pull/60111/](https://ci.nodejs.org/job/node-test-pull-request/69831/), [https://github.com/nodejs/node/pull/60331/](https://ci.nodejs.org/job/node-test-pull-request/69843/)) |
| Appeared | [vm-q9xx6](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67494/console), [vm-5d9v3](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67478/console), [vm-92kcy](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67452/console), [vm-qeafq](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67432/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69785/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69843/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67494/console">Example</a></summary>

```
not ok 2575 parallel/test-quic-test-client
  ---
  duration_ms: 1318.00200
  severity: fail
  exitcode: 1
  stack: |-
    /Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/out/Release/ngtcp2_test_client
    node:internal/modules/run_main:107
        triggerUncaughtException(
        ^
    
    AssertionError [ERR_ASSERTION]: Missing expected rejection.
        at process.processTicksAndRejections (node:internal/process/task_queues:103:5)
        at async file:///Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/test/parallel/test-quic-test-client.mjs:36:1 {
      generatedMessage: false,
      code: 'ERR_ASSERTION',
      actual: undefined,
      expected: { message: /Process exited with code 1 and signal null/ },
      operator: 'rejects',
      diff: 'simple'
    }
    
    Node.js v26.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-runner-watch-mode-kill-signal</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/60178/](https://ci.nodejs.org/job/node-test-pull-request/69777/), [https://github.com/nodejs/node/pull/60271/](https://ci.nodejs.org/job/node-test-pull-request/69789/), [https://github.com/nodejs/node/pull/60205/](https://ci.nodejs.org/job/node-test-pull-request/69790/), [https://github.com/nodejs/node/pull/60274/](https://ci.nodejs.org/job/node-test-pull-request/69818/)) |
| Appeared | [vm-e3hoc](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-arm64/67463/console), [vm-4tv35](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67437/console), [vm-oa16m](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67436/console), [vm-bmoqy](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67424/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69777/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69818/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-arm64/67463/console">Example</a></summary>

```
not ok 4776 parallel/test-runner-watch-mode-kill-signal
  ---
  duration_ms: 360060.83100
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-watch-mode-kill-signal-override</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/60298/](https://ci.nodejs.org/job/node-test-pull-request/69810/), [https://github.com/nodejs/node/pull/60139/](https://ci.nodejs.org/job/node-test-pull-request/69832/), [https://github.com/nodejs/node/pull/60318/](https://ci.nodejs.org/job/node-test-pull-request/69860/), [https://github.com/nodejs/node/pull/60372/](https://ci.nodejs.org/job/node-test-pull-request/69871/)) |
| Appeared | [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/52074/console), [test-azure-ubuntu2204_container-arm64-5](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/60808/console), [vm-usrrc](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67479/console), [test-azure_msft-win10_vs2019-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win10-COMPILED_BY-vs2022_clang/37328/console), [test-azure_msft-win11_vs2022-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-COMPILED_BY-vs2022_clang/37328/console), [test-rackspace-win2019_vs2019-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2019-COMPILED_BY-vs2022_clang/37328/console), [test-rackspace-win2022_vs2022-x64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2022-COMPILED_BY-vs2022_clang/37328/console), [test-azure_msft-win11_vs2022-arm64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/37328/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69810/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69871/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/52074/console">Example</a></summary>

```
not ok 3608 parallel/test-watch-mode-kill-signal-override
  ---
  duration_ms: 1131.91900
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/modules/run_main:107
        triggerUncaughtException(
        ^
    
    AssertionError [ERR_ASSERTION]: The input was expected to not match the regular expression /__SIGTERM received__/. Input:
    
    "Restarting '/home/iojs/node-tmp/.tmp.3607/kill-signal-for-watch.js'\n" +
      '__SIGINT received__\n' +
      '__SIGTERM received__\n'
    
        at file:///home/iojs/build/workspace/node-test-commit-linuxone/test/parallel/test-watch-mode-kill-signal-override.mjs:46:8
        at process.processTicksAndRejections (node:internal/process/task_queues:103:5) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: "Restarting '/home/iojs/node-tmp/.tmp.3607/kill-signal-for-watch.js'\n" +
        '__SIGINT received__\n' +
        '__SIGTERM received__\n',
      expected: /__SIGTERM received__/,
      operator: 'doesNotMatch',
      diff: 'simple...
```
</details>

-------

| Reason | <code>parallel/test-runner-watch-mode</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/60111/](https://ci.nodejs.org/job/node-test-pull-request/69831/), [https://github.com/nodejs/node/pull/60139/](https://ci.nodejs.org/job/node-test-pull-request/69832/), [https://github.com/nodejs/node/pull/59873/](https://ci.nodejs.org/job/node-test-pull-request/69835/)) |
| Appeared | [vm-gthqd](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67476/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69831/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69835/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67476/console">Example</a></summary>

```
not ok 2512 parallel/test-runner-watch-mode
  ---
  duration_ms: 12314.16600
  severity: fail
  exitcode: 1
  stack: |-
    TAP version 13
    # Subtest: test runner watch mode
        # Subtest: should run tests repeatedly
        ok 1 - should run tests repeatedly
          ---
          duration_ms: 2034.797083
          ...

```
</details>

-------

| Reason | <code>parallel/test-watch-mode-kill-signal-default</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/60298/](https://ci.nodejs.org/job/node-test-pull-request/69810/), [https://github.com/nodejs/node/pull/59734/](https://ci.nodejs.org/job/node-test-pull-request/69825/), [https://github.com/nodejs/node/pull/60330/](https://ci.nodejs.org/job/node-test-pull-request/69842/)) |
| Appeared | [vm-2xshg](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67493/console), [vm-v9dgt](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67470/console), [test-azure_msft-win10_vs2019-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win10-COMPILED_BY-vs2022_clang/37328/console), [test-azure_msft-win11_vs2022-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-COMPILED_BY-vs2022_clang/37328/console), [test-rackspace-win2019_vs2019-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2019-COMPILED_BY-vs2022_clang/37328/console), [test-rackspace-win2022_vs2022-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2022-COMPILED_BY-vs2022_clang/37328/console), [test-azure_msft-win11_vs2022-arm64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/37328/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69810/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69842/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67493/console">Example</a></summary>

```
not ok 4419 parallel/test-watch-mode-kill-signal-default
  ---
  duration_ms: 120032.20800
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>wpt/test-hr-time</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/60266/](https://ci.nodejs.org/job/node-test-pull-request/69787/), [https://github.com/nodejs/node/pull/60271/](https://ci.nodejs.org/job/node-test-pull-request/69803/), [https://github.com/nodejs/node/pull/60367/](https://ci.nodejs.org/job/node-test-pull-request/69856/)) |
| Appeared | [vm-lbl0c](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67506/console), [vm-5wwhg](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67447/console), [test-azure_msft-win11_vs2022-arm64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/37316/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69787/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69856/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67506/console">Example</a></summary>

```
not ok 4811 wpt/test-hr-time
  ---
  duration_ms: 2435.83600
  severity: fail
  exitcode: 1
  stack: |-
    [SKIPPED] idlharness-shadowrealm.window.js: ShadowRealm support is not enabled
    [SKIPPED] window-worker-timeOrigin.window.js: depends on URL.createObjectURL(blob)
    [PASS] self.performance.now() is a function that returns a number
    [PASS] self.performance.now() returns a positive number
    [PASS] self.performance.now() difference is not negative
    [PASS] Performance interface extends EventTarget.
    [PASS] self.performance.now() returns a positive number
    [PASS] self.performance.now() difference is not negative
    [PASS] idl_test validation
    [PASS] Partial interface mixin WindowOrWorkerGlobalScope: original interface mixin defined
    [PASS] Partial interface mixin WindowOrWorkerGlobalScope: member names are unique
    [PASS] Partial interface Window: member names are unique
    [PASS] Window includes GlobalEventHandlers: member names are unique
    [PASS] Window includes WindowEventH...
```
</details>

-------

| Reason | <code>client-proxy/test-https-proxy-request-invalid-char-in-url</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60178/](https://ci.nodejs.org/job/node-test-pull-request/69777/), [https://github.com/nodejs/node/pull/60266/](https://ci.nodejs.org/job/node-test-pull-request/69780/)) |
| Appeared | [vm-oa16m](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67427/console), [vm-bmoqy](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67424/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69777/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69780/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67427/console">Example</a></summary>

```
not ok 4378 client-proxy/test-https-proxy-request-invalid-char-in-url
  ---
  duration_ms: 533.88300
  severity: fail
  exitcode: 1
  stack: |-
    [Upstream server] responding to request for '/newline-in-host'
    [Upstream server] responding to request for '/carriage-return-in-host'
    [Upstream server] responding to request for '/carriage-return-in-port'
    [Upstream server] responding to request for '/crlf-in-host'
    [Proxy client] Received response from server for 'https://local\nhost:61468/newline-in-host': Response for '/newline-in-host'
    [Proxy client] #1 closed request for: 'https://local\nhost:61468/newline-in-host'
    [Proxy client] Received response from server for 'https://local\rhost:61468/carriage-return-in-host': Response for '/carriage-return-in-host'
    [Proxy client] #2 closed request for: 'https://local\rhost:61468/carriage-return-in-host'
    [Upstream server] responding to request for '/newline-in-port'
    [Proxy client] Received response from server for 'https://localhost:6\r1...
```
</details>

-------

