Failures in [node-test-pull-request/69896](https://ci.nodejs.org/job/node-test-pull-request/69896/) to [node-test-pull-request/69995](https://ci.nodejs.org/job/node-test-pull-request/69995/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2025-11-02.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2025-11-02 00:12 | 0       | 21      | 13       | 0       | 66      | 21.00%     |


### JSTest Failure

| Reason | <code>addons/stringbytes-external-exceed-max/test-stringbytes-external-exceed-max-by-1-hex</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 9 ([https://github.com/nodejs/node/pull/60387/](https://ci.nodejs.org/job/node-test-pull-request/69943/), [https://github.com/nodejs/node/pull/60380/](https://ci.nodejs.org/job/node-test-pull-request/69948/), [https://github.com/nodejs/node/pull/60488/](https://ci.nodejs.org/job/node-test-pull-request/69966/), [https://github.com/nodejs/node/pull/60427/](https://ci.nodejs.org/job/node-test-pull-request/69969/), [https://github.com/nodejs/node/pull/60480/](https://ci.nodejs.org/job/node-test-pull-request/69982/), [https://github.com/nodejs/node/pull/60492/](https://ci.nodejs.org/job/node-test-pull-request/69983/), [https://github.com/nodejs/node/pull/60524/](https://ci.nodejs.org/job/node-test-pull-request/69989/), [https://github.com/nodejs/node/pull/60235/](https://ci.nodejs.org/job/node-test-pull-request/69991/), [https://github.com/nodejs/node/pull/60497/](https://ci.nodejs.org/job/node-test-pull-request/69995/)) |
| Appeared | [test-ibm-aix72-ppc64_be-2](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59627/console), [test-osuosl-aix72-ppc64_be-4](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59623/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69943/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69995/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59627/console">Example</a></summary>

```
not ok 4629 addons/stringbytes-external-exceed-max/test-stringbytes-external-exceed-max-by-1-hex
  ---
  duration_ms: 120118.75600
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    1..0 # Skipped: intensive toString tests due to memory confinements
  ...

```
</details>

-------

| Reason | <code>addons/stringbytes-external-exceed-max/test-stringbytes-external-exceed-max</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 8 ([https://github.com/nodejs/node/pull/60388/](https://ci.nodejs.org/job/node-test-pull-request/69919/), [https://github.com/nodejs/node/pull/60447/](https://ci.nodejs.org/job/node-test-pull-request/69920/), [https://github.com/nodejs/node/pull/60427/](https://ci.nodejs.org/job/node-test-pull-request/69936/), [https://github.com/nodejs/node/pull/60380/](https://ci.nodejs.org/job/node-test-pull-request/69954/), [https://github.com/nodejs/node/pull/60503/](https://ci.nodejs.org/job/node-test-pull-request/69977/), [https://github.com/nodejs/node/pull/60492/](https://ci.nodejs.org/job/node-test-pull-request/69983/), [https://github.com/nodejs/node/pull/60524/](https://ci.nodejs.org/job/node-test-pull-request/69989/), [https://github.com/nodejs/node/pull/60501/](https://ci.nodejs.org/job/node-test-pull-request/69994/)) |
| Appeared | [test-osuosl-aix72-ppc64_be-4](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59626/console), [test-ibm-aix72-ppc64_be-2](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59585/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69919/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69994/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59626/console">Example</a></summary>

```
not ok 4624 addons/stringbytes-external-exceed-max/test-stringbytes-external-exceed-max
  ---
  duration_ms: 120184.68400
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    1..0 # Skipped: intensive toString tests due to memory confinements
  ...

```
</details>

-------

| Reason | <code>addons/stringbytes-external-exceed-max/test-stringbytes-external-exceed-max-by-1-utf8</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 8 ([https://github.com/nodejs/node/pull/60434/](https://ci.nodejs.org/job/node-test-pull-request/69907/), [https://github.com/nodejs/node/pull/60388/](https://ci.nodejs.org/job/node-test-pull-request/69924/), [https://github.com/nodejs/node/pull/60387/](https://ci.nodejs.org/job/node-test-pull-request/69940/), [https://github.com/nodejs/node/pull/60380/](https://ci.nodejs.org/job/node-test-pull-request/69948/), [https://github.com/nodejs/node/pull/60427/](https://ci.nodejs.org/job/node-test-pull-request/69949/), [https://github.com/nodejs/node/pull/54857/](https://ci.nodejs.org/job/node-test-pull-request/69957/), [https://github.com/nodejs/node/pull/60497/](https://ci.nodejs.org/job/node-test-pull-request/69961/), [https://github.com/nodejs/node/pull/60480/](https://ci.nodejs.org/job/node-test-pull-request/69982/)) |
| Appeared | [test-ibm-aix72-ppc64_be-2](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59615/console), [test-osuosl-aix72-ppc64_be-4](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59594/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69907/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69982/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59615/console">Example</a></summary>

```
not ok 4629 addons/stringbytes-external-exceed-max/test-stringbytes-external-exceed-max-by-1-utf8
  ---
  duration_ms: 120167.70000
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    1..0 # Skipped: intensive toString tests due to memory confinements
  ...

```
</details>

-------

| Reason | <code>parallel/test-perf-hooks-timerify</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 8 ([https://github.com/nodejs/node/pull/60370/](https://ci.nodejs.org/job/node-test-pull-request/69901/), [https://github.com/nodejs/node/pull/60388/](https://ci.nodejs.org/job/node-test-pull-request/69919/), [https://github.com/nodejs/node/pull/60496/](https://ci.nodejs.org/job/node-test-pull-request/69963/), [https://github.com/nodejs/node/pull/60351/](https://ci.nodejs.org/job/node-test-pull-request/69965/), [https://github.com/nodejs/node/pull/60491/](https://ci.nodejs.org/job/node-test-pull-request/69973/), [https://github.com/nodejs/node/pull/60503/](https://ci.nodejs.org/job/node-test-pull-request/69977/), [https://github.com/nodejs/node/pull/60466/](https://ci.nodejs.org/job/node-test-pull-request/69985/), [https://github.com/nodejs/node/pull/60259/](https://ci.nodejs.org/job/node-test-pull-request/69986/)) |
| Appeared | [test-ibm-rhel8-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/67204/console), [test-ibm-ubuntu2404_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_shared_x64/53385/console), [test-ibm-rhel8-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/67195/console), [test-ibm-ubuntu2404_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_shared_x64/53374/console), [test-ibm-ubuntu2404_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_openssl30_x64/53373/console), [test-ibm-alpine321_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/67184/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69901/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69986/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/67204/console">Example</a></summary>

```
not ok 2861 parallel/test-perf-hooks-timerify
  ---
  duration_ms: 195.84500
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/histogram:292
        validateInteger(val, 'val', 1);
        ^
    
    RangeError [ERR_OUT_OF_RANGE]: The value of "val" is out of range. It must be >= 1 && <= 9007199254740991. Received 0
        at RecordableHistogram.record (node:internal/histogram:292:5)
        at processComplete (node:internal/perf/timerify:40:15)
        at timerified m (node:internal/perf/timerify:87:5)
        at /home/iojs/build/workspace/node/test/parallel/test-perf-hooks-timerify.js:107:5
        at runNextTicks (node:internal/process/task_queues:64:5)
        at listOnTimeout (node:internal/timers:567:9)
        at process.processTimers (node:internal/timers:541:7) {
      code: 'ERR_OUT_OF_RANGE'
    }
    
    Node.js v26.0.0-pre
  ...

```
</details>

-------

| Reason | <code>addons/stringbytes-external-exceed-max/test-stringbytes-external-exceed-max-by-2</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/60388/](https://ci.nodejs.org/job/node-test-pull-request/69924/), [https://github.com/nodejs/node/pull/60427/](https://ci.nodejs.org/job/node-test-pull-request/69941/), [https://github.com/nodejs/node/pull/60380/](https://ci.nodejs.org/job/node-test-pull-request/69948/), [https://github.com/nodejs/node/pull/54857/](https://ci.nodejs.org/job/node-test-pull-request/69957/), [https://github.com/nodejs/node/pull/60492/](https://ci.nodejs.org/job/node-test-pull-request/69971/), [https://github.com/nodejs/node/pull/60480/](https://ci.nodejs.org/job/node-test-pull-request/69988/)) |
| Appeared | [test-ibm-aix72-ppc64_be-2](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59620/console), [test-osuosl-aix72-ppc64_be-4](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59591/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69924/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69988/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59620/console">Example</a></summary>

```
not ok 4630 addons/stringbytes-external-exceed-max/test-stringbytes-external-exceed-max-by-2
  ---
  duration_ms: 120141.10200
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    1..0 # Skipped: intensive toString tests due to memory confinements
  ...

```
</details>

-------

| Reason | <code>addons/stringbytes-external-exceed-max/test-stringbytes-external-exceed-max-by-1-base64</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/60388/](https://ci.nodejs.org/job/node-test-pull-request/69919/), [https://github.com/nodejs/node/pull/60387/](https://ci.nodejs.org/job/node-test-pull-request/69938/), [https://github.com/nodejs/node/pull/60497/](https://ci.nodejs.org/job/node-test-pull-request/69964/), [https://github.com/nodejs/node/pull/60492/](https://ci.nodejs.org/job/node-test-pull-request/69983/), [https://github.com/nodejs/node/pull/60524/](https://ci.nodejs.org/job/node-test-pull-request/69989/)) |
| Appeared | [test-osuosl-aix72-ppc64_be-4](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59621/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69919/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69989/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59621/console">Example</a></summary>

```
not ok 4589 addons/stringbytes-external-exceed-max/test-stringbytes-external-exceed-max-by-1-base64
  ---
  duration_ms: 120130.99800
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    1..0 # Skipped: intensive toString tests due to memory confinements
  ...

```
</details>

-------

| Reason | <code>parallel/test-watch-mode-files_watcher</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/60454/](https://ci.nodejs.org/job/node-test-pull-request/69921/), [https://github.com/nodejs/node/pull/60248/](https://ci.nodejs.org/job/node-test-pull-request/69927/), [https://github.com/nodejs/node/pull/60524/](https://ci.nodejs.org/job/node-test-pull-request/69989/), [https://github.com/nodejs/node/pull/60235/](https://ci.nodejs.org/job/node-test-pull-request/69991/), [https://github.com/nodejs/node/pull/60501/](https://ci.nodejs.org/job/node-test-pull-request/69994/)) |
| Appeared | [vm-al4wu](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-arm64/67642/console), [vm-foi6n](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67589/console), [test-rackspace-win2022_vs2022-x64-6](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2022-COMPILED_BY-vs2022_clang/37440/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69921/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69994/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-arm64/67642/console">Example</a></summary>

```
not ok 4842 parallel/test-watch-mode-files_watcher
  ---
  duration_ms: 360008.45900
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>sequential/test-worker-prof</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/60434/](https://ci.nodejs.org/job/node-test-pull-request/69905/), [https://github.com/nodejs/node/pull/60422/](https://ci.nodejs.org/job/node-test-pull-request/69913/), [https://github.com/nodejs/node/pull/60388/](https://ci.nodejs.org/job/node-test-pull-request/69919/), [https://github.com/nodejs/node/pull/60387/](https://ci.nodejs.org/job/node-test-pull-request/69938/), [https://github.com/nodejs/node/pull/60479/](https://ci.nodejs.org/job/node-test-pull-request/69951/)) |
| Appeared | [test-azure_msft-win10_vs2019-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win10-COMPILED_BY-vs2022_clang/37460/console), [test-azure_msft-win10_vs2019-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win10-COMPILED_BY-vs2022_clang/37451/console), [test-azure_msft-win10_vs2019-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2022_clang/37433/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69905/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69951/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win10-COMPILED_BY-vs2022_clang/37460/console">Example</a></summary>

```
not ok 1167 sequential/test-worker-prof
  ---
  duration_ms: 2501.45500
  severity: fail
  exitcode: 1
  stack: |-
    files found in working directory before worker starts [ 'isolate-000002CF0EFDE000-5360-v8.log' ]
    parent prof file: isolate-000002CF0EFDE000-5360-v8.log
    parent posted 35670 messages
    files found in working directory before worker exits [
      'isolate-000002CF0EFDE000-5360-v8.log',
      'isolate-000002CF284F8000-5360-v8.log'
    ]
    worker prof file: isolate-000002CF284F8000-5360-v8.log
    
    worker ticks 10
    parent ticks 20
    node:internal/assert/utils:146
      throw error;
      ^
    
    AssertionError [ERR_ASSERTION]: worker ticks <= 10:
    tick,0x7ff646b470ab,42863,0,0x0,0,0x7ff6469ed440,0x2cf68fc28d8,0x2124a68a219,0x2124a689927,0x2cf68f55567,0x2124a686654
    tick,0x7ff646f91f78,138867,0,0x0,2,0x2cf4914297e,0x2cf49142607,0x2124a6a73fb,0x2cf49142a4f,0x2cf49142607,0x2124a6930c3
    tick,0x7ff646a7dcdd,186875,0,0x0,2,0x2cf4914297e,0x2cf49142607,0x2124a6b4d5c,0x2124...
```
</details>

-------

| Reason | <code>es-module/test-esm-wasm</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/60434/](https://ci.nodejs.org/job/node-test-pull-request/69905/), [https://github.com/nodejs/node/pull/60429/](https://ci.nodejs.org/job/node-test-pull-request/69908/), [https://github.com/nodejs/node/pull/60422/](https://ci.nodejs.org/job/node-test-pull-request/69913/), [https://github.com/nodejs/node/pull/60388/](https://ci.nodejs.org/job/node-test-pull-request/69919/)) |
| Appeared | [test-azure_msft-win10_vs2019-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2019/37423/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69905/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69919/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2019/37423/console">Example</a></summary>

```
not ok 58 es-module/test-esm-wasm
  ---
  duration_ms: 1008.00200
  severity: fail
  exitcode: 1
  stack: |-
    TAP version 13
    # Subtest: ESM: WASM modules
        # Subtest: should load exports
        ok 1 - should load exports
          ---
          duration_ms: 251.6482
          ...

```
</details>

-------

| Reason | <code>parallel/test-quic-test-client</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/60447/](https://ci.nodejs.org/job/node-test-pull-request/69920/), [https://github.com/nodejs/node/pull/60480/](https://ci.nodejs.org/job/node-test-pull-request/69945/), [https://github.com/nodejs/node/pull/60235/](https://ci.nodejs.org/job/node-test-pull-request/69991/), [https://github.com/nodejs/node/pull/60501/](https://ci.nodejs.org/job/node-test-pull-request/69994/)) |
| Appeared | [vm-f3wy2](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67647/console), [vm-p67pn](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67644/console), [vm-80086](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67600/console), [vm-mu2vx](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67581/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69920/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69994/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67647/console">Example</a></summary>

```
not ok 2580 parallel/test-quic-test-client
  ---
  duration_ms: 1285.80100
  severity: fail
  exitcode: 1
  stack: |-
    /Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/out/Release/ngtcp2_test_client
    node:internal/modules/run_main:107
        triggerUncaughtException(
        ^
    
    AssertionError [ERR_ASSERTION]: Missing expected rejection.
        at process.processTicksAndRejections (node:internal/process/task_queues:103:5)
        at async file:///Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/test/parallel/test-quic-test-client.mjs:36:1 {
      generatedMessage: false,
      code: 'ERR_ASSERTION',
      actual: undefined,
      expected: { message: /Process exited with code 1 and signal null/ },
      operator: 'rejects',
      diff: 'simple'
    }
    
    Node.js v26.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-watch-mode-kill-signal-override</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/60480/](https://ci.nodejs.org/job/node-test-pull-request/69945/), [https://github.com/nodejs/node/pull/60345/](https://ci.nodejs.org/job/node-test-pull-request/69953/), [https://github.com/nodejs/node/pull/60496/](https://ci.nodejs.org/job/node-test-pull-request/69960/), [https://github.com/nodejs/node/pull/60259/](https://ci.nodejs.org/job/node-test-pull-request/69978/)) |
| Appeared | [test-azure-ubuntu2204_container-arm64-5](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/60910/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69945/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69978/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/60910/console">Example</a></summary>

```
not ok 3855 parallel/test-watch-mode-kill-signal-override
  ---
  duration_ms: 1208.12100
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/modules/run_main:107
        triggerUncaughtException(
        ^
    
    AssertionError [ERR_ASSERTION]: The input was expected to not match the regular expression /__SIGTERM received__/. Input:
    
    "Restarting '/home/iojs/node-tmp/.tmp.3857/kill-signal-for-watch.js'\n" +
      '__SIGINT received__\n' +
      '__SIGTERM received__\n'
    
        at file:///home/iojs/build/workspace/node-test-commit-arm/test/parallel/test-watch-mode-kill-signal-override.mjs:46:8
        at process.processTicksAndRejections (node:internal/process/task_queues:103:5) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: "Restarting '/home/iojs/node-tmp/.tmp.3857/kill-signal-for-watch.js'\n" +
        '__SIGINT received__\n' +
        '__SIGTERM received__\n',
      expected: /__SIGTERM received__/,
      operator: 'doesNotMatch',
      diff: 'simple'
   ...
```
</details>

-------

| Reason | <code>addons/stringbytes-external-exceed-max/test-stringbytes-external-exceed-max-by-1-ascii</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/60380/](https://ci.nodejs.org/job/node-test-pull-request/69948/), [https://github.com/nodejs/node/pull/60480/](https://ci.nodejs.org/job/node-test-pull-request/69982/), [https://github.com/nodejs/node/pull/60483/](https://ci.nodejs.org/job/node-test-pull-request/69992/)) |
| Appeared | [test-osuosl-aix72-ppc64_be-4](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59624/console), [test-ibm-aix72-ppc64_be-2](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59615/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69948/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69992/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59624/console">Example</a></summary>

```
not ok 4625 addons/stringbytes-external-exceed-max/test-stringbytes-external-exceed-max-by-1-ascii
  ---
  duration_ms: 120144.25200
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    1..0 # Skipped: intensive toString tests due to memory confinements
  ...

```
</details>

-------

| Reason | <code>addons/stringbytes-external-exceed-max/test-stringbytes-external-exceed-max-by-1-binary</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/60434/](https://ci.nodejs.org/job/node-test-pull-request/69907/), [https://github.com/nodejs/node/pull/60351/](https://ci.nodejs.org/job/node-test-pull-request/69922/), [https://github.com/nodejs/node/pull/60387/](https://ci.nodejs.org/job/node-test-pull-request/69942/)) |
| Appeared | [test-osuosl-aix72-ppc64_be-4](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59572/console), [test-ibm-aix72-ppc64_be-2](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59558/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69907/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69942/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59572/console">Example</a></summary>

```
not ok 4620 addons/stringbytes-external-exceed-max/test-stringbytes-external-exceed-max-by-1-binary
  ---
  duration_ms: 120134.19400
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    1..0 # Skipped: intensive toString tests due to memory confinements
  ...

```
</details>

-------

| Reason | <code>wpt/test-hr-time</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/60496/](https://ci.nodejs.org/job/node-test-pull-request/69960/), [https://github.com/nodejs/node/pull/60480/](https://ci.nodejs.org/job/node-test-pull-request/69988/), [https://github.com/nodejs/node/pull/60524/](https://ci.nodejs.org/job/node-test-pull-request/69989/)) |
| Appeared | [vm-zhanz](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67641/console), [vm-p6sa0](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67612/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69960/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69989/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67641/console">Example</a></summary>

```
not ok 4905 wpt/test-hr-time
  ---
  duration_ms: 2400.61200
  severity: fail
  exitcode: 1
  stack: |-
    [SKIPPED] idlharness-shadowrealm.window.js: ShadowRealm support is not enabled
    [SKIPPED] window-worker-timeOrigin.window.js: depends on URL.createObjectURL(blob)
    [PASS] self.performance.now() is a function that returns a number
    [PASS] self.performance.now() returns a positive number
    [PASS] self.performance.now() difference is not negative
    [PASS] Performance interface extends EventTarget.
    [PASS] self.performance.now() returns a positive number
    [PASS] self.performance.now() difference is not negative
    [PASS] idl_test validation
    [PASS] Partial interface mixin WindowOrWorkerGlobalScope: original interface mixin defined
    [PASS] Partial interface mixin WindowOrWorkerGlobalScope: member names are unique
    [PASS] Partial interface Window: member names are unique
    [PASS] Window includes GlobalEventHandlers: member names are unique
    [PASS] Window includes WindowEventH...
```
</details>

-------

| Reason | <code>parallel/test-watch-mode-kill-signal-default</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60413/](https://ci.nodejs.org/job/node-test-pull-request/69911/), [https://github.com/nodejs/node/pull/60491/](https://ci.nodejs.org/job/node-test-pull-request/69973/)) |
| Appeared | [vm-u2x6j](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67624/console), [vm-nbcl4](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67570/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69911/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69973/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67624/console">Example</a></summary>

```
not ok 4148 parallel/test-watch-mode-kill-signal-default
  ---
  duration_ms: 120060.65800
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------


### Jenkins Failure

| Reason | <code>Cannot run program "/bin/sh" (in directory "/home/iojs/build/workspace/node"): error=0, Failed to exec spawn helper: pid: 938203, exit value: 1</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/60370/](https://ci.nodejs.org/job/node-test-pull-request/69901/), [https://github.com/nodejs/node/pull/59982/](https://ci.nodejs.org/job/node-test-pull-request/69903/), [https://github.com/nodejs/node/pull/60437/](https://ci.nodejs.org/job/node-test-pull-request/69906/), [https://github.com/nodejs/node/pull/60422/](https://ci.nodejs.org/job/node-test-pull-request/69913/), [https://github.com/nodejs/node/pull/60388/](https://ci.nodejs.org/job/node-test-pull-request/69919/)) |
| Appeared | [test-rackspace-debian11-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian11-x64/67126/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69901/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69919/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian11-x64/67126/console">Example</a></summary>

```
java.io.IOException: Cannot run program "/bin/sh" (in directory "/home/iojs/build/workspace/node"): error=0, Failed to exec spawn helper: pid: 938203, exit value: 1
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at Jenkins v2.528.1//hudson.Proc$LocalProc.<init>(Proc.java:252)
	at Jenkins v2.528.1//hudson.Proc$LocalProc.<init>(Proc.java:221)
	at Jenkins v2.528.1//hudson.Launcher$LocalLauncher.launch(Launcher.java:995)
```
</details>

-------

| Reason | <code>Cannot run program "/bin/sh" (in directory "/home/iojs/build/workspace/node"): error=0, Failed to exec spawn helper: pid: 957237, exit value: 1</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/60422/](https://ci.nodejs.org/job/node-test-pull-request/69932/), [https://github.com/nodejs/node/pull/59982/](https://ci.nodejs.org/job/node-test-pull-request/69933/), [https://github.com/nodejs/node/pull/60443/](https://ci.nodejs.org/job/node-test-pull-request/69935/), [https://github.com/nodejs/node/pull/60464/](https://ci.nodejs.org/job/node-test-pull-request/69939/)) |
| Appeared | [test-rackspace-debian11-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian11-x64/67149/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69932/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69939/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian11-x64/67149/console">Example</a></summary>

```
java.io.IOException: Cannot run program "/bin/sh" (in directory "/home/iojs/build/workspace/node"): error=0, Failed to exec spawn helper: pid: 957237, exit value: 1
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at Jenkins v2.528.1//hudson.Proc$LocalProc.<init>(Proc.java:252)
	at Jenkins v2.528.1//hudson.Proc$LocalProc.<init>(Proc.java:221)
	at Jenkins v2.528.1//hudson.Launcher$LocalLauncher.launch(Launcher.java:995)
```
</details>

-------


### Build Failure


### undefined

