Failures in [node-test-pull-request/69505](https://ci.nodejs.org/job/node-test-pull-request/69505/) to [node-test-pull-request/69599](https://ci.nodejs.org/job/node-test-pull-request/69599/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2025-10-08.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2025-10-08 00:11 | 6       | 1       | 26       | 4       | 63      | 1.11%      |


### Jenkins Failure

| Reason | <code>Build timed out (after 30 minutes). Marking the build as failed.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/59805/](https://ci.nodejs.org/job/node-test-pull-request/69517/), [https://github.com/nodejs/node/pull/60040/](https://ci.nodejs.org/job/node-test-pull-request/69533/), [https://github.com/nodejs/node/pull/59952/](https://ci.nodejs.org/job/node-test-pull-request/69540/), [https://github.com/nodejs/node/pull/60060/](https://ci.nodejs.org/job/node-test-pull-request/69545/), [https://github.com/nodejs/node/pull/60064/](https://ci.nodejs.org/job/node-test-pull-request/69571/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/37129/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69517/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69571/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/37129/console">Example</a></summary>

```
Build timed out (after 30 minutes). Marking the build as failed.
```
</details>

-------

| Reason | <code>Unexpected termination of the channel</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/60000/](https://ci.nodejs.org/job/node-test-pull-request/69523/), [https://github.com/nodejs/node/pull/59952/](https://ci.nodejs.org/job/node-test-pull-request/69526/), [https://github.com/nodejs/node/pull/60060/](https://ci.nodejs.org/job/node-test-pull-request/69527/), [https://github.com/nodejs/node/pull/60115/](https://ci.nodejs.org/job/node-test-pull-request/69528/)) |
| Appeared | [vm-7unys](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-arm64/67123/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69523/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69528/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-arm64/67123/console">Example</a></summary>

```
java.io.IOException: Unexpected termination of the channel
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:80)
Caused: java.io.IOException: Backing channel 'vm-7unys' is disconnected.
	at hudson.remoting.RemoteInvocationHandler.channelOrFail(RemoteInvocationHandler.java:227)
	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:306)
	at jdk.proxy2/jdk.proxy2.$Proxy218.isAlive(Unknown Source)
```
</details>

-------

| Reason | <code>Build timed out (after 60 minutes). Marking the build as failed.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60059/](https://ci.nodejs.org/job/node-test-pull-request/69556/), [https://github.com/nodejs/node/pull/60136/](https://ci.nodejs.org/job/node-test-pull-request/69597/)) |
| Appeared | [test-ibm-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/53067/console), [test-ibm-ubuntu2404_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_icu_x64/53067/console), [test-ibm-ubuntu2404_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_openssl30_x64/53067/console), [test-ibm-ubuntu2404_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_openssl32_x64/53067/console), [test-ibm-ubuntu2404_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_openssl35_x64/53067/console), [test-ibm-ubuntu2404_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_shared_x64/53067/console), [vm-wpeon](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-arm64/67157/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69556/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69597/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/53067/console">Example</a></summary>

```
Build timed out (after 60 minutes). Marking the build as failed.
```
</details>

-------


### Git Failure


### Build Failure

| Reason | <code>fatal: detected dubious ownership in repository at 'C:/workspace/node-test-binary-windows-js-suites/build'</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/60103/](https://ci.nodejs.org/job/node-test-pull-request/69514/), [https://github.com/nodejs/node/pull/59805/](https://ci.nodejs.org/job/node-test-pull-request/69517/), [https://github.com/nodejs/node/pull/60040/](https://ci.nodejs.org/job/node-test-pull-request/69533/), [https://github.com/nodejs/node/pull/59952/](https://ci.nodejs.org/job/node-test-pull-request/69540/), [https://github.com/nodejs/node/pull/60060/](https://ci.nodejs.org/job/node-test-pull-request/69545/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-COMPILED_BY-vs2019/37085/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69514/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69545/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-COMPILED_BY-vs2019/37085/console">Example</a></summary>

```
fatal: detected dubious ownership in repository at 'C:/workspace/node-test-binary-windows-js-suites/build'
```
</details>

-------

| Reason | <code>Failed to trigger node-test-commit</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/60060/](https://ci.nodejs.org/job/node-test-pull-request/69543/), [https://github.com/nodejs/node/pull/59952/](https://ci.nodejs.org/job/node-test-pull-request/69544/), [https://github.com/nodejs/node/pull/60132/](https://ci.nodejs.org/job/node-test-pull-request/69587/)) |
| Appeared | [test-mnx-ubuntu2204-x64-1](https://ci.nodejs.org/job/node-test-pull-request/69587/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69543/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69587/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-pull-request/69587/console">Example</a></summary>

```
Failed to trigger node-test-commit
```
</details>

-------

| Reason | <code>ERROR: Step �Publish JUnit test result report� failed: No test report files were found. Configuration error?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59952/](https://ci.nodejs.org/job/node-test-pull-request/69512/), [https://github.com/nodejs/node/pull/59805/](https://ci.nodejs.org/job/node-test-pull-request/69517/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-COMPILED_BY-vs2022_clang/37090/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69512/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69517/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-COMPILED_BY-vs2022_clang/37090/console">Example</a></summary>

```
ERROR: Step �Publish JUnit test result report� failed: No test report files were found. Configuration error?
Collecting metadata...
Metadata collection done.
Notifying upstream projects of job completion
Finished: FAILURE
```
</details>

-------


### JSTest Failure

| Reason | <code>parallel/test-without-async-context-frame</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 14 ([https://github.com/nodejs/node/pull/60115/](https://ci.nodejs.org/job/node-test-pull-request/69528/), [https://github.com/nodejs/node/pull/60033/](https://ci.nodejs.org/job/node-test-pull-request/69530/), [https://github.com/nodejs/node/pull/59805/](https://ci.nodejs.org/job/node-test-pull-request/69537/), [https://github.com/nodejs/node/pull/60060/](https://ci.nodejs.org/job/node-test-pull-request/69545/), [https://github.com/nodejs/node/pull/60036/](https://ci.nodejs.org/job/node-test-pull-request/69550/), [https://github.com/nodejs/node/pull/59952/](https://ci.nodejs.org/job/node-test-pull-request/69553/), [https://github.com/nodejs/node/pull/60123/](https://ci.nodejs.org/job/node-test-pull-request/69569/), [https://github.com/nodejs/node/pull/60059/](https://ci.nodejs.org/job/node-test-pull-request/69570/), [https://github.com/nodejs/node/pull/60008/](https://ci.nodejs.org/job/node-test-pull-request/69577/), [https://github.com/nodejs/node/pull/60061/](https://ci.nodejs.org/job/node-test-pull-request/69593/), [https://github.com/nodejs/node/pull/60144/](https://ci.nodejs.org/job/node-test-pull-request/69595/), [https://github.com/nodejs/node/pull/60098/](https://ci.nodejs.org/job/node-test-pull-request/69596/), [https://github.com/nodejs/node/pull/60148/](https://ci.nodejs.org/job/node-test-pull-request/69598/), [https://github.com/nodejs/node/pull/59889/](https://ci.nodejs.org/job/node-test-pull-request/69599/)) |
| Appeared | [vm-532du](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67207/console), [test-digitalocean-ubuntu2404_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_shared_x64/53068/console), [test-digitalocean-ubuntu2404_sharedlibs_container-x64-9](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_shared_x64/53066/console), [test-digitalocean-ubuntu2404_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_shared_x64/53065/console), [vm-2on5c](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67201/console), [vm-mqg3w](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67181/console), [vm-tklkv](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67173/console), [vm-1i229](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67172/console), [vm-66gbr](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67154/console), [vm-qbevq](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67144/console), [vm-ujjv9](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67143/console), [vm-2ri4d](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67136/console), [vm-y9ecw](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67128/console), [vm-2qmvu](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67127/console), [vm-8yw85](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67121/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69528/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69599/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67207/console">Example</a></summary>

```
not ok 4167 parallel/test-without-async-context-frame
  ---
  duration_ms: 120243.89300
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-runner-run-watch</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 12 ([https://github.com/nodejs/node/pull/60024/](https://ci.nodejs.org/job/node-test-pull-request/69506/), [https://github.com/nodejs/node/pull/60103/](https://ci.nodejs.org/job/node-test-pull-request/69507/), [https://github.com/nodejs/node/pull/59877/](https://ci.nodejs.org/job/node-test-pull-request/69518/), [https://github.com/nodejs/node/pull/60033/](https://ci.nodejs.org/job/node-test-pull-request/69530/), [https://github.com/nodejs/node/pull/60040/](https://ci.nodejs.org/job/node-test-pull-request/69533/), [https://github.com/nodejs/node/pull/59805/](https://ci.nodejs.org/job/node-test-pull-request/69537/), [https://github.com/nodejs/node/pull/60060/](https://ci.nodejs.org/job/node-test-pull-request/69554/), [https://github.com/nodejs/node/pull/60059/](https://ci.nodejs.org/job/node-test-pull-request/69556/), [https://github.com/nodejs/node/pull/59952/](https://ci.nodejs.org/job/node-test-pull-request/69558/), [https://github.com/nodejs/node/pull/60061/](https://ci.nodejs.org/job/node-test-pull-request/69563/), [https://github.com/nodejs/node/pull/60123/](https://ci.nodejs.org/job/node-test-pull-request/69569/), [https://github.com/nodejs/node/pull/60064/](https://ci.nodejs.org/job/node-test-pull-request/69571/)) |
| Appeared | [vm-jyntm](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67174/console), [vm-1i229](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67172/console), [vm-3jyui](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67164/console), [vm-qe5tw](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67159/console), [vm-66gbr](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67157/console), [vm-qbevq](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67144/console), [vm-asmhb](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67139/console), [vm-fca2x](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67138/console), [vm-2ri4d](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67136/console), [vm-cl25d](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67132/console), [vm-2qmvu](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67127/console), [vm-i26vj](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67118/console), [vm-8cc4z](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67105/console), [vm-fl5w8](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67103/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69506/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69571/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67174/console">Example</a></summary>

```
not ok 2802 parallel/test-runner-run-watch
  ---
  duration_ms: 27535.14200
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'should run with different cwd while in watch mode and isolation "none"'
    Location: test/parallel/test-runner-run-watch.mjs:358:5
    AssertionError [ERR_ASSERTION]: function should not have been called at file:///Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/test/parallel/test-runner-run-watch.mjs:373
    called with arguments: [Object: null prototype] {
      name: '<anonymous>',
      nesting: 0,
      testNumber: 1,
      details: [Object: null prototype] {
        duration_ms: 210.990362,
        type: 'test',
        error: [Error: test failed] {
          code: 'ERR_TEST_FAILURE',
          failureType: 'testCodeFailure',
          cause: 'test failed',
          exitCode: null,
          signal: 'SIGTERM'
        }
      },
      line: 1,
      column: 1,
      file: '/Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/<anonymo...
```
</details>

-------

| Reason | <code>parallel/test-runner-watch-mode-kill-signal</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 7 ([https://github.com/nodejs/node/pull/59952/](https://ci.nodejs.org/job/node-test-pull-request/69510/), [https://github.com/nodejs/node/pull/60115/](https://ci.nodejs.org/job/node-test-pull-request/69521/), [https://github.com/nodejs/node/pull/59805/](https://ci.nodejs.org/job/node-test-pull-request/69537/), [https://github.com/nodejs/node/pull/60060/](https://ci.nodejs.org/job/node-test-pull-request/69541/), [https://github.com/nodejs/node/pull/60059/](https://ci.nodejs.org/job/node-test-pull-request/69549/), [https://github.com/nodejs/node/pull/60123/](https://ci.nodejs.org/job/node-test-pull-request/69564/), [https://github.com/nodejs/node/pull/60132/](https://ci.nodejs.org/job/node-test-pull-request/69584/)) |
| Appeared | [vm-zav92](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67190/console), [test-azure-ubuntu2204_container-arm64-5](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/60617/console), [vm-asmhb](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67139/console), [vm-2ri4d](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67136/console), [test-azure-ubuntu2204_container-arm64-6](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/20578/console), [vm-5sqy5](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67107/console), [vm-xw0o3](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67106/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69510/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69584/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67190/console">Example</a></summary>

```
not ok 3479 parallel/test-runner-watch-mode-kill-signal
  ---
  duration_ms: 120035.61400
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>sequential/test-worker-prof</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/59968/](https://ci.nodejs.org/job/node-test-pull-request/69567/), [https://github.com/nodejs/node/pull/60125/](https://ci.nodejs.org/job/node-test-pull-request/69579/), [https://github.com/nodejs/node/pull/60061/](https://ci.nodejs.org/job/node-test-pull-request/69593/), [https://github.com/nodejs/node/pull/60098/](https://ci.nodejs.org/job/node-test-pull-request/69596/), [https://github.com/nodejs/node/pull/60148/](https://ci.nodejs.org/job/node-test-pull-request/69598/), [https://github.com/nodejs/node/pull/59889/](https://ci.nodejs.org/job/node-test-pull-request/69599/)) |
| Appeared | [test-azure_msft-win10_vs2019-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win10-COMPILED_BY-vs2022_clang/37153/console), [test-azure_msft-win10_vs2019-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win10-COMPILED_BY-vs2022_clang/37154/console), [test-azure_msft-win10_vs2019-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2022_clang/37146/console), [test-azure_msft-win11_vs2022-arm64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/37130/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69567/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69599/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win10-COMPILED_BY-vs2022_clang/37153/console">Example</a></summary>

```
not ok 1143 sequential/test-worker-prof
  ---
  duration_ms: 2400.37800
  severity: fail
  exitcode: 1
  stack: |-
    files found in working directory before worker starts [ 'isolate-00000280C3783000-9960-v8.log' ]
    parent prof file: isolate-00000280C3783000-9960-v8.log
    parent posted 46057 messages
    files found in working directory before worker exits [
      'isolate-00000280C3783000-9960-v8.log',
      'isolate-00000280DCD33000-9960-v8.log'
    ]
    worker prof file: isolate-00000280DCD33000-9960-v8.log
    
    worker ticks 15
    parent ticks 16
    node:internal/assert/utils:77
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: worker ticks <= 15:
    tick,0x7ff62999c290,53145,0,0x0,5,0xc89a48c490,0xc89a48c337,0xc89a492679
    tick,0x7ff62994f680,194652,0,0x0,2,0x2808004447e,0x28080044107,0x2bf49e53b2e,0x2bf49e53a15,0x2bf49e50b7d,0x2bf49e5017c,0xc89a48b07c
    tick,0x7ff98937b748,256622,0,0x0,0,0x28080087b33,0x28080085e19,0xc89a48b07c
    tick,0x7ff9893f0944,272698,0,0x0,0,...
```
</details>

-------

| Reason | <code>client-proxy/test-https-proxy-request-invalid-char-in-url</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/60103/](https://ci.nodejs.org/job/node-test-pull-request/69507/), [https://github.com/nodejs/node/pull/59805/](https://ci.nodejs.org/job/node-test-pull-request/69537/), [https://github.com/nodejs/node/pull/60060/](https://ci.nodejs.org/job/node-test-pull-request/69554/), [https://github.com/nodejs/node/pull/60123/](https://ci.nodejs.org/job/node-test-pull-request/69569/), [https://github.com/nodejs/node/pull/59889/](https://ci.nodejs.org/job/node-test-pull-request/69599/)) |
| Appeared | [vm-532du](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67207/console), [vm-1i229](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67172/console), [vm-qe5tw](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67155/console), [vm-2ri4d](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67136/console), [vm-fl5w8](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67103/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69507/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69599/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67207/console">Example</a></summary>

```
not ok 4374 client-proxy/test-https-proxy-request-invalid-char-in-url
  ---
  duration_ms: 841.19700
  severity: fail
  exitcode: 1
  stack: |-
    [Upstream server] responding to request for '/carriage-return-in-host'
    [Proxy client] Received response from server for 'https://local\rhost:55418/carriage-return-in-host': Response for '/carriage-return-in-host'
    [Proxy client] #1 closed request for: 'https://local\rhost:55418/carriage-return-in-host'
    [Upstream server] responding to request for '/carriage-return-in-port'
    [Upstream server] responding to request for '/crlf-in-host'
    [Upstream server] responding to request for '/newline-in-host'
    [Upstream server] responding to request for '/crlf-in-port'
    [Proxy client] Received response from server for 'https://localhost:5\r5418/carriage-return-in-port': Response for '/carriage-return-in-port'
    [Proxy client] #2 closed request for: 'https://localhost:5\r5418/carriage-return-in-port'
    [Proxy client] Received response from server for 'h...
```
</details>

-------

| Reason | <code>parallel/test-runner-run</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/59805/](https://ci.nodejs.org/job/node-test-pull-request/69517/), [https://github.com/nodejs/node/pull/60040/](https://ci.nodejs.org/job/node-test-pull-request/69533/), [https://github.com/nodejs/node/pull/59952/](https://ci.nodejs.org/job/node-test-pull-request/69540/), [https://github.com/nodejs/node/pull/60060/](https://ci.nodejs.org/job/node-test-pull-request/69545/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-COMPILED_BY-vs2019/37085/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69517/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69545/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-COMPILED_BY-vs2019/37085/console">Example</a></summary>

```
not ok 691 parallel/test-runner-run
  ---
  duration_ms: 4080.99800
  severity: fail
  exitcode: 1
  stack: |-
    TAP version 13
    # Subtest: require('node:test').run
        # Subtest: should run with no tests
        ok 1 - should run with no tests
          ---
          duration_ms: 291.918
          ...

```
</details>

-------

| Reason | <code>sequential/test-perf-hooks</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/60115/](https://ci.nodejs.org/job/node-test-pull-request/69528/), [https://github.com/nodejs/node/pull/60059/](https://ci.nodejs.org/job/node-test-pull-request/69556/), [https://github.com/nodejs/node/pull/60061/](https://ci.nodejs.org/job/node-test-pull-request/69578/), [https://github.com/nodejs/node/pull/60144/](https://ci.nodejs.org/job/node-test-pull-request/69595/)) |
| Appeared | [test-digitalocean-ubuntu2404_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_openssl30_x64/53065/console), [vm-zqytd](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67183/console), [vm-66gbr](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67157/console), [vm-y9ecw](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67128/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69528/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69595/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_openssl30_x64/53065/console">Example</a></summary>

```
not ok 4808 sequential/test-perf-hooks
  ---
  duration_ms: 243.38900
  severity: fail
  exitcode: 1
  stack: |-
    check initial nodeTiming
    {
      "name": "node",
      "entryType": "node",
      "startTime": 0,
      "duration": 133.502016,
      "nodeStart": 0.8518930077552795,
      "v8Start": 14.677429020404816,
      "environment": 68.63174200057983,
      "loopStart": -1,
      "loopExit": -1,
      "bootstrapComplete": 90.50679802894592,
      "idleTime": 0,
      "uvMetricsInfo": {
        "loopCount": 0,
        "events": 0,
        "eventsWaiting": 0
      }
    }
    node:internal/assert/utils:77
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: now (147.868023) - timing.duration (133.502016) = 14.366006999999996 >= 10
        at checkNodeTiming (/home/iojs/build/workspace/node-test-commit-linux-containered/test/sequential/test-perf-hooks.js:61:3)
        at Object.<anonymous> (/home/iojs/build/workspace/node-test-commit-linux-containered/test/sequential/test-perf-hooks.j...
```
</details>

-------

| Reason | <code>parallel/test-http2-close-while-writing</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60024/](https://ci.nodejs.org/job/node-test-pull-request/69506/), [https://github.com/nodejs/node/pull/59952/](https://ci.nodejs.org/job/node-test-pull-request/69540/)) |
| Appeared | [vm-fca2x](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67138/console), [vm-fl5w8](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67102/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69506/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69540/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67138/console">Example</a></summary>

```
not ok 2363 parallel/test-http2-close-while-writing
  ---
  duration_ms: 120086.78500
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-quic-test-client</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59877/](https://ci.nodejs.org/job/node-test-pull-request/69520/), [https://github.com/nodejs/node/pull/59952/](https://ci.nodejs.org/job/node-test-pull-request/69560/)) |
| Appeared | [vm-m34hc](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67161/console), [vm-of2j2](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67126/console), [vm-hn1w7](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67120/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69520/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69560/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67161/console">Example</a></summary>

```
not ok 2567 parallel/test-quic-test-client
  ---
  duration_ms: 1531.02300
  severity: fail
  exitcode: 1
  stack: |-
    /Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/out/Release/ngtcp2_test_client
    node:internal/modules/run_main:107
        triggerUncaughtException(
        ^
    
    AssertionError [ERR_ASSERTION]: Missing expected rejection.
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
        at async file:///Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/test/parallel/test-quic-test-client.mjs:31:1 {
      generatedMessage: false,
      code: 'ERR_ASSERTION',
      actual: undefined,
      expected: { message: /Process exited with code 1 and signal null/ },
      operator: 'rejects',
      diff: 'simple'
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-worker-nearheaplimit-deadlock</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60060/](https://ci.nodejs.org/job/node-test-pull-request/69539/), [https://github.com/nodejs/node/pull/59968/](https://ci.nodejs.org/job/node-test-pull-request/69565/)) |
| Appeared | [test-ibm-rhel8-s390x-4](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/51843/console), [test-osuosl-rhel8-ppc64_le-2](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel8-ppc64le/61023/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69539/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69565/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/51843/console">Example</a></summary>

```
not ok 3810 parallel/test-worker-nearheaplimit-deadlock
  ---
  duration_ms: 523.05900
  severity: crashed
  exitcode: -6
  stack: |-
    
    <--- Last few GCs --->
    
    [780525:0x3ff70001000]       12 ms: Mark-Compact 1.4 (3.5) -> 1.4 (3.5) MB, pooled: 0.0 MB, 1.06 / 0.00 ms (average mu = 0.480, current mu = 0.171) background allocation failure; GC in old space requested
    [780525:0x3ff70001000]       13 ms: Mark-Compact 1.4 (3.5) -> 1.4 (3.5) MB, pooled: 0.0 MB, 0.78 / 0.00 ms (average mu = 0.393, current mu = 0.217) background allocation failure; GC in old space requested
    
    FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
    ----- Native stack trace -----
    
     1: 0x1ed3260 node::OOMErrorHandler(char const*, v8::OOMDetails const&) [out/Release/node]
     2: 0x235d6a4 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [out/Release/node]
     3: 0x273701e v8::internal::HeapAllocator::AllocateRawWithRetryOr...
```
</details>

-------

| Reason | <code>wpt/test-hr-time</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60009/](https://ci.nodejs.org/job/node-test-pull-request/69573/), [https://github.com/nodejs/node/pull/60061/](https://ci.nodejs.org/job/node-test-pull-request/69593/)) |
| Appeared | [vm-2on5c](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67201/console), [vm-2zf9u](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67176/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69573/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69593/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67201/console">Example</a></summary>

```
not ok 4820 wpt/test-hr-time
  ---
  duration_ms: 2568.59200
  severity: fail
  exitcode: 1
  stack: |-
    [SKIPPED] idlharness-shadowrealm.window.js: ShadowRealm support is not enabled
    [SKIPPED] window-worker-timeOrigin.window.js: depends on URL.createObjectURL(blob)
    [PASS] self.performance.now() is a function that returns a number
    [PASS] self.performance.now() returns a positive number
    [PASS] self.performance.now() difference is not negative
    [PASS] Performance interface extends EventTarget.
    [PASS] self.performance.now() returns a positive number
    [PASS] self.performance.now() difference is not negative
    [PASS] idl_test validation
    [PASS] Partial interface mixin WindowOrWorkerGlobalScope: original interface mixin defined
    [PASS] Partial interface mixin WindowOrWorkerGlobalScope: member names are unique
    [PASS] Partial interface Window: member names are unique
    [PASS] Window includes GlobalEventHandlers: member names are unique
    [PASS] Window includes WindowEventH...
```
</details>

-------

| Reason | <code>wpt/test-streams</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60105/](https://ci.nodejs.org/job/node-test-pull-request/69505/), [https://github.com/nodejs/node/pull/60123/](https://ci.nodejs.org/job/node-test-pull-request/69569/)) |
| Appeared | [test-ibm-aix72-ppc64_be-2](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59305/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69505/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69569/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59305/console">Example</a></summary>

```
not ok 4844 wpt/test-streams
  ---
  duration_ms: 1472.78200
  severity: crashed
  exitcode: -5
  stack: |-
    [SKIPPED] queuing-strategies-size-function-per-global.window.js: Browser-specific test
    [SKIPPED] readable-streams/cross-realm-crash.window.js: Browser-specific test
    [SKIPPED] readable-streams/owning-type-video-frame.any.js: Browser-specific test
    [SKIPPED] readable-streams/read-task-handling.window.js: Browser-specific test
    [SKIPPED] transferable/deserialize-error.window.js: Browser-specific test
    [SKIPPED] transferable/transfer-with-messageport.window.js: Browser-specific test
    [SKIPPED] transform-streams/invalid-realm.tentative.window.js: Browser-specific test
    [PASS] Closing must be propagated backward: starts closed; preventCancel omitted; fulfilled cancel promise
    [PASS] Closing must be propagated backward: starts closed; preventCancel omitted; rejected cancel promise
    [PASS] Closing must be propagated backward: starts closed; preventCancel = undefined (falsy); ful...
```
</details>

-------

